import { defineConceptProjections } from "../../builders.js";
import { CANONICAL_VOCABULARY } from "../../vocabulary.js";

export const aggregateProjectionDeclarations = [
  defineConceptProjections("breaching", {
    equipment: {
      axis: "utility",
      family: "breaching",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad force-entry umbrella for equipment used to break doors, barriers, fortifications, or route-blocking structures.",
      subcategories: [
        "gear",
        "kit",
        "consumable",
        "weapon",
      ],
      adjacentTags: [
        "door_breaching",
        "barrier_breaking",
        "demolition",
      ],
      compositeOfAnyTags: [
        "door_breaching",
        "barrier_breaking",
        "excavation",
        "siege_support",
        "demolition",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("communication", {
    equipment: {
      axis: "utility",
      family: "communication",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad communication umbrella for equipment used to signal allies, relay messages, bridge language barriers, or coordinate silently.",
      subcategories: [
        "gear",
        "backpack",
        "kit",
        "vehicle",
        "consumable",
      ],
      adjacentTags: [
        "signaling",
        "telepathic_communication",
        "message_delivery",
      ],
      compositeOfAnyTags: [
        "signaling",
        "telepathic_communication",
        "message_delivery",
        "translation_support",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
    spell: {
      axis: "utility",
      family: "communication",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad communication umbrella for spells used to signal allies, relay messages, bridge language barriers, or coordinate silently.",
      adjacentTags: [
        "signaling",
        "telepathic_communication",
        "message_delivery",
        "translation_support",
      ],
      compositeOfAnyTags: [
        "signaling",
        "telepathic_communication",
        "message_delivery",
        "translation_support",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("consultation", {
    spell: {
      axis: "utility",
      family: "consultation",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad consultation umbrella for spells used to seek cosmic answers, diagnose mysteries, or gain non-sensory divinatory guidance.",
      adjacentTags: [
        "lore_consultation",
        "problem_diagnosis",
        "omen_guidance",
      ],
      compositeOfAnyTags: [
        "lore_consultation",
        "problem_diagnosis",
        "omen_guidance",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("cosmic_framework_setting", {
    creature: {
      axis: "setting",
      family: "planar_setting",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Strongly associated with the cosmic framework planes of Axis, the Boneyard, and the Maelstrom, which govern order, judgment, and transformative change.",
      nativeOntologyPolicy: "aggregates_native_signals",
      adjacentTags: [
        "axis_setting",
        "boneyard_setting",
        "maelstrom_setting",
      ],
      compositeOfAnyTags: [
        "axis_setting",
        "boneyard_setting",
        "maelstrom_setting",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("displacement_application", {
    hazard: {
      tag: "displacement_hazard",
      axis: "effect",
      family: "forced_position",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad displacement umbrella for hazards that drop, collapse, shove, or split creatures apart through positional disruption.",
      adjacentTags: [
        "pitfall",
        "collapse_hazard",
        "forced_separation",
      ],
      compositeOfAnyTags: [
        "pitfall",
        "collapse_hazard",
        "forced_movement",
        "forced_separation",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("elemental_plane_setting", {
    creature: {
      axis: "setting",
      family: "planar_setting",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Strongly associated with one of the elemental planes of Fire, Air, Water, or Earth.",
      nativeOntologyPolicy: "aggregates_native_signals",
      adjacentTags: [
        "plane_of_fire_setting",
        "plane_of_air_setting",
        "plane_of_water_setting",
        "plane_of_earth_setting",
      ],
      compositeOfAnyTags: [
        "plane_of_fire_setting",
        "plane_of_air_setting",
        "plane_of_water_setting",
        "plane_of_earth_setting",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("environmental_application", {
    hazard: {
      tag: "environmental_hazard",
      axis: "effect",
      family: "environmental_danger",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad environmental umbrella for elemental, toxic, contaminating, and terrain-corrupting hazards that threaten a space through recurring exposure.",
      adjacentTags: [
        "fire_hazard",
        "poison_hazard",
        "contamination_hazard",
      ],
      compositeOfAnyTags: [
        "acid_hazard",
        "cold_hazard",
        "fire_hazard",
        "electric_hazard",
        "poison_hazard",
        "respiratory_hazard",
        "sound_hazard",
        "water_hazard",
        "contamination_hazard",
        "blight_hazard",
        "overgrowth_hazard",
        "cursefield_hazard",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("expedition", {
    equipment: {
      axis: "utility",
      family: "expedition",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad expedition umbrella for travel gear, camp support, sustainment, mounts, aquatic operations, and hostile-environment endurance.",
      subcategories: [
        "gear",
        "backpack",
        "kit",
        "vehicle",
        "consumable",
        "armor",
        "shield",
        "weapon",
      ],
      adjacentTags: [
        "survival",
        "sustenance",
        "environmental_adaptation",
      ],
      compositeOfAnyTags: [
        "survival",
        "mounted_support",
        "sustenance",
        "aquatic_support",
        "environmental_adaptation",
        "camp_setup",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
    spell: {
      axis: "utility",
      family: "expedition",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad expedition umbrella for spells used for routefinding, travel-ready movement, shelter, sustainment, aquatic operations, and hostile-environment survival.",
      adjacentTags: [
        "navigation",
        "field_shelter",
        "environmental_adaptation",
      ],
      compositeOfAnyTags: [
        "navigation",
        "flight",
        "aquatic_support",
        "sustenance",
        "field_shelter",
        "environmental_adaptation",
        "wayfinding",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("guarding_hazard", {
    hazard: {
      axis: "encounter",
      family: "function",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad guarding umbrella for hazards that warn, lock down, or stand watch over a threshold, object, or protected space.",
      adjacentTags: [
        "alarm",
        "barrier_lockdown",
        "sentinel_guardian",
      ],
      compositeOfAnyTags: [
        "alarm",
        "barrier_lockdown",
        "sentinel_guardian",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("lower_plane_setting", {
    creature: {
      axis: "setting",
      family: "planar_setting",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Strongly associated with the lower planes of Hell, the Abyss, or Abaddon.",
      nativeOntologyPolicy: "aggregates_native_signals",
      adjacentTags: [
        "hell_setting",
        "abyss_setting",
        "abaddon_setting",
      ],
      compositeOfAnyTags: [
        "hell_setting",
        "abyss_setting",
        "abaddon_setting",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("movement_traversal", {
    equipment: {
      axis: "utility",
      family: "movement_traversal",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad movement-and-travel umbrella for equipment that solves climbing, routefinding, repositioning, or transport problems.",
      subcategories: [
        "gear",
        "backpack",
        "kit",
        "vehicle",
        "armor",
        "weapon",
      ],
      adjacentTags: [
        "climbing",
        "navigation",
        "transport",
      ],
      compositeOfAnyTags: [
        "climbing",
        "mobility",
        "navigation",
        "transport",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("perception_application", {
    hazard: {
      tag: "perception_hazard",
      axis: "effect",
      family: "perception_control",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad perception umbrella for hazards that attack through distorted routes, hostile illusion, or deceptive pathing rather than direct force alone.",
      adjacentTags: [
        "navigation_disruption",
        "illusion_assault",
        "false_safe_route",
      ],
      compositeOfAnyTags: [
        "navigation_disruption",
        "illusion_assault",
        "false_safe_route",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("problem_discovery", {
    spell: {
      tag: "revelation",
      axis: "utility",
      family: "revelation",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad reveal umbrella for spells that detect magic, uncover deceptions, expose invisible threats, or identify hidden supernatural problems.",
      adjacentTags: [
        "magic_detection",
        "truth_reveal",
        "hazard_revelation",
      ],
      compositeOfAnyTags: [
        "magic_detection",
        "invisibility_reveal",
        "truth_reveal",
        "curse_revelation",
        "hazard_revelation",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("problem_resolution", {
    equipment: {
      tag: "resolution",
      axis: "utility",
      family: "resolution",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad resolution umbrella for equipment used to break curses, sanctify places, contain spread, clean contamination, or solve a problem at its source.",
      subcategories: [
        "gear",
        "backpack",
        "kit",
        "consumable",
      ],
      adjacentTags: [
        "curse_removal",
        "ritual_appeasement",
        "source_revelation",
        "contamination_cleanup",
        "source_cleanup",
      ],
      compositeOfAnyTags: [
        "curse_removal",
        "sanctification",
        "ritual_appeasement",
        "source_revelation",
        "quarantine_containment",
        "contamination_cleanup",
        "source_cleanup",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
    spell: {
      tag: "resolution",
      axis: "utility",
      family: "resolution",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad resolution umbrella for spells that break curses, expel hostile presences, contain spread, purify contamination, or solve a supernatural problem at its source.",
      adjacentTags: [
        "curse_removal",
        "exorcism",
        "ritual_appeasement",
        "source_cleanup",
      ],
      compositeOfAnyTags: [
        "curse_removal",
        "exorcism",
        "sanctification",
        "ritual_appeasement",
        "quarantine_containment",
        "contamination_cleanup",
        "source_revelation",
        "source_cleanup",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("reconnaissance", {
    equipment: {
      axis: "utility",
      family: "reconnaissance",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad recon umbrella for equipment used to scout, illuminate, record evidence, track targets, or frustrate pursuit.",
      subcategories: [
        "gear",
        "backpack",
        "kit",
        "vehicle",
        "armor",
        "weapon",
      ],
      adjacentTags: [
        "scouting",
        "tracking",
        "anti_tracking",
      ],
      compositeOfAnyTags: [
        "scouting",
        "illumination",
        "surveillance_recording",
        "tracking",
        "anti_tracking",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
    spell: {
      axis: "utility",
      family: "reconnaissance",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad scouting umbrella for spells that gather remote information, extend senses, or track a target from afar.",
      adjacentTags: [
        "scouting",
        "tracking",
        "scouting_summons",
      ],
      compositeOfAnyTags: [
        "scouting",
        "tracking",
        "scouting_summons",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("security", {
    equipment: {
      axis: "utility",
      family: "security",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad security umbrella for gear that warns about intrusion, blocks magical spying, or reveals after-the-fact interference.",
      subcategories: [
        "gear",
        "backpack",
        "kit",
        "vehicle",
        "consumable",
      ],
      adjacentTags: [
        "alarm",
        "scrying_protection",
        "tamper_evidence",
      ],
      compositeOfAnyTags: [
        "alarm",
        "scrying_protection",
        "tamper_evidence",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
    spell: {
      axis: "utility",
      family: "security",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad security umbrella for spells that warn about intrusion, protect private spaces, or harden a target against magical observation and interference.",
      adjacentTags: [
        "alarm",
        "scrying_protection",
        "protective_ward",
      ],
      compositeOfAnyTags: [
        "alarm",
        "scrying_protection",
        "protective_ward",
        "countermagic",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("transformation", {
    spell: {
      axis: "transformation",
      family: "transformation",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Spells that alter a creature's body, form, or battle shape.",
      adjacentTags: [
        "battle_form",
        "animal_form",
        "elemental_form",
      ],
      compositeOfAnyTags: [
        "battle_form",
        "animal_form",
        "elemental_form",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("upper_plane_setting", {
    creature: {
      axis: "setting",
      family: "planar_setting",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Strongly associated with the upper planes of Heaven, Nirvana, or Elysium.",
      nativeOntologyPolicy: "aggregates_native_signals",
      adjacentTags: [
        "heaven_setting",
        "nirvana_setting",
        "elysium_setting",
      ],
      compositeOfAnyTags: [
        "heaven_setting",
        "nirvana_setting",
        "elysium_setting",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
  defineConceptProjections("wayfinding", {
    spell: {
      axis: "utility",
      family: "wayfinding",
      assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
      description: "Broad route-and-destination umbrella for spells that orient travel, locate a target destination, or bypass distance through strategic movement magic.",
      adjacentTags: [
        "navigation",
        "tracking",
        "long_range_teleport",
      ],
      compositeOfAnyTags: [
        "navigation",
        "tracking",
        "long_range_teleport",
        "planar_travel",
      ],
      translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
    },
  }),
];
