import type { DerivedTagRule } from "../runtime/matcher/shared.js";
import type { DerivedTagManagedCategory } from "../manifest.js";
import { AFFLICTION_DERIVED_TAG_RULES as AFFLICTION_LEGACY_DERIVED_TAG_RULES } from "./affliction.js";
import { CREATURE_DERIVED_TAG_RULES as CREATURE_LEGACY_DERIVED_TAG_RULES } from "./creature.js";
import { EQUIPMENT_DERIVED_TAG_RULES as EQUIPMENT_LEGACY_DERIVED_TAG_RULES } from "./equipment.js";
import { HAZARD_DERIVED_TAG_RULES as HAZARD_LEGACY_DERIVED_TAG_RULES } from "./hazard.js";
import { SPELL_DERIVED_TAG_RULES as SPELL_LEGACY_DERIVED_TAG_RULES } from "./spell.js";

export {
  AFFLICTION_LEGACY_DERIVED_TAG_RULES,
  CREATURE_LEGACY_DERIVED_TAG_RULES,
  EQUIPMENT_LEGACY_DERIVED_TAG_RULES,
  HAZARD_LEGACY_DERIVED_TAG_RULES,
  SPELL_LEGACY_DERIVED_TAG_RULES,
};

export const DERIVED_TAG_LEGACY_RULES_BY_CATEGORY: Record<DerivedTagManagedCategory, DerivedTagRule[]> = {
  affliction: AFFLICTION_LEGACY_DERIVED_TAG_RULES,
  creature: CREATURE_LEGACY_DERIVED_TAG_RULES,
  equipment: EQUIPMENT_LEGACY_DERIVED_TAG_RULES,
  hazard: HAZARD_LEGACY_DERIVED_TAG_RULES,
  spell: SPELL_LEGACY_DERIVED_TAG_RULES,
};
