import type { DerivedTagSeedRecordResolution } from "../types.js";
import { buildDerivedTagSeedLookup } from "./catalog-utils.js";

export const DERIVED_TAG_SEED_RECORD_RESOLUTIONS: DerivedTagSeedRecordResolution[] = [
  { recordKey: "age-of-ashes-bestiary:SVh7cPwyGgmZORVz", pack: "age-of-ashes-bestiary", name: "Scarlet Triad Boss" },
  { recordKey: "age-of-ashes-bestiary:egTpOr4Wc0L5e0iY", pack: "age-of-ashes-bestiary", name: "Scarlet Triad Enforcer" },
  { recordKey: "age-of-ashes-bestiary:lDgabn0WtDKbLtfc", pack: "age-of-ashes-bestiary", name: "Luminous Ward" },
  { recordKey: "age-of-ashes-bestiary:yrU0xi4eKBmcGudo", pack: "age-of-ashes-bestiary", name: "Animated Dragonstorm" },
  { recordKey: "agents-of-edgewatch-bestiary:HXiA7x1jWnB1BqUy", pack: "agents-of-edgewatch-bestiary", name: "Summoning Rune (Barbazu Devil)" },
  { recordKey: "agents-of-edgewatch-bestiary:QHcBauLnHzfwkDBK", pack: "agents-of-edgewatch-bestiary", name: "Summoning Rune (Cinder Rat)" },
  { recordKey: "agents-of-edgewatch-bestiary:qy53ECS2agScE7G3", pack: "agents-of-edgewatch-bestiary", name: "Kharnas's Lesser Glyph" },
  { recordKey: "agents-of-edgewatch-bestiary:rAUaIxp3QFgT3bzl", pack: "agents-of-edgewatch-bestiary", name: "Needling Stairs" },
  { recordKey: "agents-of-edgewatch-bestiary:xN3FDmrCKWW0psBu", pack: "agents-of-edgewatch-bestiary", name: "Sleepless Sun Veteran" },
  { recordKey: "battlecry-bestiary:DZiYwwjNKlAlyNU2", pack: "battlecry-bestiary", name: "Sinswarm" },
  { recordKey: "blood-lords-bestiary:DIDEV6UK5S5jQunK", pack: "blood-lords-bestiary", name: "Animated Fireplace" },
  { recordKey: "blood-lords-bestiary:I83vD5fNYIC1s3Xg", pack: "blood-lords-bestiary", name: "Time Rift" },
  { recordKey: "blood-lords-bestiary:JiT7B2Y7yYG8G0ZL", pack: "blood-lords-bestiary", name: "Nwanyian Archer" },
  { recordKey: "blood-lords-bestiary:NogvW222v6TGMz5w", pack: "blood-lords-bestiary", name: "Glyph of Warding (D5)" },
  { recordKey: "blood-lords-bestiary:lycxuueclDmiIAOF", pack: "blood-lords-bestiary", name: "Unstable Fiendflame Cage" },
  { recordKey: "blood-lords-bestiary:mZUwni8Hhv27vj4s", pack: "blood-lords-bestiary", name: "Glyph of Warding (B8)" },
  { recordKey: "blood-lords-bestiary:s16EyzsD3GLLY43o", pack: "blood-lords-bestiary", name: "Summoning Rune (Cockatrice)" },
  { recordKey: "book-of-the-dead-bestiary:GabMKY8QJOulyqAr", pack: "book-of-the-dead-bestiary", name: "Ghost Stampede" },
  { recordKey: "book-of-the-dead-bestiary:PH4GHPsekbDdyX3j", pack: "book-of-the-dead-bestiary", name: "Phantom Jailer" },
  { recordKey: "book-of-the-dead-bestiary:zqftTUpxqkdLx2IY", pack: "book-of-the-dead-bestiary", name: "Ecorche" },
  { recordKey: "claws-of-the-tyrant-bestiary:3wLksd7BQeyxygyR", pack: "claws-of-the-tyrant-bestiary", name: "Iomedae's Flame" },
  { recordKey: "curtain-call-bestiary:0w2my6fBuCH98gV9", pack: "curtain-call-bestiary", name: "Mocking Puppets" },
  { recordKey: "curtain-call-bestiary:CbDmMyhdy0O6Nndy", pack: "curtain-call-bestiary", name: "Archway Barrier" },
  { recordKey: "curtain-call-bestiary:NKj4bVrJwkf85jwV", pack: "curtain-call-bestiary", name: "Spectral Opera" },
  { recordKey: "curtain-call-bestiary:RzrRRymlgfoGIevs", pack: "curtain-call-bestiary", name: "Mask Summoning Rune" },
  { recordKey: "curtain-call-bestiary:SGWcXt1bqMh09qab", pack: "curtain-call-bestiary", name: "Animated Boiler" },
  { recordKey: "curtain-call-bestiary:wJTI5OsZaV7n2VUp", pack: "curtain-call-bestiary", name: "Harmonic Barrier" },
  { recordKey: "extinction-curse-bestiary:0fe7PVMIq92fkUJK", pack: "extinction-curse-bestiary", name: "Dream Pollen Pod" },
  { recordKey: "extinction-curse-bestiary:1CjTIaMYUvQUkQI2", pack: "extinction-curse-bestiary", name: "Mukradi Summoning Runes" },
  { recordKey: "extinction-curse-bestiary:1HYH5BgFGtFxVMpc", pack: "extinction-curse-bestiary", name: "Krooth Summoning Rune" },
  { recordKey: "extinction-curse-bestiary:b7ADAguVQLHCauWO", pack: "extinction-curse-bestiary", name: "Poisoned Secret Door Trap" },
  { recordKey: "extinction-curse-bestiary:wQHcJGJ9rSyFQFPB", pack: "extinction-curse-bestiary", name: "Envenomed Thorns Trap" },
  { recordKey: "fists-of-the-ruby-phoenix-bestiary:BcRxQjtyMNgiEpvb", pack: "fists-of-the-ruby-phoenix-bestiary", name: "Floating Flamethrower" },
  { recordKey: "gatewalkers-bestiary:6c4I4D3DgJmsSZEI", pack: "gatewalkers-bestiary", name: "Haunted Aiudara" },
  { recordKey: "gatewalkers-bestiary:F0YvQwAEdIuZ7mQI", pack: "gatewalkers-bestiary", name: "Poisonous Atmosphere" },
  { recordKey: "gatewalkers-bestiary:GJCVwAFKDG91TXok", pack: "gatewalkers-bestiary", name: "Formian Sting Trench" },
  { recordKey: "gatewalkers-bestiary:itAkkjCM3EUQ4heC", pack: "gatewalkers-bestiary", name: "Quarry Construct" },
  { recordKey: "gatewalkers-bestiary:y9W4wnQ5mzs09Px8", pack: "gatewalkers-bestiary", name: "Soporific Lecture" },
  { recordKey: "hazards:2GAOUxDfoA48uCWP", pack: "hazards", name: "Fireball Rune" },
  { recordKey: "hazards:4jAJh3cTLIgkqtou", pack: "hazards", name: "Malevolent Mannequins" },
  { recordKey: "hazards:A93flWUsot3FmC7t", pack: "hazards", name: "Yellow Mold" },
  { recordKey: "hazards:AqK60DreNDtgDb4o", pack: "hazards", name: "Poisonous Mold" },
  { recordKey: "hazards:O0qA1ElCOgYGEBtL", pack: "hazards", name: "Eternal Flame" },
  { recordKey: "hazards:m4PRYxFq9ojcwesh", pack: "hazards", name: "Pharaoh's Ward" },
  { recordKey: "hazards:nO4osrBRnpWKFCMP", pack: "hazards", name: "Summoning Rune" },
  { recordKey: "hazards:yM4G2LvMwvkIRx0G", pack: "hazards", name: "Planar Rift" },
  { recordKey: "hellbreakers-bestiary:9a0GH3YuaACzsyof", pack: "hellbreakers-bestiary", name: "Captain Lamperia Bane" },
  { recordKey: "hellbreakers-bestiary:KqRkvwwQWX6C8YAx", pack: "hellbreakers-bestiary", name: "Play Time" },
  { recordKey: "hellbreakers-bestiary:PYqZIgsj26WyJOlN", pack: "hellbreakers-bestiary", name: "Hecatinia" },
  { recordKey: "hellbreakers-bestiary:pjEz149NBKw1h96g", pack: "hellbreakers-bestiary", name: "False Hellbreaker" },
  { recordKey: "kingmaker-bestiary:Dxn6t9aoWUwPn6CE", pack: "kingmaker-bestiary", name: "Virthad" },
  { recordKey: "kingmaker-bestiary:I8pvGB7SiXQ6SnGn", pack: "kingmaker-bestiary", name: "Stygian Fires" },
  { recordKey: "kingmaker-bestiary:nDFogS2qQJomjfmR", pack: "kingmaker-bestiary", name: "Fetch Stalker" },
  { recordKey: "kingmaker-bestiary:oBPdL0icCG5zmknB", pack: "kingmaker-bestiary", name: "Glyph of Warding (Kingmaker)" },
  { recordKey: "kingmaker-bestiary:z1Hk6z6RU4sF9aJU", pack: "kingmaker-bestiary", name: "Thresholder Disciple" },
  { recordKey: "lost-omens-bestiary:8AANjQtU703ghIsR", pack: "lost-omens-bestiary", name: "Animated Bamboo Figurine" },
  { recordKey: "lost-omens-bestiary:95IcOUvxABvj5lvo", pack: "lost-omens-bestiary", name: "Changeling Hellknight" },
  { recordKey: "lost-omens-bestiary:fXlmbjtV3spZlmGS", pack: "lost-omens-bestiary", name: "Animated Kite" },
  { recordKey: "myth-speaker-bestiary:o2O3dPdWCCgRcIO3", pack: "myth-speaker-bestiary", name: "Animated Panoply" },
  { recordKey: "one-shot-bestiary:E6e8iE0BgIxLYqQZ", pack: "one-shot-bestiary", name: "Poisoned Lock (Lionlodge)" },
  { recordKey: "one-shot-bestiary:Z6aUTOMtvX2erFeA", pack: "one-shot-bestiary", name: "Soulbound Guardian" },
  { recordKey: "outlaws-of-alkenstar-bestiary:QQ2Ci8E2lkxG8QIV", pack: "outlaws-of-alkenstar-bestiary", name: "Subduing Gas Chamber" },
  { recordKey: "outlaws-of-alkenstar-bestiary:t60zBqM2apOZtOaC", pack: "outlaws-of-alkenstar-bestiary", name: "Glass Elephant" },
  { recordKey: "pathfinder-bestiary:3nOBhH8j9I7ps6fC", pack: "pathfinder-bestiary", name: "Green Hag" },
  { recordKey: "pathfinder-bestiary:AdQVjlOWB6rmBRVp", pack: "pathfinder-bestiary", name: "Doppelganger" },
  { recordKey: "pathfinder-bestiary:hOXpmWmXU8N3n4Bw", pack: "pathfinder-bestiary", name: "Raja Rakshasa" },
  { recordKey: "pathfinder-dark-archive:P2fNCqJsR0gazMzM", pack: "pathfinder-dark-archive", name: "Exhaling Portal" },
  { recordKey: "pathfinder-monster-core-2:KxVSaTjRAUwTWeDX", pack: "pathfinder-monster-core-2", name: "Atrixyl" },
  { recordKey: "pathfinder-monster-core-2:jaKVhw83CPKpW9UJ", pack: "pathfinder-monster-core-2", name: "Animated Trebuchet" },
  { recordKey: "pathfinder-monster-core:3nUt7cW8fqE5IpyE", pack: "pathfinder-monster-core", name: "Envyspawn" },
  { recordKey: "pathfinder-monster-core:PLZk6zY5iwccPTPS", pack: "pathfinder-monster-core", name: "Orc Commander" },
  { recordKey: "pathfinder-monster-core:V90OYOMyyPLPJuod", pack: "pathfinder-monster-core", name: "Orc Veteran" },
  { recordKey: "pathfinder-monster-core:ccAeM0tNgf5aVokj", pack: "pathfinder-monster-core", name: "Slothspawn" },
  { recordKey: "pathfinder-monster-core:eke1AhiUjNPpyRhG", pack: "pathfinder-monster-core", name: "Gluttonyspawn" },
  { recordKey: "pathfinder-monster-core:h4cMwW2K34KheWtD", pack: "pathfinder-monster-core", name: "Pridespawn" },
  { recordKey: "pathfinder-monster-core:k4fqHhiax2GPrkbh", pack: "pathfinder-monster-core", name: "Lustspawn" },
  { recordKey: "pathfinder-monster-core:kngoPtu4Cr3BtgW8", pack: "pathfinder-monster-core", name: "Cuckoo Hag" },
  { recordKey: "pathfinder-monster-core:pH2yNe16EnoJ8R0i", pack: "pathfinder-monster-core", name: "Gimmerling" },
  { recordKey: "pathfinder-monster-core:pkhNqTDUttoAzcKn", pack: "pathfinder-monster-core", name: "Greedspawn" },
  { recordKey: "pathfinder-monster-core:yv7hdQ3MO3pLgCF5", pack: "pathfinder-monster-core", name: "Wrathspawn" },
  { recordKey: "pathfinder-npc-core:02AGznZTv5jjcnOg", pack: "pathfinder-npc-core", name: "Hellknight Cavalry Brigade" },
  { recordKey: "pathfinder-npc-core:0cj7cQhgNnLxbUmR", pack: "pathfinder-npc-core", name: "Mage Knight" },
  { recordKey: "pathfinder-npc-core:2hBS767YPGZwXeiP", pack: "pathfinder-npc-core", name: "Mixed Martial Artist" },
  { recordKey: "pathfinder-npc-core:3m8fkhbaUubLeckt", pack: "pathfinder-npc-core", name: "Local Herbalist" },
  { recordKey: "pathfinder-npc-core:8WFse73d3kgTPbje", pack: "pathfinder-npc-core", name: "Orc Agriculturist" },
  { recordKey: "pathfinder-npc-core:9EzCOBw3rMsyfr5Q", pack: "pathfinder-npc-core", name: "Halfling Yarnspinner" },
  { recordKey: "pathfinder-npc-core:9wdaQ6ZuBAZx9Vjk", pack: "pathfinder-npc-core", name: "Envoy" },
  { recordKey: "pathfinder-npc-core:A4XWtiK4iStEDAUu", pack: "pathfinder-npc-core", name: "Orc Veteran Master" },
  { recordKey: "pathfinder-npc-core:AhyWwDKH1gIVSfys", pack: "pathfinder-npc-core", name: "Kholo Pragmatist" },
  { recordKey: "pathfinder-npc-core:AxB7Sh2Bbt9AcDPp", pack: "pathfinder-npc-core", name: "Catfolk Name Collector" },
  { recordKey: "pathfinder-npc-core:B9NoqcAASkg2Gjz3", pack: "pathfinder-npc-core", name: "Courtesan" },
  { recordKey: "pathfinder-npc-core:BYpxg06tP5hI6CzQ", pack: "pathfinder-npc-core", name: "Innkeeper" },
  { recordKey: "pathfinder-npc-core:C8Bo22NBYGoj9Fwd", pack: "pathfinder-npc-core", name: "Orc Skullcrushers" },
  { recordKey: "pathfinder-npc-core:D3SJlR6iZYMgL2s8", pack: "pathfinder-npc-core", name: "Artillerist" },
  { recordKey: "pathfinder-npc-core:Dd7E7pMKxPhrXaa8", pack: "pathfinder-npc-core", name: "Expedition Leader" },
  { recordKey: "pathfinder-npc-core:G2AJ9Ya7QG7ebNPO", pack: "pathfinder-npc-core", name: "Master of Disguise" },
  { recordKey: "pathfinder-npc-core:GKDMvepxkEsUnN5d", pack: "pathfinder-npc-core", name: "Miner" },
  { recordKey: "pathfinder-npc-core:GZxDz6PKbHs9f2WN", pack: "pathfinder-npc-core", name: "Hobgoblin Battalion" },
  { recordKey: "pathfinder-npc-core:GuYToKMrt5mxxZW6", pack: "pathfinder-npc-core", name: "Gunsmith" },
  { recordKey: "pathfinder-npc-core:Iax22298eQbIhIQK", pack: "pathfinder-npc-core", name: "Heavy Cavalry" },
  { recordKey: "pathfinder-npc-core:MxcprNbX7hcpAU8p", pack: "pathfinder-npc-core", name: "Departmental Chair" },
  { recordKey: "pathfinder-npc-core:O0n4NLOuY3ZkEKbF", pack: "pathfinder-npc-core", name: "Hobgoblin Spellbreaker" },
  { recordKey: "pathfinder-npc-core:OB4x3FBwjJBfOsi3", pack: "pathfinder-npc-core", name: "Arms Dealer" },
  { recordKey: "pathfinder-npc-core:UWBT8xEvGfHaAj0U", pack: "pathfinder-npc-core", name: "Court Historian" },
  { recordKey: "pathfinder-npc-core:V6UV4BeMRUUwGL0g", pack: "pathfinder-npc-core", name: "Natural Scientist" },
  { recordKey: "pathfinder-npc-core:Wv4jaiD6X8negvH2", pack: "pathfinder-npc-core", name: "Dockhand" },
  { recordKey: "pathfinder-npc-core:WzBMIigC3lfvZyhJ", pack: "pathfinder-npc-core", name: "Legbreaker" },
  { recordKey: "pathfinder-npc-core:XnfZwf1g4rfan1gY", pack: "pathfinder-npc-core", name: "Driver" },
  { recordKey: "pathfinder-npc-core:Y0MSOv0l5ePhP3Co", pack: "pathfinder-npc-core", name: "Astronomer" },
  { recordKey: "pathfinder-npc-core:eF87AWFclYpu1cgD", pack: "pathfinder-npc-core", name: "Beast Tamer" },
  { recordKey: "pathfinder-npc-core:fDUocyyYWJU1grxV", pack: "pathfinder-npc-core", name: "Halfling Head Chef" },
  { recordKey: "pathfinder-npc-core:fSwCwS75z9FeUazU", pack: "pathfinder-npc-core", name: "Knight" },
  { recordKey: "pathfinder-npc-core:hXcBMFGA45ES01Lb", pack: "pathfinder-npc-core", name: "Orc Gamekeeper" },
  { recordKey: "pathfinder-npc-core:lhhdqML98o90gXqO", pack: "pathfinder-npc-core", name: "Construction Worker" },
  { recordKey: "pathfinder-npc-core:m7UKHHTw1WpDCfsL", pack: "pathfinder-npc-core", name: "Kobold Egg Guardian" },
  { recordKey: "pathfinder-npc-core:msItO7UjfQfWe9nZ", pack: "pathfinder-npc-core", name: "Dromaar Lorekeeper" },
  { recordKey: "pathfinder-npc-core:qtD7Xa8Mgl0Y63os", pack: "pathfinder-npc-core", name: "Chronicler" },
  { recordKey: "pathfinder-npc-core:rY3uqGq5QyvNOU91", pack: "pathfinder-npc-core", name: "Dwarf Smith" },
  { recordKey: "pathfinder-npc-core:tGndoQjOV5Mj5Foh", pack: "pathfinder-npc-core", name: "Musketeer" },
  { recordKey: "pathfinder-npc-core:taNAx8xPuOJ3EmxC", pack: "pathfinder-npc-core", name: "Harrow Reader" },
  { recordKey: "pathfinder-npc-core:xnHaTClGCleGFoLP", pack: "pathfinder-npc-core", name: "Dwarf Battalion" },
  { recordKey: "pathfinder-npc-core:z1tLeckmpJuStmlx", pack: "pathfinder-npc-core", name: "Messenger" },
  { recordKey: "prey-for-death-bestiary:2c6GMe3gATc3l7ZV", pack: "prey-for-death-bestiary", name: "Flensing Floor" },
  { recordKey: "prey-for-death-bestiary:tKqmm3jB9aZBJYHN", pack: "prey-for-death-bestiary", name: "Berserker Ordulf" },
  { recordKey: "quest-for-the-frozen-flame-bestiary:HMpKt3b2LfrXa9yV", pack: "quest-for-the-frozen-flame-bestiary", name: "Death's Slumber Ward" },
  { recordKey: "quest-for-the-frozen-flame-bestiary:XhzGe3CAlugFu8AM", pack: "quest-for-the-frozen-flame-bestiary", name: "Forest Fire" },
  { recordKey: "quest-for-the-frozen-flame-bestiary:wuV8k7N1cEJBYNbK", pack: "quest-for-the-frozen-flame-bestiary", name: "Weykoward" },
  { recordKey: "revenge-of-the-runelords-bestiary:CPkNCHW9cGAUq099", pack: "revenge-of-the-runelords-bestiary", name: "Greedspawn" },
  { recordKey: "revenge-of-the-runelords-bestiary:EsCu5ehBgpwRHKGZ", pack: "revenge-of-the-runelords-bestiary", name: "Pridespawn Sentinel" },
  { recordKey: "revenge-of-the-runelords-bestiary:bWqwwzOECcOmXLQD", pack: "revenge-of-the-runelords-bestiary", name: "Lograsi" },
  { recordKey: "revenge-of-the-runelords-bestiary:bwpKnfGrRdLrSEyJ", pack: "revenge-of-the-runelords-bestiary", name: "Knight of Malice" },
  { recordKey: "season-of-ghosts-bestiary:52dTAJPXCnE48a5a", pack: "season-of-ghosts-bestiary", name: "Noppera-bo Grunt" },
  { recordKey: "season-of-ghosts-bestiary:6UkZJRICusE2EOhS", pack: "season-of-ghosts-bestiary", name: "Noppera-Bo Impersonator (Primal)" },
  { recordKey: "season-of-ghosts-bestiary:APu2EqTJ4QdHkwtR", pack: "season-of-ghosts-bestiary", name: "Noppera-bo Trickster" },
  { recordKey: "season-of-ghosts-bestiary:DueMGlf6tX1bqwSS", pack: "season-of-ghosts-bestiary", name: "Witherweird Runes" },
  { recordKey: "season-of-ghosts-bestiary:Mt053Q3jCVLXp6us", pack: "season-of-ghosts-bestiary", name: "Noppera-Bo Impersonator (Occult)" },
  { recordKey: "season-of-ghosts-bestiary:QSa1PbcvbgDv8Zpr", pack: "season-of-ghosts-bestiary", name: "Noppera-Bo Impersonator (Arcane)" },
  { recordKey: "season-of-ghosts-bestiary:V67VC975O8iC1Yq2", pack: "season-of-ghosts-bestiary", name: "Animated Axe" },
  { recordKey: "seven-dooms-for-sandpoint-bestiary:xoh5JAue3PtjH6dS", pack: "seven-dooms-for-sandpoint-bestiary", name: "Greedspawn" },
  { recordKey: "shades-of-blood-bestiary:9I6hHRcVLPbqcZvo", pack: "shades-of-blood-bestiary", name: "Furious Flame" },
  { recordKey: "shades-of-blood-bestiary:ITCAohOOP7A1AK2X", pack: "shades-of-blood-bestiary", name: "Conundrum Ward" },
  { recordKey: "sky-kings-tomb-bestiary:yGlzyyqtMfngIBON", pack: "sky-kings-tomb-bestiary", name: "Buried Shock Glyph" },
  { recordKey: "spells-srd:0AZOIMRvZtePuGOw", pack: "spells-srd", name: "Rainbow Fumarole" },
  { recordKey: "spells-srd:0fYE64odlKqISzft", pack: "spells-srd", name: "Rusting Grasp" },
  { recordKey: "spells-srd:1Yoipc5jNcMehtEW", pack: "spells-srd", name: "Slashing Gust" },
  { recordKey: "spells-srd:1hLxZznnA2kvXlIt", pack: "spells-srd", name: "Cutting Insult" },
  { recordKey: "spells-srd:1xM9muPRa8hiyJtI", pack: "spells-srd", name: "Dive and Breach" },
  { recordKey: "spells-srd:2Vkd1IxylPceUAAF", pack: "spells-srd", name: "Regenerate" },
  { recordKey: "spells-srd:2gQYrCPwBmwau26O", pack: "spells-srd", name: "Life Link" },
  { recordKey: "spells-srd:3A3ueS9Q0s3U8KXE", pack: "spells-srd", name: "Noxious Metals" },
  { recordKey: "spells-srd:3GXU3ugrwLv0P7AH", pack: "spells-srd", name: "Ignite Fireworks" },
  { recordKey: "spells-srd:3VxVbZqIRvpKkg3O", pack: "spells-srd", name: "Fungal Infestation" },
  { recordKey: "spells-srd:3ZxaIw1FOOocJboH", pack: "spells-srd", name: "Musical Shift" },
  { recordKey: "spells-srd:3qx1axryNbl97ker", pack: "spells-srd", name: "Blister Bomb" },
  { recordKey: "spells-srd:4MOew29Z1oCX8O28", pack: "spells-srd", name: "Moment of Renewal" },
  { recordKey: "spells-srd:4k99nOJudmeNnBTF", pack: "spells-srd", name: "Shielded Arm" },
  { recordKey: "spells-srd:5KmyO4YSGEAUdgAS", pack: "spells-srd", name: "Funeral Flames" },
  { recordKey: "spells-srd:5QD75UbyB5EiG3yz", pack: "spells-srd", name: "Scorching Blast" },
  { recordKey: "spells-srd:5bTt2CvYHPvaR7QQ", pack: "spells-srd", name: "Interplanar Teleport" },
  { recordKey: "spells-srd:6DfLZBl8wKIV03Iq", pack: "spells-srd", name: "Ignition" },
  { recordKey: "spells-srd:6XscENSWyYRHqK0A", pack: "spells-srd", name: "Airlift" },
  { recordKey: "spells-srd:7uL4XhHpxZpgNJPh", pack: "spells-srd", name: "Blinding Foam" },
  { recordKey: "spells-srd:9h9YCncqah6VNsKf", pack: "spells-srd", name: "Acid Grip" },
  { recordKey: "spells-srd:9iJaD4S7ptUeq5vO", pack: "spells-srd", name: "Positive Attunement" },
  { recordKey: "spells-srd:9kOI14Jep97TzGO7", pack: "spells-srd", name: "Life-Giving Form" },
  { recordKey: "spells-srd:A16eFTRh82xIjMu8", pack: "spells-srd", name: "Divine Immolation" },
  { recordKey: "spells-srd:AWxS2lr86qNNQVDT", pack: "spells-srd", name: "Diadem of Divine Radiance" },
  { recordKey: "spells-srd:AfOpnnwdZwHi2Tnc", pack: "spells-srd", name: "Protect Companion" },
  { recordKey: "spells-srd:AnWCohzPgK4L9GVl", pack: "spells-srd", name: "Detect Scrying" },
  { recordKey: "spells-srd:BAu5AgqoO556clyK", pack: "spells-srd", name: "Rewrite Possibility" },
  { recordKey: "spells-srd:BWvGBx51RevizICD", pack: "spells-srd", name: "Mutilate" },
  { recordKey: "spells-srd:C2w3YfBKjIRS07DP", pack: "spells-srd", name: "Hidden Mind" },
  { recordKey: "spells-srd:CIjj9CU5ekeq1oLT", pack: "spells-srd", name: "Warding Aggression" },
  { recordKey: "spells-srd:CR8OKDbeFJoZbOCu", pack: "spells-srd", name: "Extend Boost" },
  { recordKey: "spells-srd:CXpOlv2ZZq2jVbRX", pack: "spells-srd", name: "Blood in the Water" },
  { recordKey: "spells-srd:D7ZEhTNIDWDLC2J4", pack: "spells-srd", name: "Puff of Poison" },
  { recordKey: "spells-srd:DH9Y3RQGWO0GzXGU", pack: "spells-srd", name: "Protector's Sphere" },
  { recordKey: "spells-srd:EPTmSiURVp2ldkVB", pack: "spells-srd", name: "Armor of Thorn and Claw" },
  { recordKey: "spells-srd:ES6FkwXXqYr4ujQH", pack: "spells-srd", name: "Blood Feast" },
  { recordKey: "spells-srd:EUMjrJJwSgsqNidi", pack: "spells-srd", name: "Anticipate Peril" },
  { recordKey: "spells-srd:EfFMLVbmkBWmzoLF", pack: "spells-srd", name: "Clear Mind" },
  { recordKey: "spells-srd:EoKBlgf6Smt8opaU", pack: "spells-srd", name: "Veil of Privacy" },
  { recordKey: "spells-srd:F1qxaqsEItmBura2", pack: "spells-srd", name: "Nature's Pathway" },
  { recordKey: "spells-srd:HStu2Yhw3iQER9tY", pack: "spells-srd", name: "Boost Eidolon" },
  { recordKey: "spells-srd:I2IgZu4Rd2dz0J6v", pack: "spells-srd", name: "Sawtooth Terrain" },
  { recordKey: "spells-srd:I8CPe9Pp7GABqOyB", pack: "spells-srd", name: "Zeal for Battle" },
  { recordKey: "spells-srd:IERHT6v4o5ISvuJG", pack: "spells-srd", name: "Halcyon Mists" },
  { recordKey: "spells-srd:IHUs4qn27RrdFQ5Y", pack: "spells-srd", name: "Cosmic Form" },
  { recordKey: "spells-srd:IT1aaqDBAISlHDUV", pack: "spells-srd", name: "Achaekek's Clutch" },
  { recordKey: "spells-srd:LQzlKbYjZSMFQawP", pack: "spells-srd", name: "Locate" },
  { recordKey: "spells-srd:LTUaK3smfm5eDiFK", pack: "spells-srd", name: "Song of Marching" },
  { recordKey: "spells-srd:M5dp7ILSCKID9fDK", pack: "spells-srd", name: "Shock to the System" },
  { recordKey: "spells-srd:MFPvs0ARxtThYPFq", pack: "spells-srd", name: "Dimensional Excision" },
  { recordKey: "spells-srd:MLYTWHfewOpI3Cz7", pack: "spells-srd", name: "Field of Razors" },
  { recordKey: "spells-srd:MLdMUOdwSKegOGlo", pack: "spells-srd", name: "Dull Ambition" },
  { recordKey: "spells-srd:MPxbKoR54gkYkqLO", pack: "spells-srd", name: "Gouging Claw" },
  { recordKey: "spells-srd:My7FvAoLYgGDDBzy", pack: "spells-srd", name: "Antimagic Field" },
  { recordKey: "spells-srd:NacrNSvfODxpZena", pack: "spells-srd", name: "Blazing Blade" },
  { recordKey: "spells-srd:NzXpEzcZAjuDTZjK", pack: "spells-srd", name: "Aerial Form" },
  { recordKey: "spells-srd:OJ91rm1FkJSlf3nk", pack: "spells-srd", name: "Ancient Dust" },
  { recordKey: "spells-srd:PIdXUPtE6ZGpFpXV", pack: "spells-srd", name: "Domora's Defense" },
  { recordKey: "spells-srd:PrlR2sLWeiuTcPF2", pack: "spells-srd", name: "Earth's Bile" },
  { recordKey: "spells-srd:R8bqnYiThB6MYTxD", pack: "spells-srd", name: "Phantom Pain" },
  { recordKey: "spells-srd:RCbLd7dfquHnuvrZ", pack: "spells-srd", name: "False Vision" },
  { recordKey: "spells-srd:RGBZrVRIEDb2G48h", pack: "spells-srd", name: "Soothing Mist" },
  { recordKey: "spells-srd:Ru9v8U9IRk3LtWx8", pack: "spells-srd", name: "Feral Shades" },
  { recordKey: "spells-srd:S708JF3E0kuhuRzG", pack: "spells-srd", name: "Bone Spray" },
  { recordKey: "spells-srd:Seaah9amXg70RKw2", pack: "spells-srd", name: "Water Walk" },
  { recordKey: "spells-srd:SnaLVgxZ9ryUFmUr", pack: "spells-srd", name: "Restoration" },
  { recordKey: "spells-srd:SnjhtQYexDtNDdEg", pack: "spells-srd", name: "Stabilize" },
  { recordKey: "spells-srd:TYbCj4dgXDOZou9k", pack: "spells-srd", name: "Reinforce Eidolon" },
  { recordKey: "spells-srd:TaaMEYdZXQXF0Sks", pack: "spells-srd", name: "Blood Vendetta" },
  { recordKey: "spells-srd:ThE5zPYKF4weiljj", pack: "spells-srd", name: "Show the Way" },
  { recordKey: "spells-srd:U0hL0LLaprcnAyzC", pack: "spells-srd", name: "Migration" },
  { recordKey: "spells-srd:V4IpjSlefultlOuY", pack: "spells-srd", name: "Bone Flense" },
  { recordKey: "spells-srd:VXUrO8TwRqBpNzdU", pack: "spells-srd", name: "Bloodspray Curse" },
  { recordKey: "spells-srd:Vbj8bTQ1nwrOBbYF", pack: "spells-srd", name: "Live Wire" },
  { recordKey: "spells-srd:VrhCpCIQB8PFax77", pack: "spells-srd", name: "Spellmaster's Ward" },
  { recordKey: "spells-srd:WV2aMNN9DO5ZBjSv", pack: "spells-srd", name: "Flense" },
  { recordKey: "spells-srd:XEhzFKNTSARsofav", pack: "spells-srd", name: "Advanced Scurvy" },
  { recordKey: "spells-srd:Xrz6wPXDBUr27izR", pack: "spells-srd", name: "Grave Impressions" },
  { recordKey: "spells-srd:YrzBLPLd3r9m6t1p", pack: "spells-srd", name: "Fire Shield" },
  { recordKey: "spells-srd:Z3kJty995FkrsZRb", pack: "spells-srd", name: "Combustion" },
  { recordKey: "spells-srd:a5uwCgOe7ayHPtHe", pack: "spells-srd", name: "Enhance Senses" },
  { recordKey: "spells-srd:aAbfKn8maGjJjk2W", pack: "spells-srd", name: "Mystic Armor" },
  { recordKey: "spells-srd:b5sGjGlBf58f8jn0", pack: "spells-srd", name: "Air Walk" },
  { recordKey: "spells-srd:b6AQvzs8EotmlK56", pack: "spells-srd", name: "Flourishing Flora" },
  { recordKey: "spells-srd:bIz6QnUIxu5Z7vEH", pack: "spells-srd", name: "Final Fate of the Locust Host" },
  { recordKey: "spells-srd:bVvGpSOg2WaTUItS", pack: "spells-srd", name: "Cinder Swarm" },
  { recordKey: "spells-srd:cCFDnmFB1EGeQUeA", pack: "spells-srd", name: "Friendly Push" },
  { recordKey: "spells-srd:cwXiKPkZrIupjwlQ", pack: "spells-srd", name: "Summoner's Precaution" },
  { recordKey: "spells-srd:dKWc83KKiXoIJkhp", pack: "spells-srd", name: "Beheading Buzz Saw" },
  { recordKey: "spells-srd:dgMauNKWeRIu8pMN", pack: "spells-srd", name: "Glass Sand" },
  { recordKey: "spells-srd:dqaCLzINHBiKjh4J", pack: "spells-srd", name: "Call to Arms" },
  { recordKey: "spells-srd:e36Z2t6tLdW3RUzZ", pack: "spells-srd", name: "Elemental Gift" },
  { recordKey: "spells-srd:eexkxcqnkXazsGfK", pack: "spells-srd", name: "Enervation" },
  { recordKey: "spells-srd:eidmNlfl2DUVIclc", pack: "spells-srd", name: "Brine Dragon Bile" },
  { recordKey: "spells-srd:f8hRqLJaxBVhF1u0", pack: "spells-srd", name: "Acid Arrow" },
  { recordKey: "spells-srd:f9m9DayyGy3meqUX", pack: "spells-srd", name: "Dehydrate" },
  { recordKey: "spells-srd:fAlzXtQAASaJx0mY", pack: "spells-srd", name: "Life Boost" },
  { recordKey: "spells-srd:fI20AVwOzJMHXRdo", pack: "spells-srd", name: "Levitate" },
  { recordKey: "spells-srd:g1eY1vN44mgluE33", pack: "spells-srd", name: "Charged Javelin" },
  { recordKey: "spells-srd:gISYsBFby1TiXfBt", pack: "spells-srd", name: "Acid Splash" },
  { recordKey: "spells-srd:h47yv6j6x1pUtzlr", pack: "spells-srd", name: "Arcane Countermeasure" },
  { recordKey: "spells-srd:hW9pgce6vTme61g1", pack: "spells-srd", name: "Unfetter Eidolon" },
  { recordKey: "spells-srd:hoR6w8BqX2F35Tdx", pack: "spells-srd", name: "Blistering Invective" },
  { recordKey: "spells-srd:ikSb3LRGnrwXJBVX", pack: "spells-srd", name: "Vital Beacon" },
  { recordKey: "spells-srd:k34hDOfIIMAxNL4a", pack: "spells-srd", name: "Grim Tendrils" },
  { recordKey: "spells-srd:l6zjNysNedpJcmDT", pack: "spells-srd", name: "Know the Enemy" },
  { recordKey: "spells-srd:lJdAvY1sJyEmNDc6", pack: "spells-srd", name: "Phoenix Ward" },
  { recordKey: "spells-srd:lOZhcvtej10TqlQm", pack: "spells-srd", name: "Lifelink Surge" },
  { recordKey: "spells-srd:lV8FkHZtzZu7Cy6j", pack: "spells-srd", name: "Evolution Surge" },
  { recordKey: "spells-srd:lY9fOk1qBDDhBT8s", pack: "spells-srd", name: "Protective Wards" },
  { recordKey: "spells-srd:nnYxDWU3Vzg9WenB", pack: "spells-srd", name: "Fire's Pathway" },
  { recordKey: "spells-srd:nsQvjNyg4Whw2mek", pack: "spells-srd", name: "Divine Aura" },
  { recordKey: "spells-srd:ovx7O2FHvkjXhMcA", pack: "spells-srd", name: "Perseis's Precautions" },
  { recordKey: "spells-srd:p6ebe2PliRkGbmiV", pack: "spells-srd", name: "Flame Dancer" },
  { recordKey: "spells-srd:pfFxj4NI5KwO119I", pack: "spells-srd", name: "Blind Eye" },
  { recordKey: "spells-srd:r3NeUnsgt9mS03Sn", pack: "spells-srd", name: "Shocking Grasp" },
  { recordKey: "spells-srd:ru3YdXajUREbKQDV", pack: "spells-srd", name: "Return Beacon" },
  { recordKey: "spells-srd:sUvTGELaggrBSgGm", pack: "spells-srd", name: "Implement of Destruction" },
  { recordKey: "spells-srd:szIyEsvihc5e1w8n", pack: "spells-srd", name: "Soothe" },
  { recordKey: "spells-srd:tBC1QmB33KWIuBFX", pack: "spells-srd", name: "Spiritual Renewal" },
  { recordKey: "spells-srd:tf4PMMMzR5xxJDun", pack: "spells-srd", name: "Cleansing Flames" },
  { recordKey: "spells-srd:tj86Rnq3QuQnDtG3", pack: "spells-srd", name: "Hunter's Vision" },
  { recordKey: "spells-srd:v4KzRPol5XQOOmk0", pack: "spells-srd", name: "Heat Metal" },
  { recordKey: "spells-srd:vGMbpV7GWIFPNUaZ", pack: "spells-srd", name: "Bursting Bloom" },
  { recordKey: "spells-srd:vQMAdnIwnV9prPiG", pack: "spells-srd", name: "Element Embodied" },
  { recordKey: "spells-srd:vb2dFNtbofJ7A9BW", pack: "spells-srd", name: "Summoner's Visage" },
  { recordKey: "spells-srd:x5rGOmhDRDVQPrnW", pack: "spells-srd", name: "Field of Life" },
  { recordKey: "spells-srd:xn0V2HDrmDWNzPEt", pack: "spells-srd", name: "Savor the Sting" },
  { recordKey: "spells-srd:ziHDISWkFSwz3pmn", pack: "spells-srd", name: "Delay Affliction" },
  { recordKey: "spore-war-bestiary:eTFchJ8UliMAaKzY", pack: "spore-war-bestiary", name: "Enhanced Fireball Rune" },
  { recordKey: "stolen-fate-bestiary:UX7QKytewemOnNeX", pack: "stolen-fate-bestiary", name: "Stage Fire" },
  { recordKey: "strength-of-thousands-bestiary:5f8EKdudDgYRBmqA", pack: "strength-of-thousands-bestiary", name: "Stinger Ward Trap" },
  { recordKey: "strength-of-thousands-bestiary:JRn1QlBUtlU7xjYR", pack: "strength-of-thousands-bestiary", name: "Venom Pool" },
  { recordKey: "strength-of-thousands-bestiary:ZDiRrUHkhFz0mLc7", pack: "strength-of-thousands-bestiary", name: "Serpent Ward" },
  { recordKey: "the-slithering-bestiary:IUAbDA2cbIB4ONlD", pack: "the-slithering-bestiary", name: "Stalker Summoning Rune" },
  { recordKey: "triumph-of-the-tusk-bestiary:AteURENKIt5Zg2sS", pack: "triumph-of-the-tusk-bestiary", name: "Trampling Livestock" },
  { recordKey: "troubles-in-otari-bestiary:aqDFxmLMx6cOnGlx", pack: "troubles-in-otari-bestiary", name: "Tongues of Flame" },
  { recordKey: "wardens-of-wildwood-bestiary:7jeSUb3zjcsBYfEP", pack: "wardens-of-wildwood-bestiary", name: "Poisonous Pollen Trap" },
];

export const DERIVED_TAG_SEED_LOOKUP = buildDerivedTagSeedLookup(DERIVED_TAG_SEED_RECORD_RESOLUTIONS);
