import { CANONICAL_VOCABULARY } from "./vocabulary.js";

export type CanonicalFacet = {
  readonly kind: (typeof CANONICAL_VOCABULARY.FACET.KIND)[keyof typeof CANONICAL_VOCABULARY.FACET.KIND];
  readonly value: (typeof CANONICAL_VOCABULARY.FACET.VALUE)[keyof typeof CANONICAL_VOCABULARY.FACET.VALUE];
};

export const CANONICAL_FACETS = {
  BEHAVIOR_OVERRIDE: {
    BEHAVIOR_OVERRIDE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.BEHAVIOR_OVERRIDE,
      value: CANONICAL_VOCABULARY.FACET.VALUE.BEHAVIOR_OVERRIDE,
    },
  },
  CAPABILITY: {
    CAPABILITY: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CAPABILITY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.CAPABILITY,
    },
    CASTING_PROFILE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CAPABILITY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.CASTING_PROFILE,
    },
    DEFENSIVE_CAPABILITY: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CAPABILITY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.DEFENSIVE_CAPABILITY,
    },
    SENSORY_CAPABILITY: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CAPABILITY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.SENSORY_CAPABILITY,
    },
    TARGETING_CAPABILITY: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CAPABILITY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.TARGETING_CAPABILITY,
    },
  },
  CHALLENGE_STRUCTURE: {
    CHALLENGE_STRUCTURE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CHALLENGE_STRUCTURE,
      value: CANONICAL_VOCABULARY.FACET.VALUE.CHALLENGE_STRUCTURE,
    },
  },
  CREATURE_FAMILY: {
    BOUND_OBJECT_FAMILY: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CREATURE_FAMILY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.BOUND_OBJECT_FAMILY,
    },
    CREATURE_FAMILY: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.CREATURE_FAMILY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.CREATURE_FAMILY,
    },
  },
  DELIVERY: {
    DELIVERY_PROFILE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.DELIVERY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.DELIVERY_PROFILE,
    },
    PAYLOAD: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.DELIVERY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.PAYLOAD,
    },
    VECTOR: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.DELIVERY,
      value: CANONICAL_VOCABULARY.FACET.VALUE.VECTOR,
    },
  },
  EFFECT: {
    EFFECT_PROFILE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.EFFECT,
      value: CANONICAL_VOCABULARY.FACET.VALUE.EFFECT_PROFILE,
    },
  },
  FUNCTION: {
    HAZARD_FUNCTION: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.FUNCTION,
      value: CANONICAL_VOCABULARY.FACET.VALUE.HAZARD_FUNCTION,
    },
  },
  MECHANISM: {
    MECHANISM: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.MECHANISM,
      value: CANONICAL_VOCABULARY.FACET.VALUE.MECHANISM,
    },
  },
  PATHOGENESIS: {
    PATHOGENESIS: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.PATHOGENESIS,
      value: CANONICAL_VOCABULARY.FACET.VALUE.PATHOGENESIS,
    },
  },
  PROGRESSION: {
    PROGRESSION_PROFILE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.PROGRESSION,
      value: CANONICAL_VOCABULARY.FACET.VALUE.PROGRESSION_PROFILE,
    },
  },
  RESPONSE_DEMAND: {
    RESPONSE_DEMAND: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.RESPONSE_DEMAND,
      value: CANONICAL_VOCABULARY.FACET.VALUE.RESPONSE_DEMAND,
    },
  },
  ROLE: {
    ROLE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.ROLE,
      value: CANONICAL_VOCABULARY.FACET.VALUE.ROLE,
    },
    TACTICAL: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.ROLE,
      value: CANONICAL_VOCABULARY.FACET.VALUE.TACTICAL,
    },
  },
  SETTING: {
    HABITAT: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.SETTING,
      value: CANONICAL_VOCABULARY.FACET.VALUE.HABITAT,
    },
    PLANAR: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.SETTING,
      value: CANONICAL_VOCABULARY.FACET.VALUE.PLANAR,
    },
    REGIONAL: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.SETTING,
      value: CANONICAL_VOCABULARY.FACET.VALUE.REGIONAL,
    },
    SITE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.SETTING,
      value: CANONICAL_VOCABULARY.FACET.VALUE.SITE,
    },
  },
  THEME: {
    CORRUPTION: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.THEME,
      value: CANONICAL_VOCABULARY.FACET.VALUE.CORRUPTION,
    },
    HAUNT_MANIFESTATION: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.THEME,
      value: CANONICAL_VOCABULARY.FACET.VALUE.HAUNT_MANIFESTATION,
    },
    PESTILENCE: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.THEME,
      value: CANONICAL_VOCABULARY.FACET.VALUE.PESTILENCE,
    },
    THEME: {
      kind: CANONICAL_VOCABULARY.FACET.KIND.THEME,
      value: CANONICAL_VOCABULARY.FACET.VALUE.THEME,
    },
  },
} as const;
