// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeCapabilityView } from "./RuntimeCapabilityView";
import type { RuntimeCountView } from "./RuntimeCountView";
import type { RuntimeEffectNoteView } from "./RuntimeEffectNoteView";

export type ActionBudgetView = { actions: RuntimeCountView, reactions: RuntimeCountView, can_act: RuntimeCapabilityView, can_react: RuntimeCapabilityView, notes: Array<RuntimeEffectNoteView>, };
