// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityRollSurfaceView } from "./ActivityRollSurfaceView";
import type { StatModifierView } from "./StatModifierView";

export type ActivityRollView = { roll_id: string, label: string, base_value: number, adjusted_value: number, surface: ActivityRollSurfaceView, modifiers: Array<StatModifierView>, suppressed_modifiers: Array<StatModifierView>, };
