// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorActivityView } from "./ActorActivityView";
import type { ActorModifierView } from "./ActorModifierView";
import type { ActorMovementView } from "./ActorMovementView";
import type { ActorRuntimeView } from "./ActorRuntimeView";
import type { ActorSavesView } from "./ActorSavesView";
import type { ActorSenseView } from "./ActorSenseView";
import type { ActorSkillView } from "./ActorSkillView";
import type { FactView } from "./FactView";
import type { IwrEntryView } from "./IwrEntryView";
import type { NumberFactView } from "./NumberFactView";

export type ActorPresentationView = { level: NumberFactView, armor_class: NumberFactView, maximum_hp: NumberFactView, perception: NumberFactView, saves: ActorSavesView, abilities: FactView<Array<ActorModifierView>>, skills: FactView<Array<ActorSkillView>>, movement: FactView<Array<ActorMovementView>>, land_speed: NumberFactView, immunities: FactView<Array<IwrEntryView>>, weaknesses: FactView<Array<IwrEntryView>>, resistances: FactView<Array<IwrEntryView>>, senses: FactView<Array<ActorSenseView>>, perception_details: FactView<string>, languages: FactView<Array<string>>, language_details: FactView<string>, activities: FactView<Array<ActorActivityView>>, runtime: ActorRuntimeView | null, };
