// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";

export type ActorSenseView = { sense: FactView<string>, acuity: FactView<string>, range_feet: NumberFactView, };
