// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionalSkillView } from "./ConditionalSkillView";
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";

export type ActorSkillView = { key: string, label: string, modifier: NumberFactView, note: FactView<string>, conditional: FactView<Array<ConditionalSkillView>>, };
