// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumberFactView } from "./NumberFactView";

export type ActorSavesView = { fortitude: NumberFactView, reflex: NumberFactView, will: NumberFactView, };
