// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionBudgetView } from "./ActionBudgetView";
import type { UnappliedEffectView } from "./UnappliedEffectView";

export type ActorRuntimeView = { action_budget: ActionBudgetView | null, unapplied_effects: Array<UnappliedEffectView>, };
