// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorActivityKindView } from "./ActorActivityKindView";
import type { DamageComponentView } from "./DamageComponentView";
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";
import type { RecordBadgeView } from "./RecordBadgeView";
import type { RecordNavigationView } from "./RecordNavigationView";
import type { RuntimeEffectNoteView } from "./RuntimeEffectNoteView";

export type ActorActivityView = { navigation: RecordNavigationView, title: string, family: string, kind: ActorActivityKindView, usage: string | null, traits: Array<RecordBadgeView>, attack: NumberFactView, lore_modifier: NumberFactView, damage: FactView<Array<DamageComponentView>>, difficulty_class: NumberFactView, casting_tradition: FactView<string>, preparation: FactView<string>, casting_entry: RecordNavigationView | null, association: FactView<string>, notes: Array<RuntimeEffectNoteView>, };
