// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddEncounterRecordParticipantRequest = { encounter_ref: string, record_ref: string, quantity: number, initiative?: bigint, };
