// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddEncounterParticipantConditionRequest = { participant_key: string, condition_ref?: string, name?: string, value?: number, source_participant_key?: string, duration_rounds?: number, note?: string, };
