// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddEncounterManualParticipantRequest = { encounter_ref: string, display_name: string, max_hp?: number, current_hp?: number, initiative?: number, };
