// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddSavedListItemRequest = { list_ref: string, record_ref: string, note?: string, };
