// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppErrorCode } from "./AppErrorCode";
import type { AppRecoverableAction } from "./AppRecoverableAction";

export type AppError = { code: AppErrorCode, message: string, details?: unknown, retryable?: boolean, recoverable_action?: AppRecoverableAction, };
