// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppRecoverableAction = "run_setup_check" | "run_setup" | "reopen_result_window" | "refresh_readiness" | "reload_record" | "rebuild_filter_editor" | "retry" | "none";
