// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppReadinessStatus } from "./AppReadinessStatus";

export type AppReadinessView = { status: AppReadinessStatus, message: string, };
