// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicSearchFilter } from "./BasicSearchFilter";
import type { BasicSearchMode } from "./BasicSearchMode";
import type { RecordListSortView } from "./RecordListSortView";

export type BasicSearchState = { v: number, mode: BasicSearchMode, sort?: RecordListSortView, page_size: number, page: number, filter: BasicSearchFilter, };
