// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterClause } from "./FilterClause";

export type BasicSearchFilter = { clauses: Array<FilterClause>, };
