// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchSavedListItemResultView } from "./BatchSavedListItemResultView";

export type BatchSavedListItemMutationView = { list_key: string, slug: string, requested_count: bigint, added_count: bigint, already_present_count: bigint, failed_count: bigint, items: Array<BatchSavedListItemResultView>, };
