// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchSavedListItemInput } from "./BatchSavedListItemInput";

export type BatchAddSavedListItemsRequest = { list_ref: string, items: Array<BatchSavedListItemInput>, };
