// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { BatchSavedListItemOutcomeView } from "./BatchSavedListItemOutcomeView";

export type BatchSavedListItemResultView = { input: string, outcome: BatchSavedListItemOutcomeView, record_key?: string, record_name?: string, error?: AppError, };
