// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableFactView } from "./ConsumableFactView";

export type ConsumableDamageView = { formula: ConsumableFactView<string>, category: ConsumableFactView<string>, damage_type: ConsumableFactView<string>, };
