// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableDefinitionView } from "./ConsumableDefinitionView";
import type { ConsumableOccurrenceIdentityStabilityView } from "./ConsumableOccurrenceIdentityStabilityView";
import type { ConsumableOccurrenceTargetView } from "./ConsumableOccurrenceTargetView";
import type { ConsumableSourceStateView } from "./ConsumableSourceStateView";
import type { ConsumableSpellChildLinkView } from "./ConsumableSpellChildLinkView";
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";

export type ConsumableOccurrenceView = { occurrence_id: string, authored_order: number, name: string, identity_stability: ConsumableOccurrenceIdentityStabilityView, target: ConsumableOccurrenceTargetView, definition?: ConsumableDefinitionView, source_state: ConsumableSourceStateView, spell_child?: ConsumableSpellChildLinkView, content?: Array<CreatureSurfaceContentView>, };
