// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumableSpellChildLinkView = { parent_record_key: string, occurrence_id?: string, child_id: string, target_record_key?: string, };
