// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableDamageView } from "./ConsumableDamageView";
import type { ConsumableFactView } from "./ConsumableFactView";
import type { ConsumableMaterialView } from "./ConsumableMaterialView";
import type { ConsumablePriceView } from "./ConsumablePriceView";
import type { ConsumablePublicationView } from "./ConsumablePublicationView";
import type { ConsumableSourceStateView } from "./ConsumableSourceStateView";
import type { ConsumableSpellChildLinkView } from "./ConsumableSpellChildLinkView";
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";

export type ConsumableSurfaceView = { slug: ConsumableFactView<string>, level: ConsumableFactView<number>, category: ConsumableFactView<string>, rarity: ConsumableFactView<string>, traits: ConsumableFactView<Array<string>>, other_tags: ConsumableFactView<Array<string>>, usage: ConsumableFactView<string>, base_item: ConsumableFactView<string>, bulk: ConsumableFactView<string>, size: ConsumableFactView<string>, stack_group: ConsumableFactView<string>, material: ConsumableFactView<ConsumableMaterialView>, price: ConsumableFactView<ConsumablePriceView>, maximum_uses: ConsumableFactView<number>, auto_destroy: ConsumableFactView<boolean>, maximum_hp: ConsumableFactView<number>, hardness: ConsumableFactView<number>, publication: ConsumableFactView<ConsumablePublicationView>, source_state: ConsumableSourceStateView, damage: ConsumableFactView<ConsumableDamageView>, spell_child?: ConsumableSpellChildLinkView, content?: Array<CreatureSurfaceContentView>, };
