// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumableOccurrenceIdentityStabilityView = "stable_source_identity" | "unstable_owner_ordinal";
