// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableEquippedView } from "./ConsumableEquippedView";
import type { ConsumableFactView } from "./ConsumableFactView";

export type ConsumableSourceStateView = { quantity: ConsumableFactView<number>, current_uses: ConsumableFactView<number>, current_hp: ConsumableFactView<number>, container_id: ConsumableFactView<string>, equipped: ConsumableFactView<ConsumableEquippedView>, };
