// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableFactView } from "./ConsumableFactView";

export type ConsumableEquippedView = { carry_type: ConsumableFactView<string>, hands_held: ConsumableFactView<number>, in_slot: ConsumableFactView<boolean>, };
