// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableTargetReasonView } from "./ConsumableTargetReasonView";

export type ConsumableOccurrenceTargetView = { "state": "resolved", record_key: string, mismatch_fields: Array<string>, } | { "state": "parent_owned", reason: ConsumableTargetReasonView, };
