// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumableFactView<T> = { "state": "missing" } | { "state": "null" } | { "state": "known", "value": T } | { "state": "unsupported" };
