// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableFactView } from "./ConsumableFactView";

export type ConsumableMaterialView = { grade: ConsumableFactView<string>, material_type: ConsumableFactView<string>, effects: ConsumableFactView<Array<string>>, };
