// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableFactView } from "./ConsumableFactView";
import type { ConsumablePriceDenominationView } from "./ConsumablePriceDenominationView";

export type ConsumablePriceView = { denominations: ConsumableFactView<Array<ConsumablePriceDenominationView>>, per: ConsumableFactView<number>, };
