// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsumableFactView } from "./ConsumableFactView";

export type ConsumablePublicationView = { title: ConsumableFactView<string>, license: ConsumableFactView<string>, remaster: ConsumableFactView<boolean>, };
