// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumableTargetReasonView = "no_locator" | "malformed_or_duplicate_locator" | "target_missing" | "wrong_document_or_family";
