// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentControlKindView } from "./ContentControlKindView";

export type ContentControlView = { ordinal: number, control: ContentControlKindView, };
