// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentControlKindView = { "kind": "check", statistic: string | null, options: { [key in string]?: string }, } | { "kind": "damage", formula: string, options: { [key in string]?: string }, } | { "kind": "command", command: string, arguments: string, options: { [key in string]?: string }, } | { "kind": "template", shape: string | null, options: { [key in string]?: string }, };
