// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceRelationshipKindView = "granted_by" | "item_grant" | "linked_weapon" | "prepared_spell";
