// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";

export type CreatureSurfaceAbilitiesView = { strength?: bigint, dexterity?: bigint, constitution?: bigint, intelligence?: bigint, wisdom?: bigint, charisma?: bigint, provenance: CreatureSurfaceFactProvenanceView, };
