// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactOwnerView } from "./CreatureSurfaceFactOwnerView";
import type { CreatureSurfaceSourceFieldView } from "./CreatureSurfaceSourceFieldView";

export type CreatureSurfaceFactProvenanceView = { owner: CreatureSurfaceFactOwnerView, field: CreatureSurfaceSourceFieldView, };
