// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceSourceFieldView = "size" | "adjustment" | "initiative" | "defenses" | "perception" | "languages" | "skills" | "legacy_abilities" | "movement" | "resources" | "embedded_entities";
