// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentOwnerView } from "./CreatureSurfaceContentOwnerView";
import type { CreatureSurfaceContentProvenanceView } from "./CreatureSurfaceContentProvenanceView";
import type { CreatureSurfaceContentRoleView } from "./CreatureSurfaceContentRoleView";

export type CreatureSurfaceContentView = { content_key: string, owner: CreatureSurfaceContentOwnerView, role: CreatureSurfaceContentRoleView, authored_order: number, label?: string, text: string, content_hash: string, visibility: string, provenance: CreatureSurfaceContentProvenanceView, };
