// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentInlineView } from "./CreatureSurfaceContentInlineView";
import type { CreatureSurfaceContentListItemView } from "./CreatureSurfaceContentListItemView";
import type { CreatureSurfaceContentTableRowView } from "./CreatureSurfaceContentTableRowView";

export type CreatureSurfaceContentBlockView = { "block_type": "heading", level: number, text: string, } | { "block_type": "paragraph", spans: Array<CreatureSurfaceContentInlineView>, } | { "block_type": "list", ordered: boolean, items: Array<CreatureSurfaceContentListItemView>, } | { "block_type": "table", caption?: string, rows: Array<CreatureSurfaceContentTableRowView>, } | { "block_type": "divider" };
