// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";
import type { CreatureSurfaceSaveView } from "./CreatureSurfaceSaveView";

export type CreatureSurfaceSavesView = { fortitude?: CreatureSurfaceSaveView, reflex?: CreatureSurfaceSaveView, will?: CreatureSurfaceSaveView, all_saves_note?: string, provenance: CreatureSurfaceFactProvenanceView, };
