// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceSpellSlotView } from "./CreatureSurfaceSpellSlotView";
import type { CreatureSurfaceSpellView } from "./CreatureSurfaceSpellView";

export type CreatureSurfaceSpellcastingView = { occurrence_id: string, authored_order: number, label: string, preparation?: string, tradition?: string, attack_modifier?: number, difficulty_class?: number, slots?: Array<CreatureSurfaceSpellSlotView>, spells?: Array<CreatureSurfaceSpellView>, };
