// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceMovementView = { component_id: string, authored_order: number, mode: string, label?: string, speed_feet?: number, details?: string, };
