// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceAdjustmentValueView } from "./CreatureSurfaceAdjustmentValueView";
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";

export type CreatureSurfaceAdjustmentView = { value: CreatureSurfaceAdjustmentValueView, provenance: CreatureSurfaceFactProvenanceView, };
