// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceActionCostView = { "cost_type": "passive" } | { "cost_type": "reaction" } | { "cost_type": "free_action" } | { "cost_type": "actions", count: number, } | { "cost_type": "time", value: string, };
