// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";
import type { CreatureSurfaceUnavailableFieldView } from "./CreatureSurfaceUnavailableFieldView";
import type { CreatureSurfaceUnavailableStateView } from "./CreatureSurfaceUnavailableStateView";
import type { CreatureSurfaceUnmodeledSkillView } from "./CreatureSurfaceUnmodeledSkillView";

export type CreatureSurfaceUnavailableCauseView = { state: CreatureSurfaceUnavailableStateView, field: CreatureSurfaceUnavailableFieldView, component_id?: string, provenance: CreatureSurfaceFactProvenanceView, unmodeled_skill?: CreatureSurfaceUnmodeledSkillView, message: string, };
