// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceActionCostView } from "./CreatureSurfaceActionCostView";
import type { CreatureSurfaceActivityTypeView } from "./CreatureSurfaceActivityTypeView";
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { CreatureSurfaceDamageView } from "./CreatureSurfaceDamageView";
import type { CreatureSurfaceFrequencyView } from "./CreatureSurfaceFrequencyView";
import type { CreatureSurfaceRollView } from "./CreatureSurfaceRollView";
import type { CreatureSurfaceSelfEffectView } from "./CreatureSurfaceSelfEffectView";
import type { CreatureSurfaceUsesView } from "./CreatureSurfaceUsesView";

export type CreatureSurfaceActivityView = { occurrence_id: string, authored_order: number, activity_type: CreatureSurfaceActivityTypeView, label: string, traits?: Array<string>, action_cost?: CreatureSurfaceActionCostView, attack_effects?: Array<string>, category?: string, frequency?: CreatureSurfaceFrequencyView, requirements?: string, cost?: string, uses?: CreatureSurfaceUsesView, self_effect?: CreatureSurfaceSelfEffectView, rolls?: Array<CreatureSurfaceRollView>, damage?: Array<CreatureSurfaceDamageView>, content?: Array<CreatureSurfaceContentView>, };
