// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceRelationshipTargetView = { "target_type": "occurrence", occurrence_id: string, } | { "target_type": "unresolved_source", source_id: string, };
