// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceContentRoleView = "primary_description" | "summary" | "supplemental_rules" | "embedded_capability" | "journal_page" | "table_result" | "generated_narrative" | "provenance";
