// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";
import type { CreatureSurfaceIwrView } from "./CreatureSurfaceIwrView";

export type CreatureSurfaceDefensesView = { armor_class?: bigint, armor_class_details?: string, hardness?: bigint, immunities: Array<CreatureSurfaceIwrView>, resistances: Array<CreatureSurfaceIwrView>, weaknesses: Array<CreatureSurfaceIwrView>, provenance: CreatureSurfaceFactProvenanceView, };
