// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceOccurrenceIdentityStabilityView } from "./CreatureSurfaceOccurrenceIdentityStabilityView";
import type { CreatureSurfaceSourceLocatorView } from "./CreatureSurfaceSourceLocatorView";

export type CreatureSurfaceOccurrenceProvenanceView = { identity_stability: CreatureSurfaceOccurrenceIdentityStabilityView, nested_source_id?: string, stable_source_locator?: string, source_locators?: Array<CreatureSurfaceSourceLocatorView>, };
