// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceSkillView = { component_id: string, authored_order: number, kind: string, label: string, modifier?: number, note?: string, };
