// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceIntegerPresenceView } from "./CreatureSurfaceIntegerPresenceView";
import type { CreatureSurfaceUnmodeledSkillReasonView } from "./CreatureSurfaceUnmodeledSkillReasonView";

export type CreatureSurfaceUnmodeledSkillView = { authored_key: string, base: CreatureSurfaceIntegerPresenceView, reason: CreatureSurfaceUnmodeledSkillReasonView, };
