// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceSpellView = { occurrence_id: string, authored_order: number, label: string, target_record_key?: string, rank?: bigint, traits?: Array<string>, };
