// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceOccurrenceProvenanceView } from "./CreatureSurfaceOccurrenceProvenanceView";

export type CreatureSurfaceLoreView = { occurrence_id: string, authored_order: number, provenance: CreatureSurfaceOccurrenceProvenanceView, label: string, modifier?: number, };
