// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceAbilitiesView } from "./CreatureSurfaceAbilitiesView";
import type { CreatureSurfaceActivityView } from "./CreatureSurfaceActivityView";
import type { CreatureSurfaceAwarenessView } from "./CreatureSurfaceAwarenessView";
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { CreatureSurfaceDefensesView } from "./CreatureSurfaceDefensesView";
import type { CreatureSurfaceMovementView } from "./CreatureSurfaceMovementView";
import type { CreatureSurfaceProvenanceView } from "./CreatureSurfaceProvenanceView";
import type { CreatureSurfaceRelationshipView } from "./CreatureSurfaceRelationshipView";
import type { CreatureSurfaceResourceView } from "./CreatureSurfaceResourceView";
import type { CreatureSurfaceSavesView } from "./CreatureSurfaceSavesView";
import type { CreatureSurfaceSkillView } from "./CreatureSurfaceSkillView";
import type { CreatureSurfaceSpellcastingView } from "./CreatureSurfaceSpellcastingView";
import type { CreatureSurfaceUnavailableDomainsView } from "./CreatureSurfaceUnavailableDomainsView";
import type { CreatureSurfaceVitalsView } from "./CreatureSurfaceVitalsView";

export type CreatureSurfaceView = { vitals?: CreatureSurfaceVitalsView, defenses?: CreatureSurfaceDefensesView, saves?: CreatureSurfaceSavesView, awareness?: CreatureSurfaceAwarenessView, abilities?: CreatureSurfaceAbilitiesView, skills?: Array<CreatureSurfaceSkillView>, movement?: Array<CreatureSurfaceMovementView>, resources?: Array<CreatureSurfaceResourceView>, spellcasting?: Array<CreatureSurfaceSpellcastingView>, activities?: Array<CreatureSurfaceActivityView>, content?: Array<CreatureSurfaceContentView>, relationships?: Array<CreatureSurfaceRelationshipView>, unavailable_domains?: CreatureSurfaceUnavailableDomainsView, provenance?: CreatureSurfaceProvenanceView, };
