// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceUsesView } from "./CreatureSurfaceUsesView";

export type CreatureSurfaceEquipmentView = { occurrence_id: string, authored_order: number, label: string, source_item_id?: string, traits?: Array<string>, level?: number, usage?: string, quantity?: number, uses?: CreatureSurfaceUsesView, };
