// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceContentOwnerView = { "owner_type": "record", record_key: string, } | { "owner_type": "entity", entity_id: string, } | { "owner_type": "occurrence", occurrence_id: string, };
