// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceIntegerPresenceView } from "./CreatureSurfaceIntegerPresenceView";
import type { CreatureSurfaceSkillSourceEntryView } from "./CreatureSurfaceSkillSourceEntryView";
import type { CreatureSurfaceUnmodeledSkillReasonView } from "./CreatureSurfaceUnmodeledSkillReasonView";

export type CreatureSurfaceUnmodeledSkillView = { component_id: string, authored_order: number, source_entries?: Array<CreatureSurfaceSkillSourceEntryView>, source_item_id?: string, authored_key: string, base: CreatureSurfaceIntegerPresenceView, reason: CreatureSurfaceUnmodeledSkillReasonView, };
