// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";

export type CreatureSurfaceVitalsView = { hit_points?: number, details?: string, provenance: CreatureSurfaceFactProvenanceView, };
