// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";
import type { CreatureSurfaceIwrView } from "./CreatureSurfaceIwrView";
import type { CreatureSurfaceShieldView } from "./CreatureSurfaceShieldView";

export type CreatureSurfaceDefensesView = { armor_class?: number, armor_class_details?: string, hardness?: number, shield?: CreatureSurfaceShieldView, immunities?: Array<CreatureSurfaceIwrView>, resistances?: Array<CreatureSurfaceIwrView>, weaknesses?: Array<CreatureSurfaceIwrView>, provenance: CreatureSurfaceFactProvenanceView, };
