// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceUsesView } from "./CreatureSurfaceUsesView";

export type CreatureSurfaceSpellOccurrenceContextView = { group?: string, location?: string, slot?: string, uses?: CreatureSurfaceUsesView, contextual_label?: string, };
