// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { CreatureSurfaceOccurrenceProvenanceView } from "./CreatureSurfaceOccurrenceProvenanceView";
import type { CreatureSurfaceSpellOccurrenceContextView } from "./CreatureSurfaceSpellOccurrenceContextView";

export type CreatureSurfaceSpellView = { occurrence_id: string, authored_order: number, provenance: CreatureSurfaceOccurrenceProvenanceView, label: string, target_record_key?: string, rank?: number, context?: CreatureSurfaceSpellOccurrenceContextView, traits?: Array<string>, content?: Array<CreatureSurfaceContentView>, };
