// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceAbilitiesView } from "./CreatureSurfaceAbilitiesView";
import type { CreatureSurfaceActivityView } from "./CreatureSurfaceActivityView";
import type { CreatureSurfaceAdjustmentView } from "./CreatureSurfaceAdjustmentView";
import type { CreatureSurfaceAwarenessView } from "./CreatureSurfaceAwarenessView";
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { CreatureSurfaceDefensesView } from "./CreatureSurfaceDefensesView";
import type { CreatureSurfaceEquipmentView } from "./CreatureSurfaceEquipmentView";
import type { CreatureSurfaceInitiativeView } from "./CreatureSurfaceInitiativeView";
import type { CreatureSurfaceLoreView } from "./CreatureSurfaceLoreView";
import type { CreatureSurfaceMovementView } from "./CreatureSurfaceMovementView";
import type { CreatureSurfaceProvenanceView } from "./CreatureSurfaceProvenanceView";
import type { CreatureSurfaceRelationshipView } from "./CreatureSurfaceRelationshipView";
import type { CreatureSurfaceResourceView } from "./CreatureSurfaceResourceView";
import type { CreatureSurfaceRitualsView } from "./CreatureSurfaceRitualsView";
import type { CreatureSurfaceSavesView } from "./CreatureSurfaceSavesView";
import type { CreatureSurfaceSizeView } from "./CreatureSurfaceSizeView";
import type { CreatureSurfaceSkillView } from "./CreatureSurfaceSkillView";
import type { CreatureSurfaceSpellView } from "./CreatureSurfaceSpellView";
import type { CreatureSurfaceSpellcastingView } from "./CreatureSurfaceSpellcastingView";
import type { CreatureSurfaceUnavailableDomainsView } from "./CreatureSurfaceUnavailableDomainsView";
import type { CreatureSurfaceVitalsView } from "./CreatureSurfaceVitalsView";

export type CreatureSurfaceView = { teaser?: string, size?: CreatureSurfaceSizeView, adjustment?: CreatureSurfaceAdjustmentView, initiative?: CreatureSurfaceInitiativeView, vitals?: CreatureSurfaceVitalsView, defenses?: CreatureSurfaceDefensesView, saves?: CreatureSurfaceSavesView, awareness?: CreatureSurfaceAwarenessView, abilities?: CreatureSurfaceAbilitiesView, skills?: Array<CreatureSurfaceSkillView>, movement?: Array<CreatureSurfaceMovementView>, resources?: Array<CreatureSurfaceResourceView>, rituals?: CreatureSurfaceRitualsView, equipment?: Array<CreatureSurfaceEquipmentView>, lore?: Array<CreatureSurfaceLoreView>, spellcasting?: Array<CreatureSurfaceSpellcastingView>, standalone_spells?: Array<CreatureSurfaceSpellView>, activities?: Array<CreatureSurfaceActivityView>, content?: Array<CreatureSurfaceContentView>, relationships?: Array<CreatureSurfaceRelationshipView>, unavailable_domains?: CreatureSurfaceUnavailableDomainsView, provenance?: CreatureSurfaceProvenanceView, };
