// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";
import type { CreatureSurfaceSizeValueView } from "./CreatureSurfaceSizeValueView";

export type CreatureSurfaceSizeView = { value: CreatureSurfaceSizeValueView, provenance: CreatureSurfaceFactProvenanceView, };
