// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceOccurrenceIdentityStabilityView = "stable_nested_source_id" | "unstable_owner_family_ordinal";
