// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceLoreView = { occurrence_id: string, authored_order: number, label: string, source_item_id?: string, modifier?: number, };
