// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceActionCostView } from "./CreatureSurfaceActionCostView";
import type { CreatureSurfaceActivityTypeView } from "./CreatureSurfaceActivityTypeView";
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { CreatureSurfaceDamageView } from "./CreatureSurfaceDamageView";
import type { CreatureSurfaceRollView } from "./CreatureSurfaceRollView";

export type CreatureSurfaceActivityView = { occurrence_id: string, authored_order: number, activity_type: CreatureSurfaceActivityTypeView, label: string, traits?: Array<string>, action_cost?: CreatureSurfaceActionCostView, rolls?: Array<CreatureSurfaceRollView>, damage?: Array<CreatureSurfaceDamageView>, content?: Array<CreatureSurfaceContentView>, };
