// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceContentProvenanceView = { source_record_key: string, relative_source_path: string, field_family: string, nested_source_id?: string, };
