// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceRelationshipKindView } from "./CreatureSurfaceRelationshipKindView";
import type { CreatureSurfaceRelationshipTargetView } from "./CreatureSurfaceRelationshipTargetView";

export type CreatureSurfaceRelationshipView = { source_occurrence_id: string, kind: CreatureSurfaceRelationshipKindView, target: CreatureSurfaceRelationshipTargetView, contextual_label?: string, provenance_only: boolean, };
