// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceContentInlineView = { "span_type": "text", text: string, } | { "span_type": "strong", spans: Array<CreatureSurfaceContentInlineView>, } | { "span_type": "emphasis", spans: Array<CreatureSurfaceContentInlineView>, } | { "span_type": "code", text: string, } | { "span_type": "reference", label: string, record_key?: string, embedded: boolean, } | { "span_type": "line_break" };
