// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceSkillSourceEntryView } from "./CreatureSurfaceSkillSourceEntryView";
import type { CreatureSurfaceSkillVariantView } from "./CreatureSurfaceSkillVariantView";

export type CreatureSurfaceSkillView = { component_id: string, authored_order: number, kind: string, label: string, source_entries?: Array<CreatureSurfaceSkillSourceEntryView>, modifier?: number, note?: string, variants?: Array<CreatureSurfaceSkillVariantView>, };
