// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceSkillPredicateView } from "./CreatureSurfaceSkillPredicateView";

export type CreatureSurfaceSkillVariantView = { component_id: string, authored_order: number, modifier?: number, label?: string, predicates?: Array<CreatureSurfaceSkillPredicateView>, };
