// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";

export type CreatureSurfaceAbilitiesView = { strength?: number, dexterity?: number, constitution?: number, intelligence?: number, wisdom?: number, charisma?: number, provenance: CreatureSurfaceFactProvenanceView, };
