// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceIwrView = { component_id: string, authored_order: number, kind: string, amount?: bigint, exceptions: Array<string>, double_vs: Array<string>, };
