// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceFactProvenanceView } from "./CreatureSurfaceFactProvenanceView";
import type { CreatureSurfaceSenseView } from "./CreatureSurfaceSenseView";

export type CreatureSurfaceAwarenessView = { perception?: bigint, details?: string, has_vision?: boolean, senses: Array<CreatureSurfaceSenseView>, languages: Array<string>, language_details?: string, provenance: CreatureSurfaceFactProvenanceView, };
