// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceShieldView = { armor_class_bonus?: number, broken_threshold?: number, hardness?: number, maximum_hit_points?: number, };
