// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentBlockView } from "./CreatureSurfaceContentBlockView";

export type CreatureSurfaceContentListItemView = { blocks: Array<CreatureSurfaceContentBlockView>, };
