// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureSurfaceSkillPredicateView = { "predicate_type": "term", term: string, } | { "predicate_type": "not", term: string, } | { "predicate_type": "any", terms: Array<string>, } | { "predicate_type": "at_least", term: string, minimum: number, };
