// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";

export type DamageComponentView = { id: string, formula: FactView<string>, damage_type: FactView<string>, kinds: FactView<Array<string>>, category: FactView<string>, materials: FactView<Array<string>>, apply_modifier: FactView<boolean>, };
