// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageEffectKindView } from "./DamageEffectKindView";
import type { StatModifierView } from "./StatModifierView";

export type DamageExpressionView = { damage_id: string, label?: string, formula: string, adjusted_formula?: string, damage_type?: string, effect_kind: DamageEffectKindView, modifiers: Array<StatModifierView>, };
