// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatModifierView } from "./StatModifierView";

export type DamageExpressionView = { damage_id: string, label?: string, formula: string, damage_type?: string, modifiers: Array<StatModifierView>, };
