// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterDiscoveryContext } from "./FilterDiscoveryContext";

export type DiscoverFilterEditorRequest = { context: FilterDiscoveryContext, };
