// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterDiscoveryContext } from "./FilterDiscoveryContext";

export type DiscoverFilterValuesRequest = { context: FilterDiscoveryContext, field_id: string, clause_id: string | null, text: string | null, offset: number, limit: number, };
