// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantView } from "./EncounterParticipantView";
import type { RecordDetailView } from "./RecordDetailView";

export type EncounterParticipantDetailView = { participant: EncounterParticipantView, record_detail?: RecordDetailView, };
