// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeHazardInitiativeStatisticView } from "./EncounterRuntimeHazardInitiativeStatisticView";
import type { RuntimeNumberView } from "./RuntimeNumberView";

export type EncounterRuntimeHazardInitiativeSuggestionView = { statistic: EncounterRuntimeHazardInitiativeStatisticView, modifier: RuntimeNumberView, };
