// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterSpellCastUnavailableReasonView = "missing_current" | "missing_maximum" | "unsafe_integer" | "missing_identity" | "ambiguous_ownership" | "unsupported_preparation" | "unresolved_participant" | "state_unavailable";
