// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterConditionCategoryView = "action_economy" | "attitude" | "death_and_dying" | "detection" | "object_state" | "runtime_state" | "stat_modifier";
