// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeSpellSlotView } from "./EncounterRuntimeSpellSlotView";
import type { RuntimeRollView } from "./RuntimeRollView";

export type EncounterRuntimeSpellcastingView = { entry_id: string, label: string, attack?: RuntimeRollView, dc?: RuntimeRollView, slots?: Array<EncounterRuntimeSpellSlotView>, };
