// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantPreservedDomainView } from "./EncounterParticipantPreservedDomainView";
import type { EncounterParticipantResetDomainView } from "./EncounterParticipantResetDomainView";
import type { EncounterParticipantView } from "./EncounterParticipantView";

export type EncounterParticipantResetResultView = { participant_key: string, reset_domains: Array<EncounterParticipantResetDomainView>, preserved_domains: Array<EncounterParticipantPreservedDomainView>, cleared_current_turn: boolean, participant: EncounterParticipantView, };
