// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeSpellSlotView } from "./EncounterRuntimeSpellSlotView";
import type { EncounterRuntimeSpellView } from "./EncounterRuntimeSpellView";
import type { RuntimeRollView } from "./RuntimeRollView";

export type EncounterRuntimeSpellcastingView = { entry_id: string, authored_order: number, label: string, preparation?: string, tradition?: string, attack?: RuntimeRollView, dc?: RuntimeRollView, slots?: Array<EncounterRuntimeSpellSlotView>, spells?: Array<EncounterRuntimeSpellView>, };
