// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterConditionApplicabilityView } from "./EncounterConditionApplicabilityView";
import type { EncounterConditionAutomationLevelView } from "./EncounterConditionAutomationLevelView";
import type { EncounterConditionCategoryView } from "./EncounterConditionCategoryView";

export type EncounterConditionDefinitionView = { condition_ref: string, name: string, automation_level: EncounterConditionAutomationLevelView, applies_to: Array<EncounterConditionApplicabilityView>, categories: Array<EncounterConditionCategoryView>, has_value: boolean, default_value?: bigint, };
