// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantView } from "./EncounterParticipantView";
import type { EncounterSummaryView } from "./EncounterSummaryView";

export type EncounterDetailView = { encounter: EncounterSummaryView, note?: string, current_turn_participant_key?: string, participants: Array<EncounterParticipantView>, };
