// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeAbilitiesView } from "./EncounterRuntimeAbilitiesView";
import type { EncounterRuntimeActionBudgetView } from "./EncounterRuntimeActionBudgetView";
import type { EncounterRuntimeActivityView } from "./EncounterRuntimeActivityView";
import type { EncounterRuntimeAwarenessView } from "./EncounterRuntimeAwarenessView";
import type { EncounterRuntimeConditionView } from "./EncounterRuntimeConditionView";
import type { EncounterRuntimeDefensesView } from "./EncounterRuntimeDefensesView";
import type { EncounterRuntimeMovementView } from "./EncounterRuntimeMovementView";
import type { EncounterRuntimeResourceView } from "./EncounterRuntimeResourceView";
import type { EncounterRuntimeSavesView } from "./EncounterRuntimeSavesView";
import type { EncounterRuntimeSkillView } from "./EncounterRuntimeSkillView";
import type { EncounterRuntimeSpellcastingView } from "./EncounterRuntimeSpellcastingView";
import type { EncounterRuntimeUnappliedFactView } from "./EncounterRuntimeUnappliedFactView";
import type { EncounterRuntimeVitalsView } from "./EncounterRuntimeVitalsView";
import type { RuntimeNumberView } from "./RuntimeNumberView";

export type EncounterRuntimeView = { adjusted_level?: RuntimeNumberView, vitals?: EncounterRuntimeVitalsView, defenses?: EncounterRuntimeDefensesView, saves?: EncounterRuntimeSavesView, awareness?: EncounterRuntimeAwarenessView, abilities?: EncounterRuntimeAbilitiesView, skills: Array<EncounterRuntimeSkillView>, movement?: EncounterRuntimeMovementView, resources: Array<EncounterRuntimeResourceView>, spellcasting: Array<EncounterRuntimeSpellcastingView>, activities: Array<EncounterRuntimeActivityView>, action_budget?: EncounterRuntimeActionBudgetView, conditions: Array<EncounterRuntimeConditionView>, unapplied_facts: Array<EncounterRuntimeUnappliedFactView>, };
