// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterSpellCastOperationView } from "./EncounterSpellCastOperationView";
import type { EncounterSpellSpendTargetView } from "./EncounterSpellSpendTargetView";

export type EncounterSpellCastRequest = { spell_occurrence_id: string, spend_target: EncounterSpellSpendTargetView, operation: EncounterSpellCastOperationView, };
