// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeHazardInitiativeSuggestionView } from "./EncounterRuntimeHazardInitiativeSuggestionView";
import type { EncounterRuntimeHazardStateView } from "./EncounterRuntimeHazardStateView";
import type { RuntimeNumberView } from "./RuntimeNumberView";

export type EncounterRuntimeHazardView = { state: EncounterRuntimeHazardStateView, detection_dc?: RuntimeNumberView, broken_threshold?: RuntimeNumberView, initiative_suggestion?: EncounterRuntimeHazardInitiativeSuggestionView, convenience_rule_id: string, convenience_rule_version: number, };
