// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeSkillKindView } from "./EncounterRuntimeSkillKindView";
import type { RuntimeNumberView } from "./RuntimeNumberView";

export type EncounterRuntimeSkillView = { skill_id: string, label: string, kind: EncounterRuntimeSkillKindView, modifier: RuntimeNumberView, };
