// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeActionCostKindView } from "./EncounterRuntimeActionCostKindView";
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type EncounterRuntimeActionCostView = { value: EncounterRuntimeActionCostKindView, provenance: RuntimeFactProvenanceView, };
