// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type EncounterRuntimeConditionView = { condition_id: number, condition_key?: string, name: string, value?: number, source_participant_key?: string, duration_rounds?: number, note?: string, created_at: string, updated_at: string, provenance: RuntimeFactProvenanceView, };
