// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeCountView } from "./RuntimeCountView";

export type EncounterRuntimeSpellSlotView = { rank: bigint, maximum: RuntimeCountView, };
