// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterSpellSpendTargetView = { "target_type": "prepared_slot", entry_id: string, rank: number, slot_id: string, } | { "target_type": "spontaneous_pool", entry_id: string, rank: number, } | { "target_type": "innate_use", entry_id?: string, spell_occurrence_id: string, } | { "target_type": "focus_pool", resource_id: string, } | { "target_type": "at_will" };
