// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantView } from "./EncounterParticipantView";
import type { EncounterSpellCastAvailabilityView } from "./EncounterSpellCastAvailabilityView";
import type { EncounterSpellCastOperationView } from "./EncounterSpellCastOperationView";

export type EncounterSpellCastResultView = { operation: EncounterSpellCastOperationView, participant_key: string, spell_occurrence_id: string, before: EncounterSpellCastAvailabilityView, after: EncounterSpellCastAvailabilityView, participant: EncounterParticipantView, };
