// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterRuntimeAutomationLimitationCodeView = "activity_check_not_automated" | "condition_attack_adjustment_partial" | "condition_damage_adjustment_partial" | "exploration_activity_restriction_not_automated" | "manipulate_action_check_not_automated" | "prone_context_requires_adjudication" | "restricted_action_exceptions_not_automated" | "spell_disruption_check_not_automated" | "stunned_timing_requires_adjudication";
