// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeAutomationLimitationCodeView } from "./EncounterRuntimeAutomationLimitationCodeView";
import type { EncounterRuntimeAutomationLimitationTargetView } from "./EncounterRuntimeAutomationLimitationTargetView";

export type EncounterRuntimeAutomationLimitationView = { code: EncounterRuntimeAutomationLimitationCodeView, target: EncounterRuntimeAutomationLimitationTargetView, message: string, };
