// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterRuntimeSkillKindView = { "kind": "standard", slug: string, } | { "kind": "lore", slug: string, } | { "kind": "legacy", slug: string, };
