// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterStatusView } from "./EncounterStatusView";

export type EncounterSummaryView = { encounter_key: string, slug: string, name: string, description?: string, status: EncounterStatusView, round_number: bigint, participant_count: number, created_at: string, updated_at: string, };
