// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterSpellCastUnavailableReasonView } from "./EncounterSpellCastUnavailableReasonView";

export type EncounterSpellCastStateView = { "state_type": "at_will" } | { "state_type": "tracked", maximum: number, initial_remaining: number, remaining: number, } | { "state_type": "unavailable", reason: EncounterSpellCastUnavailableReasonView, };
