// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterRuntimeActionCostKindView = { "kind": "passive" } | { "kind": "reaction" } | { "kind": "free_action" } | { "kind": "actions", count: number, } | { "kind": "time", value: string, };
