// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeNumberView } from "./RuntimeNumberView";

export type EncounterRuntimeResourceView = { resource_id: string, label: string, maximum: RuntimeNumberView, current?: RuntimeNumberView, };
