// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type EncounterRuntimeFrequencyView = { maximum?: bigint, period?: string, serialized_value?: bigint, provenance: RuntimeFactProvenanceView, };
