// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterSpellCastBlockedReasonView } from "./EncounterSpellCastBlockedReasonView";
import type { EncounterSpellCastStateView } from "./EncounterSpellCastStateView";
import type { EncounterSpellSpendTargetView } from "./EncounterSpellSpendTargetView";

export type EncounterSpellCastAvailabilityView = { spend_target?: EncounterSpellSpendTargetView, available: boolean, state: EncounterSpellCastStateView, blocked_reason?: EncounterSpellCastBlockedReasonView, };
