// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterParticipantResetDomainView = "hit_points" | "defeated" | "conditions" | "initiative_turn_state" | "variant_adjustments" | "action_budget" | "spell_resources";
