// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeCanonicalTargetView } from "./RuntimeCanonicalTargetView";
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type EncounterRuntimeUnappliedFactView = { provenance: RuntimeFactProvenanceView, label: string, reason: string, canonical_target?: RuntimeCanonicalTargetView, };
