// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { EncounterRuntimeActivityView } from "./EncounterRuntimeActivityView";
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type EncounterRuntimeSpellView = { occurrence_id: string, authored_order: number, label: string, target_record_key?: string, rank?: bigint, traits?: Array<string>, content?: Array<CreatureSurfaceContentView>, activity?: EncounterRuntimeActivityView, provenance: RuntimeFactProvenanceView, };
