// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncounterRuntimeAutomationLimitationTargetView = { "target_type": "participant" } | { "target_type": "condition", condition_id: bigint, } | { "target_type": "activity", activity_id: string, } | { "target_type": "spellcasting", entry_id: string, };
