// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantKindView } from "./EncounterParticipantKindView";
import type { EncounterParticipantResetAvailabilityView } from "./EncounterParticipantResetAvailabilityView";
import type { EncounterParticipantSideView } from "./EncounterParticipantSideView";
import type { EncounterParticipantStatusView } from "./EncounterParticipantStatusView";
import type { EncounterParticipantVariantView } from "./EncounterParticipantVariantView";
import type { RecordSurfaceView } from "./RecordSurfaceView";

export type EncounterParticipantView = { participant_key: string, record_key?: string, participant_kind: EncounterParticipantKindView, participant_variant: EncounterParticipantVariantView, status: EncounterParticipantStatusView, position: number, display_name: string, side: EncounterParticipantSideView, initiative?: number, initiative_order: number, defeated: boolean, hidden: boolean, note?: string, note_hint: string | null, reset: EncounterParticipantResetAvailabilityView, record_view: RecordSurfaceView, };
