// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeDistanceView } from "./RuntimeDistanceView";

export type EncounterRuntimeMovementView = { speeds: Array<RuntimeDistanceView>, };
