// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterControlView = { "kind": "multi_select" } | { "kind": "range", min_label: string, max_label: string, min?: number, max?: number, step?: number, } | { "kind": "boolean", true_label: string, false_label: string, } | { "kind": "metric_comparison", key_label: string, operator_label: string, value_label: string, };
