// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterValidationCode = "field_unknown" | "field_not_applicable" | "operator_not_supported" | "value_unknown" | "value_not_applicable" | "value_zero_count" | "range_invalid" | "range_empty" | "metric_unknown" | "metric_ambiguous" | "metric_not_numeric" | "clause_empty" | "clause_conflict" | "filter_too_complex";
