// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterEditorGroupView } from "./FilterEditorGroupView";

export type FilterEditorView = { matching_record_count: bigint, groups: Array<FilterEditorGroupView>, };
