// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterEditorFieldView } from "./FilterEditorFieldView";

export type FilterEditorGroupView = { id: string, label: string, fields: Array<FilterEditorFieldView>, };
