// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterClauseOperator } from "./FilterClauseOperator";

export type FilterFieldView = { id: string, label: string, cardinality: string, value_kind: string, allowed_operators: Array<FilterClauseOperator>, default_operator: FilterClauseOperator, ui_hint: string, supports_counts: boolean, };
