// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryError } from "./QueryError";
import type { QueryPredicate } from "./QueryPredicate";

export type FilterValidationResult = { predicate: QueryPredicate | null, errors: Array<QueryError>, };
