// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryValueOptions } from "./QueryValueOptions";

export type FilterValueListView = { values: QueryValueOptions, };
