// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterClauseOperator } from "./FilterClauseOperator";
import type { FilterRange } from "./FilterRange";
import type { MetricComparison } from "./MetricComparison";

export type FilterClause = { id: string, field: string, operator: FilterClauseOperator, values?: Array<string>, range?: FilterRange, metric?: MetricComparison, };
