// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterClauseOperator = "include_any" | "include_all" | "exclude_any" | "range" | "metric_compare";
