// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryPredicate } from "./QueryPredicate";

export type FilterSavedListRequest = { list_ref: string, query?: string, filter?: QueryPredicate, };
