// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterFieldView } from "./FilterFieldView";

export type FilterFieldListView = { matching_record_count: bigint, fields: Array<FilterFieldView>, };
