// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterControlView } from "./FilterControlView";
import type { FilterFieldPlacement } from "./FilterFieldPlacement";
import type { QueryFieldDefinition } from "./QueryFieldDefinition";

export type FilterEditorFieldView = { definition: QueryFieldDefinition, control: FilterControlView, placement: FilterFieldPlacement, };
