// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterValueOption } from "./FilterValueOption";

export type FilterValueListView = { field_id: string, matching_record_count: bigint, options: Array<FilterValueOption>, };
