// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicSearchFilter } from "./BasicSearchFilter";

export type FilterDiscoveryContext = { "kind": "filtered", filter: BasicSearchFilter, };
