// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterValidationCode } from "./FilterValidationCode";

export type FilterValidationMessage = { severity: string, code: FilterValidationCode, clause_id?: string, field_id?: string, value?: string, message: string, recoverable_action?: string, };
