// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFieldCounts } from "./QueryFieldCounts";

export type FilterCountsView = { counts: QueryFieldCounts, };
