// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterClauseOperator } from "./FilterClauseOperator";
import type { FilterControlView } from "./FilterControlView";
import type { FilterFieldPlacement } from "./FilterFieldPlacement";

export type FilterEditorFieldView = { id: string, label: string, control: FilterControlView, placement: FilterFieldPlacement, allowed_operators: Array<FilterClauseOperator>, default_operator: FilterClauseOperator, supports_counts: boolean, };
