// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterEditorGroupView } from "./FilterEditorGroupView";
import type { QueryLimits } from "./QueryLimits";

export type FilterEditorView = { catalog_version: number, limits: QueryLimits, groups: Array<FilterEditorGroupView>, };
