// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryPredicate } from "./QueryPredicate";
import type { RetrievalModeView } from "./RetrievalModeView";

export type FilterDiscoveryContext = { "kind": "filtered", filter: QueryPredicate | null, text: string | null, mode: RetrievalModeView, } | { "kind": "saved_list", list_ref: string, filter: QueryPredicate | null, text: string | null, mode: RetrievalModeView, };
