// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicSearchFilter } from "./BasicSearchFilter";
import type { FilterValidationMessage } from "./FilterValidationMessage";

export type FilterValidationResult = { compiled_filter?: unknown, messages: Array<FilterValidationMessage>, normalized_filter?: BasicSearchFilter, };
