// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordRelationshipView } from "./RecordRelationshipView";
import type { RecordSummaryView } from "./RecordSummaryView";

export type GraphSectionView = { records: Array<RecordSummaryView>, occurrences: Array<RecordRelationshipView>, truncated: boolean, };
