// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphSectionView } from "./GraphSectionView";
import type { RecordSummaryView } from "./RecordSummaryView";

export type GraphContextView = { seed: RecordSummaryView, outgoing: GraphSectionView, backlinks: GraphSectionView, };
