// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedContentLocator } from "./OwnedContentLocator";

export type GraphContextViewRequest = { record_key: string, owners: Array<OwnedContentLocator> | null, source_fingerprint: string | null, outgoing_limit: number, backlink_limit: number, };
