// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8UnsupportedValueView } from "./H8UnsupportedValueView";

export type H8FactView<T> = { "state": "missing" } | { "state": "null" } | { "state": "known", "value": T } | { "state": "unsupported", "value": H8UnsupportedValueView };
