// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8FactView } from "./H8FactView";

export type H8PageSourceMetadataView = { ownership: H8FactView<string>, flags: H8FactView<string>, stats: H8FactView<string>, };
