// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8UnsupportedValueView } from "./H8UnsupportedValueView";

export type H8UnsupportedFieldView = { relative_path: string, authored_order: number, value: H8UnsupportedValueView, };
