// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8FactView } from "./H8FactView";
import type { H8IdentityStabilityView } from "./H8IdentityStabilityView";

export type H8UnsupportedChildView = { locator: string, identity_stability: H8IdentityStabilityView, source_id: H8FactView<string>, source_ordinal: number, exact_source: string, reason: string, };
