// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorPresentationView } from "./ActorPresentationView";
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";

export type HazardPresentationView = { actor: ActorPresentationView, complex: FactView<boolean>, stealth: NumberFactView, hardness: NumberFactView, };
