// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentBlockView } from "./CreatureSurfaceContentBlockView";

export type HazardSurfaceLifecycleView = { description?: Array<CreatureSurfaceContentBlockView>, disable?: Array<CreatureSurfaceContentBlockView>, routine?: Array<CreatureSurfaceContentBlockView>, reset?: Array<CreatureSurfaceContentBlockView>, };
