// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HazardSurfaceExpectedShapeView = "any" | "boolean" | "integer" | "string" | "string_or_boolean" | "string_or_array" | "array" | "object" | "closed_vocabulary" | "rich_document";
