// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceApplicabilityStateView } from "./HazardSurfaceApplicabilityStateView";

export type HazardSurfaceDefenseApplicabilityView = { health: HazardSurfaceApplicabilityStateView, structure: HazardSurfaceApplicabilityStateView, rule_id: string, rule_version: number, };
