// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentBlockView } from "./CreatureSurfaceContentBlockView";

export type HazardSurfaceHitPointsView = { current?: number, maximum?: number, temporary?: number, broken_threshold?: number, details?: Array<CreatureSurfaceContentBlockView>, };
