// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HazardSurfaceOccurrenceIdentityStabilityView = "stable_source_identity" | "unstable_authored_ordinal";
