// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceRelationshipTargetView } from "./HazardSurfaceRelationshipTargetView";

export type HazardSurfaceRelationshipView = { relationship_id: string, authored_order: number, source_occurrence_id?: string, target: HazardSurfaceRelationshipTargetView, };
