// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HazardSurfaceRelationshipTargetView = { "target_type": "entity", entity_id: string, } | { "target_type": "occurrence", occurrence_id: string, };
