// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceUnavailableStateView } from "./HazardSurfaceUnavailableStateView";

export type HazardSurfaceUnavailableView = { fact_id?: string, state: HazardSurfaceUnavailableStateView, field: string, component_id?: string, message: string, consequence?: string, };
