// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HazardSurfaceEmitsSoundView = { "sound_type": "boolean", value: boolean, } | { "sound_type": "named", value: string, };
