// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceHitPointsView } from "./HazardSurfaceHitPointsView";
import type { HazardSurfaceIwrView } from "./HazardSurfaceIwrView";
import type { HazardSurfaceSavesView } from "./HazardSurfaceSavesView";

export type HazardSurfaceDefensesView = { armor_class?: number, hardness?: number, hit_points?: HazardSurfaceHitPointsView, saves?: HazardSurfaceSavesView, immunities?: Array<HazardSurfaceIwrView>, weaknesses?: Array<HazardSurfaceIwrView>, resistances?: Array<HazardSurfaceIwrView>, };
