// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceExpectedShapeView } from "./HazardSurfaceExpectedShapeView";
import type { HazardSurfaceSourceShapeView } from "./HazardSurfaceSourceShapeView";

export type HazardSurfaceSourceFactView<T> = { "state": "missing", source_path: string, } | { "state": "null", source_path: string, } | { "state": "typed", source_path: string, value: T, } | { "state": "unsupported", source_path: string, exact_json: string, expected_shape: HazardSurfaceExpectedShapeView, actual_shape: HazardSurfaceSourceShapeView, };
