// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceProvenanceTextView } from "./HazardSurfaceProvenanceTextView";

export type HazardSurfaceProvenanceView = { source_path: string, source_contract_version: string, source_system_version: string, source_upstream_commit: string, convenience_rule_id: string, convenience_rule_version: number, image: HazardSurfaceProvenanceTextView, publication_license: HazardSurfaceProvenanceTextView, };
