// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardSurfaceSourceFactView } from "./HazardSurfaceSourceFactView";

export type HazardSurfaceItemLineageView = { compendium_source: HazardSurfaceSourceFactView<string>, };
