// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { HazardSurfaceActivityView } from "./HazardSurfaceActivityView";
import type { HazardSurfaceComplexityView } from "./HazardSurfaceComplexityView";
import type { HazardSurfaceDefensesView } from "./HazardSurfaceDefensesView";
import type { HazardSurfaceDetectionView } from "./HazardSurfaceDetectionView";
import type { HazardSurfaceEmitsSoundView } from "./HazardSurfaceEmitsSoundView";
import type { HazardSurfaceLifecycleView } from "./HazardSurfaceLifecycleView";
import type { HazardSurfaceProvenanceView } from "./HazardSurfaceProvenanceView";
import type { HazardSurfaceRelationshipView } from "./HazardSurfaceRelationshipView";
import type { HazardSurfaceSizeView } from "./HazardSurfaceSizeView";
import type { HazardSurfaceUnavailableView } from "./HazardSurfaceUnavailableView";

export type HazardSurfaceView = { teaser?: string, complexity?: HazardSurfaceComplexityView, size?: HazardSurfaceSizeView, emits_sound?: HazardSurfaceEmitsSoundView, detection?: HazardSurfaceDetectionView, defenses?: HazardSurfaceDefensesView, lifecycle?: HazardSurfaceLifecycleView, activities?: Array<HazardSurfaceActivityView>, content?: Array<CreatureSurfaceContentView>, relationships?: Array<HazardSurfaceRelationshipView>, unavailable_fields?: Array<HazardSurfaceUnavailableView>, provenance: HazardSurfaceProvenanceView, };
