// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListSummaryView } from "./SavedListSummaryView";

export type ImportSavedListView = { list: SavedListSummaryView, replaced: boolean, active_count: bigint, unresolved_count: bigint, };
