// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListExportDocumentView } from "./SavedListExportDocumentView";

export type ImportSavedListRequest = { document: SavedListExportDocumentView, id?: string, replace: boolean, };
