// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";

export type IwrEntryView = { damage_type: FactView<string>, magnitude: NumberFactView, exceptions: FactView<Array<string>>, double_against: FactView<Array<string>>, };
