// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8FactView } from "./H8FactView";

export type JournalPageVideoView = { controls: H8FactView<boolean>, loop_playback: H8FactView<boolean>, autoplay: H8FactView<boolean>, volume: H8FactView<string>, timestamp: H8FactView<string>, width: H8FactView<string>, height: H8FactView<string>, };
