// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentBlockView } from "./CreatureSurfaceContentBlockView";
import type { H8FactView } from "./H8FactView";

export type JournalPageTextView = { content: H8FactView<Array<CreatureSurfaceContentBlockView>>, format: H8FactView<number>, markdown: H8FactView<string>, };
