// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { H8FactView } from "./H8FactView";
import type { H8ProvenanceView } from "./H8ProvenanceView";
import type { H8SourceMetadataView } from "./H8SourceMetadataView";
import type { H8UnsupportedFieldView } from "./H8UnsupportedFieldView";
import type { JournalPageEntryView } from "./JournalPageEntryView";

export type JournalSurfaceView = { source_id: string, pages: H8FactView<Array<JournalPageEntryView>>, content?: Array<CreatureSurfaceContentView>, source_metadata: H8SourceMetadataView, unsupported_fields?: Array<H8UnsupportedFieldView>, provenance: H8ProvenanceView, };
