// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8FactView } from "./H8FactView";

export type JournalPageTitleView = { show: H8FactView<boolean>, level: H8FactView<number>, };
