// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8FactView } from "./H8FactView";
import type { H8IdentityStabilityView } from "./H8IdentityStabilityView";
import type { H8PageSourceMetadataView } from "./H8PageSourceMetadataView";
import type { H8UnsupportedFieldView } from "./H8UnsupportedFieldView";
import type { JournalPageTextView } from "./JournalPageTextView";
import type { JournalPageTitleView } from "./JournalPageTitleView";
import type { JournalPageVideoView } from "./JournalPageVideoView";

export type JournalPageView = { locator: string, identity_stability: H8IdentityStabilityView, source_id: H8FactView<string>, source_ordinal: number, name: H8FactView<string>, page_kind: H8FactView<string>, sort: H8FactView<number>, title: H8FactView<JournalPageTitleView>, text: H8FactView<JournalPageTextView>, source: H8FactView<string>, image_source: H8FactView<string>, image_caption: H8FactView<string>, video: H8FactView<JournalPageVideoView>, source_system: H8FactView<string>, source_metadata: H8PageSourceMetadataView, unsupported_fields?: Array<H8UnsupportedFieldView>, };
