// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8UnsupportedChildView } from "./H8UnsupportedChildView";
import type { JournalPageView } from "./JournalPageView";

export type JournalPageEntryView = { "entry_type": "page", page: JournalPageView, } | { "entry_type": "unsupported", unsupported: H8UnsupportedChildView, };
