// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageExpressionView } from "./DamageExpressionView";

export type MechanicActivityModeView = { mode_id: string, label: string, target?: string, range?: string, time?: string, damage: Array<DamageExpressionView>, };
