// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageExpressionView } from "./DamageExpressionView";
import type { MechanicActivityKindView } from "./MechanicActivityKindView";
import type { MechanicActivityUsageView } from "./MechanicActivityUsageView";

export type MechanicActivityView = { activity_id: string, label: string, kind: MechanicActivityKindView, usage: MechanicActivityUsageView, damage: Array<DamageExpressionView>, };
