// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityRollView } from "./ActivityRollView";
import type { DamageExpressionView } from "./DamageExpressionView";
import type { MechanicActivityKindView } from "./MechanicActivityKindView";
import type { MechanicActivityModeView } from "./MechanicActivityModeView";
import type { MechanicActivityUsageView } from "./MechanicActivityUsageView";

export type MechanicActivityView = { activity_id: string, label: string, kind: MechanicActivityKindView, usage: MechanicActivityUsageView, rolls: Array<ActivityRollView>, damage: Array<DamageExpressionView>, modes: Array<MechanicActivityModeView>, };
