// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityRollView } from "./ActivityRollView";
import type { DamageExpressionView } from "./DamageExpressionView";
import type { MechanicActivityKindView } from "./MechanicActivityKindView";
import type { RecordNavigationView } from "./RecordNavigationView";
import type { RuntimeEffectNoteView } from "./RuntimeEffectNoteView";

export type MechanicActivityView = { activity_id: string, label: string, kind: MechanicActivityKindView, navigation: RecordNavigationView, notes: Array<RuntimeEffectNoteView>, rolls: Array<ActivityRollView>, damage: Array<DamageExpressionView>, };
