// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAdjustmentView } from "./RuntimeAdjustmentView";
import type { RuntimeEffectNoteView } from "./RuntimeEffectNoteView";

export type MovementSpeedView = { movement_type: string, label: string, base_value_feet: bigint, adjusted_value_feet: bigint, adjustments: Array<RuntimeAdjustmentView>, suppressed_adjustments: Array<RuntimeAdjustmentView>, notes: Array<RuntimeEffectNoteView>, };
