// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumberAdjustmentView } from "./NumberAdjustmentView";
import type { QueryFieldState } from "./QueryFieldState";

export type NumberFactView = { state: QueryFieldState, value: number | null, adjustment: NumberAdjustmentView | null, };
