// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeEffectNoteView } from "./RuntimeEffectNoteView";
import type { StatModifierView } from "./StatModifierView";

export type NumberAdjustmentView = { authored: number, applied: Array<StatModifierView>, suppressed: Array<StatModifierView>, notes: Array<RuntimeEffectNoteView>, };
