// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultWindowMode } from "./ResultWindowMode";
import type { SearchPageRequest } from "./SearchPageRequest";

export type OpenResultWindowRequest = { mode: ResultWindowMode, page: SearchPageRequest, include_diagnostics: boolean, };
