// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNavigationView } from "./RecordNavigationView";

export type OwnedRecordLinkView = { navigation: RecordNavigationView, title: string, family: string, usage: string | null, };
