// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreparedFieldBodyView } from "./PreparedFieldBodyView";
import type { SourceContentLocator } from "./SourceContentLocator";

export type PreparedContentFieldView = { locator: SourceContentLocator, role: string, source_fingerprint: string | null, body: PreparedFieldBodyView, };
