// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentControlView } from "./ContentControlView";
import type { QueryFieldState } from "./QueryFieldState";

export type PreparedFieldBodyView = { "kind": "html", html: string, controls: Array<ContentControlView>, } | { "kind": "plain", text: string, } | { "kind": "unavailable", state: QueryFieldState, };
