// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PresentationInline = { "kind": "text", text: string, } | { "kind": "strong", spans: Array<PresentationInline>, } | { "kind": "emphasis", spans: Array<PresentationInline>, } | { "kind": "code", text: string, } | { "kind": "reference", label: string, record_key?: string, embedded: boolean, } | { "kind": "line_break" };
