// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationInline } from "./PresentationInline";
import type { PresentationListItem } from "./PresentationListItem";
import type { PresentationTableRow } from "./PresentationTableRow";

export type PresentationContentBlock = { "kind": "heading", level: number, text: string, } | { "kind": "paragraph", spans: Array<PresentationInline>, } | { "kind": "list", ordered: boolean, items: Array<PresentationListItem>, } | { "kind": "table", caption: string | null, rows: Array<PresentationTableRow>, } | { "kind": "rule" };
