// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationBadgeKind } from "./PresentationBadgeKind";

export type PresentationBadge = { kind: PresentationBadgeKind, label: string, value: string, };
