// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationBlock } from "./PresentationBlock";
import type { PresentationSectionKind } from "./PresentationSectionKind";

export type PresentationSection = { kind: PresentationSectionKind, title: string, blocks: Array<PresentationBlock>, };
