// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationContent } from "./PresentationContent";
import type { PresentationFact } from "./PresentationFact";
import type { PresentationRelationship } from "./PresentationRelationship";
import type { PresentationText } from "./PresentationText";

export type PresentationBlock = { "kind": "fact_list", "content": Array<PresentationFact> } | { "kind": "prose", "content": PresentationText } | { "kind": "content", "content": PresentationContent } | { "kind": "relationships", "content": Array<PresentationRelationship> };
