// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationRelationshipKind } from "./PresentationRelationshipKind";

export type PresentationRelationship = { kind: PresentationRelationshipKind, label: string, record_key: string | null, };
