// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFieldType } from "./QueryFieldType";
import type { QueryValueDiscovery } from "./QueryValueDiscovery";

export type QueryFieldDefinition = { id: string, path: string, scope: string | null, field_type: QueryFieldType, label: string, family_types: Array<string>, units: string | null, basis: string, choices: Array<string>, operators: Array<string>, examples: Array<string>, value_discovery: QueryValueDiscovery, };
