// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryLimits = { source_bytes: number, nodes: number, depth: number, literal_list: number, };
