// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryLiteral } from "./QueryLiteral";

export type QueryValueOption = { value: QueryLiteral, distinct_roots: bigint, selected: boolean, };
