// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryValueOption } from "./QueryValueOption";

export type QueryValueOptions = { field: string, options: Array<QueryValueOption>, total_values: bigint, exhaustive: boolean, count_basis: string, };
