// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryValueDiscovery = "open_values" | "closed_choices" | "boolean_counts" | "numeric_statistics" | "collection_states";
