// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuerySetMatch = "includes" | "includes_any" | "includes_all" | "excludes_any";
