// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryStateCount } from "./QueryStateCount";

/**
 * `counting_scope` partitions roots for root values and counts occurrences
 * for collection-member states.
 */
export type QueryFieldCounts = { field: string, counting_scope: string, states: Array<QueryStateCount>, exhaustive: boolean, count_basis: string, minimum: number | null, maximum: number | null, };
