// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFieldState } from "./QueryFieldState";

export type QueryStateCount = { state: QueryFieldState, occurrences: bigint, distinct_roots: bigint, };
