// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordResolutionCandidateView } from "./RecordResolutionCandidateView";

export type RecordResolutionAmbiguousView = { record_ref: string, matches: Array<RecordResolutionCandidateView>, };
