// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFieldState } from "./QueryFieldState";
import type { RecordNavigationView } from "./RecordNavigationView";
import type { SourceContentLocator } from "./SourceContentLocator";

export type RecordRelationshipView = { source: SourceContentLocator, ordinal: number, origin: string, kind: string, authored_target: string | null, occurrence_path: string | null, audiences: Array<string>, availability: QueryFieldState | null, status: string, target: RecordNavigationView | null, url: string | null, };
