// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordDetailRequest } from "./RecordDetailRequest";
import type { RecordSurfaceProfileView } from "./RecordSurfaceProfileView";

export type RecordSurfaceRequest = { selection: RecordDetailRequest, profile: RecordSurfaceProfileView, };
