// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordBadgeView } from "./RecordBadgeView";

export type RecordSummaryView = { record_key: string, title: string, kind: string, kind_label: string, level_label?: string, rarity?: string, traits?: Array<RecordBadgeView>, taxonomy?: Array<RecordBadgeView>, publication?: string, pack_label?: string, preview?: string, };
