// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceView } from "./CreatureSurfaceView";
import type { HazardSurfaceView } from "./HazardSurfaceView";
import type { JournalSurfaceView } from "./JournalSurfaceView";
import type { RollTableSurfaceView } from "./RollTableSurfaceView";
import type { SpellSurfaceView } from "./SpellSurfaceView";
import type { SurfaceUnavailableView } from "./SurfaceUnavailableView";

export type RecordSurfacePresentationView = { "presentation_type": "creature", body: CreatureSurfaceView, } | { "presentation_type": "hazard", body: HazardSurfaceView, } | { "presentation_type": "spell", body: SpellSurfaceView, } | { "presentation_type": "journal", body: JournalSurfaceView, } | { "presentation_type": "roll_table", body: RollTableSurfaceView, } | { "presentation_type": "unavailable", unavailable: SurfaceUnavailableView, };
