// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordPresentationDocument } from "./RecordPresentationDocument";
import type { RecordSurfaceHeaderView } from "./RecordSurfaceHeaderView";
import type { RecordSurfaceProfileView } from "./RecordSurfaceProfileView";
import type { RecordSurfaceSectionView } from "./RecordSurfaceSectionView";

export type RecordSurfaceView = { record_key: string, title: string, kind: string, profile: RecordSurfaceProfileView, header: RecordSurfaceHeaderView, sections: Array<RecordSurfaceSectionView>, fallback_presentation?: RecordPresentationDocument, };
