// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceView } from "./CreatureSurfaceView";
import type { SurfaceUnavailableView } from "./SurfaceUnavailableView";

export type RecordSurfacePresentationView = { "presentation_type": "creature", body: CreatureSurfaceView, } | { "presentation_type": "unavailable", unavailable: SurfaceUnavailableView, };
