// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordKey } from "./RecordKey";
import type { RecordResolutionCandidateView } from "./RecordResolutionCandidateView";

export type RecordRefResolutionView = { "kind": "key", "value": RecordKey } | { "kind": "miss" } | { "kind": "ambiguous", "value": Array<RecordResolutionCandidateView> };
