// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordListSortView = { "kind": "alphabetical" } | { "kind": "level_asc" } | { "kind": "level_desc" } | { "kind": "price_asc" } | { "kind": "price_desc" } | { "kind": "record_key" } | { "kind": "random", seed: bigint, };
