// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationContent } from "./PresentationContent";
import type { RecordSurfaceSectionKindView } from "./RecordSurfaceSectionKindView";
import type { SurfaceActivityView } from "./SurfaceActivityView";
import type { SurfaceNoteView } from "./SurfaceNoteView";
import type { SurfaceValueGroupView } from "./SurfaceValueGroupView";
import type { SurfaceValueView } from "./SurfaceValueView";

export type RecordSurfaceSectionView = { kind: RecordSurfaceSectionKindView, title: string, values?: Array<SurfaceValueView>, groups?: Array<SurfaceValueGroupView>, activities?: Array<SurfaceActivityView>, notes?: Array<SurfaceNoteView>, content?: PresentationContent, collapsed_by_default: boolean, };
