// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterRuntimeView } from "./EncounterRuntimeView";
import type { RecordSurfaceIssueView } from "./RecordSurfaceIssueView";
import type { RecordSurfaceMetadataView } from "./RecordSurfaceMetadataView";
import type { RecordSurfacePresentationView } from "./RecordSurfacePresentationView";
import type { RecordSurfaceProfileView } from "./RecordSurfaceProfileView";
import type { RecordSurfaceReferencesView } from "./RecordSurfaceReferencesView";

export type RecordSurfaceView = { metadata: RecordSurfaceMetadataView, profile: RecordSurfaceProfileView, presentation: RecordSurfacePresentationView, issues?: Array<RecordSurfaceIssueView>, references?: RecordSurfaceReferencesView, encounter?: EncounterRuntimeView, };
