// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordBadgeView } from "./RecordBadgeView";

export type RecordSummaryView = { record_key: string, title: string, kind: string, kind_label: string, source_type: string | null, level_label: string | null, level_basis: string | null, rarity: string | null, traits: Array<RecordBadgeView>, publication: string | null, pack: string | null, };
