// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSummaryView } from "./RecordSummaryView";

export type RecordResolutionCandidateView = { record: RecordSummaryView, query: string, normalized_query: string, match_kind: string, matched_text: string, };
