// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordSurfaceSourceView = { publication_title?: string, pack_label: string, document_type: string, record_type: string, source_path?: string, source_contract_version?: string, source_system_version?: string, source_upstream_commit?: string, };
