// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNavigationView } from "./RecordNavigationView";
import type { RecordRelationshipView } from "./RecordRelationshipView";
import type { RecordSummaryView } from "./RecordSummaryView";
import type { RecordSurfaceView } from "./RecordSurfaceView";

export type RecordDetailView = { record: RecordSummaryView, surface: RecordSurfaceView, selected: RecordNavigationView, relationships: Array<RecordRelationshipView>, relationships_truncated: boolean, };
