// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceEditionCounterpartRoleView } from "./RecordSurfaceEditionCounterpartRoleView";

export type RecordSurfaceEditionCounterpartView = { role: RecordSurfaceEditionCounterpartRoleView, record_key: string, title: string, };
