// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceIssueCodeView } from "./RecordSurfaceIssueCodeView";
import type { RecordSurfaceIssuePlacementView } from "./RecordSurfaceIssuePlacementView";
import type { RecordSurfaceIssueSubjectView } from "./RecordSurfaceIssueSubjectView";

export type RecordSurfaceIssueView = { fact_id?: string, code: RecordSurfaceIssueCodeView, placement: RecordSurfaceIssuePlacementView, subject?: RecordSurfaceIssueSubjectView, fact_label?: string, message: string, consequence?: string, };
