// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNavigationView } from "./RecordNavigationView";
import type { RecordPresentationView } from "./RecordPresentationView";
import type { RecordRelationshipView } from "./RecordRelationshipView";
import type { RecordSummaryView } from "./RecordSummaryView";

export type RecordDetailView = { record: RecordSummaryView, presentation: RecordPresentationView, selected: RecordNavigationView, relationships: Array<RecordRelationshipView>, relationships_truncated: boolean, };
