// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedRecordLinkView } from "./OwnedRecordLinkView";
import type { PreparedContentFieldView } from "./PreparedContentFieldView";
import type { RecordBodyView } from "./RecordBodyView";
import type { RecordSummaryView } from "./RecordSummaryView";

export type RecordPresentationView = { identity: RecordSummaryView, content: Array<PreparedContentFieldView>, owned: Array<OwnedRecordLinkView>, body: RecordBodyView, };
