// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorActivityView } from "./ActorActivityView";
import type { ActorPresentationView } from "./ActorPresentationView";
import type { HazardPresentationView } from "./HazardPresentationView";
import type { PhysicalPresentationView } from "./PhysicalPresentationView";
import type { RollTablePresentationView } from "./RollTablePresentationView";
import type { SpellPresentationView } from "./SpellPresentationView";
import type { TableResultPresentationView } from "./TableResultPresentationView";

export type RecordBodyView = { "kind": "creature", "value": ActorPresentationView } | { "kind": "hazard", "value": HazardPresentationView } | { "kind": "spell", "value": SpellPresentationView } | { "kind": "activity", "value": ActorActivityView } | { "kind": "physical_reference", "value": PhysicalPresentationView } | { "kind": "roll_table", "value": RollTablePresentationView } | { "kind": "table_result", "value": TableResultPresentationView } | { "kind": "content" };
