// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceBadgeView } from "./SurfaceBadgeView";

export type RecordSurfaceHeaderView = { level_label?: string, kind_label?: string, rarity?: string, traits: Array<SurfaceBadgeView>, publication?: string, pack?: string, };
