// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordSurfaceIssuePlacementView = "record" | "classification" | "defenses" | "activity" | "casting" | "targeting" | "damage" | "duration" | "heightening" | "ritual" | "rules" | "forms" | "references";
