// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedContentLocator } from "./OwnedContentLocator";
import type { SourcePassageAddress } from "./SourcePassageAddress";

export type RecordDetailRequest = { record_key: string, owners: Array<OwnedContentLocator>, fields: Array<string>, passage: SourcePassageAddress | null, source_fingerprint: string | null, };
