// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceReferenceSectionView } from "./RecordSurfaceReferenceSectionView";

export type RecordSurfaceReferencesView = { outgoing: RecordSurfaceReferenceSectionView, backlinks: RecordSurfaceReferenceSectionView, };
