// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceEditionCounterpartView } from "./RecordSurfaceEditionCounterpartView";
import type { RecordSurfaceEditionStatusView } from "./RecordSurfaceEditionStatusView";

export type RecordSurfaceEditionView = { status: RecordSurfaceEditionStatusView, counterparts: Array<RecordSurfaceEditionCounterpartView>, };
