// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSummaryView } from "./RecordSummaryView";
import type { SearchPageView } from "./SearchPageView";

export type RecordListView = { records: Array<RecordSummaryView>, page: SearchPageView, };
