// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppErrorCode } from "./AppErrorCode";
import type { RecordSurfaceReferenceEdgeView } from "./RecordSurfaceReferenceEdgeView";
import type { RecordSurfaceReferenceRecordView } from "./RecordSurfaceReferenceRecordView";

export type RecordSurfaceReferenceSectionView = { "state": "not_requested" } | { "state": "available", requested_limit: number, records: Array<RecordSurfaceReferenceRecordView>, edges: Array<RecordSurfaceReferenceEdgeView>, total_records: number, total_edges: number, truncated: boolean, } | { "state": "unavailable", requested_limit: number, code: AppErrorCode, message: string, };
