// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordSurfaceIssueCodeView = "required_missing" | "required_null" | "required_empty" | "unsupported" | "malformed" | "ambiguous" | "unavailable" | "unmodeled" | "source_consistency_conflict";
