// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceSourceView } from "./RecordSurfaceSourceView";

export type RecordSurfaceMetadataView = { record_key?: string, title: string, kind: string, kind_label: string, level?: number, rarity?: string, traits?: Array<string>, source?: RecordSurfaceSourceView, };
