// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordDetailRequest = { child_locator?: string, spell_form_id?: string, spell_cast_rank?: number, reference_outgoing_limit?: number, reference_backlink_limit?: number, };
