// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordSurfaceIssueTargetView = { "target_type": "activity", occurrence_id: string, };
