// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationBadge } from "./PresentationBadge";
import type { PresentationFact } from "./PresentationFact";
import type { PresentationSection } from "./PresentationSection";

export type RecordPresentationDocument = { record_key: string, kind: string, title: string, identity: Array<PresentationFact>, badges: Array<PresentationBadge>, sections: Array<PresentationSection>, };
