// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceReferenceSourceView } from "./RecordSurfaceReferenceSourceView";

export type RecordSurfaceReferenceEdgeView = { from_record_key: string, to_record_key: string, display_text?: string, reference_text: string, source: RecordSurfaceReferenceSourceView, };
