// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordSurfaceSectionKindView = "identity" | "description" | "vitals" | "runtime" | "defenses" | "saves" | "abilities" | "skills" | "movement" | "activities" | "conditions" | "notes" | "rich_content" | "references" | "fallback_presentation";
