// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordPresentationDocument } from "./RecordPresentationDocument";

export type RecordDetailView = { record_key: string, title: string, kind: string, presentation: RecordPresentationDocument, };
