// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSurfaceIssueCodeView } from "./RecordSurfaceIssueCodeView";
import type { RecordSurfaceIssuePlacementView } from "./RecordSurfaceIssuePlacementView";

export type RecordSurfaceIssueView = { code: RecordSurfaceIssueCodeView, placement: RecordSurfaceIssuePlacementView, message: string, };
