// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceSearchDirection } from "./ReferenceSearchDirection";

export type RelationshipConstraint = { direction: ReferenceSearchDirection, record_key: string, };
