// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSummaryView } from "./RecordSummaryView";

export type RemasterLinkView = { legacy_record: RecordSummaryView, remaster_record: RecordSummaryView, evidence: string, };
