// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReorderEncounterParticipantPlacementView } from "./ReorderEncounterParticipantPlacementView";

export type ReorderEncounterParticipantRequest = { participant_key: string, target_participant_key: string, placement: ReorderEncounterParticipantPlacementView, };
