// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSummaryView } from "./RecordSummaryView";
import type { SearchWitnessView } from "./SearchWitnessView";

export type ResultWindowRow = { record: RecordSummaryView, matches: Array<SearchWitnessView>, };
