// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicSearchFilter } from "./BasicSearchFilter";
import type { RecordListSortView } from "./RecordListSortView";

export type ResultWindowMode = { "kind": "list_records", filter?: BasicSearchFilter, sort: RecordListSortView, } | { "kind": "text_search", query: string, exclude?: string, filter?: BasicSearchFilter, };
