// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultWindowModeSummary } from "./ResultWindowModeSummary";
import type { ResultWindowRow } from "./ResultWindowRow";
import type { SearchPageView } from "./SearchPageView";

export type ResultWindowPage = { window_id: bigint, mode: ResultWindowModeSummary, page: SearchPageView, rows: Array<ResultWindowRow>, };
