// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSummaryView } from "./RecordSummaryView";
import type { ResultMatchSummary } from "./ResultMatchSummary";

export type ResultWindowRow = { record: RecordSummaryView, match_summary?: ResultMatchSummary, };
