// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetrievalModeView } from "./RetrievalModeView";

export type ResultWindowModeSummary = { "kind": "list_records" } | { "kind": "text_search", query: string, mode: RetrievalModeView, };
