// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryPredicate } from "./QueryPredicate";
import type { RetrievalModeView } from "./RetrievalModeView";

export type ResultWindowMode = { "kind": "list_records", filter: QueryPredicate | null, } | { "kind": "text_search", query: string, filter: QueryPredicate | null, mode: RetrievalModeView, };
