// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAdjustmentView } from "./RuntimeAdjustmentView";
import type { RuntimeCountSegmentView } from "./RuntimeCountSegmentView";
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type RuntimeCountView = { label: string, base_value: bigint, adjusted_value: bigint, segments: Array<RuntimeCountSegmentView>, adjustments: Array<RuntimeAdjustmentView>, suppressed_adjustments: Array<RuntimeAdjustmentView>, provenance: RuntimeFactProvenanceView, };
