// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";
import type { RuntimeModifierView } from "./RuntimeModifierView";
import type { RuntimeRollSurfaceView } from "./RuntimeRollSurfaceView";

export type RuntimeRollView = { roll_id: string, label: string, base_value: number, adjusted_value: number, surface: RuntimeRollSurfaceView, modifiers?: Array<RuntimeModifierView>, suppressed_modifiers?: Array<RuntimeModifierView>, provenance: RuntimeFactProvenanceView, };
