// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type RuntimeCapabilityView = { available: boolean, provenance?: RuntimeFactProvenanceView, reason?: string, };
