// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeCanonicalTargetView } from "./RuntimeCanonicalTargetView";
import type { RuntimeFactSourceView } from "./RuntimeFactSourceView";

export type RuntimeFactProvenanceView = { source: RuntimeFactSourceView, canonical_target?: RuntimeCanonicalTargetView, };
