// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeAdjustmentView = { source: string, label: string, value: bigint, reason?: string, };
