// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";

export type RuntimeAdjustmentView = { provenance: RuntimeFactProvenanceView, label: string, value: number, reason?: string, };
