// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeDamageEffectKindView } from "./RuntimeDamageEffectKindView";
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";
import type { RuntimeModifierView } from "./RuntimeModifierView";

export type RuntimeFormulaView = { damage_id: string, label?: string, formula: string, adjusted_formula?: string, damage_type?: string, effect_kind: RuntimeDamageEffectKindView, modifiers: Array<RuntimeModifierView>, provenance: RuntimeFactProvenanceView, };
