// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";
import type { StatModifierTypeView } from "./StatModifierTypeView";

export type RuntimeModifierView = { provenance: RuntimeFactProvenanceView, label: string, modifier_type: StatModifierTypeView, value: number, };
