// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantVariantView } from "./EncounterParticipantVariantView";
import type { RuntimeRuleView } from "./RuntimeRuleView";

export type RuntimeFactSourceView = { "source_type": "canonical_record" } | { "source_type": "participant_state" } | { "source_type": "participant_variant", variant: EncounterParticipantVariantView, } | { "source_type": "condition", condition_id: number, condition_ref: string, label: string, } | { "source_type": "runtime_rule", rule: RuntimeRuleView, };
