// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFactProvenanceView } from "./RuntimeFactProvenanceView";
import type { RuntimeModifierView } from "./RuntimeModifierView";

export type RuntimeNumberView = { label: string, base_value: bigint, adjusted_value: bigint, modifiers: Array<RuntimeModifierView>, suppressed_modifiers: Array<RuntimeModifierView>, provenance: RuntimeFactProvenanceView, };
