// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListItemMutationOutcomeView } from "./SavedListItemMutationOutcomeView";

export type SavedListItemMutationView = { list_key: string, slug: string, record_key: string, record_name?: string, outcome: SavedListItemMutationOutcomeView, };
