// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListSummaryView } from "./SavedListSummaryView";

export type SavedListUpdateView = { list: SavedListSummaryView, };
