// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavedListItemMutationOutcomeView = "added" | "already_present" | "removed" | "not_present";
