// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListExportItemView } from "./SavedListExportItemView";
import type { SavedListExportListView } from "./SavedListExportListView";

export type SavedListExportDocumentView = { format: string, version: bigint, exported_at: string, list: SavedListExportListView, items: Array<SavedListExportItemView>, };
