// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavedListSummaryView = { list_key: string, slug: string, name: string, description?: string, tags: Array<string>, item_count: bigint, created_at: string, updated_at: string, };
