// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordSummaryView } from "./RecordSummaryView";
import type { SavedListItemSnapshotView } from "./SavedListItemSnapshotView";
import type { SavedListItemStatusView } from "./SavedListItemStatusView";

export type SavedListItemView = { record_key: string, position: bigint, note?: string, status: SavedListItemStatusView, snapshot: SavedListItemSnapshotView, record?: RecordSummaryView, };
