// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListItemView } from "./SavedListItemView";
import type { SavedListSummaryView } from "./SavedListSummaryView";

export type SavedListDetailView = { list: SavedListSummaryView, items: Array<SavedListItemView>, };
