// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedListItemSnapshotView } from "./SavedListItemSnapshotView";
import type { SavedListItemStatusView } from "./SavedListItemStatusView";

export type SavedListExportItemView = { position: bigint, record_key: string, record_name: string, kind?: string, status: SavedListItemStatusView, note?: string, snapshot: SavedListItemSnapshotView, };
