// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNavigationView } from "./RecordNavigationView";
import type { SearchLaneView } from "./SearchLaneView";

export type SearchWitnessView = { navigation: RecordNavigationView, lane: SearchLaneView, label: string | null, snippet: string | null, lexical_rank: number | null, semantic_similarity: number | null, };
