// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchPageView = { number: number, size: number, count: number, total: bigint, has_more: boolean, next_page?: number, };
