// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultWindowRow } from "./ResultWindowRow";
import type { SearchCoverageView } from "./SearchCoverageView";
import type { SearchPageView } from "./SearchPageView";

export type SearchResultsView = { rows: Array<ResultWindowRow>, page: SearchPageView, coverage: SearchCoverageView, };
