// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchCoverageView = { exhaustive: boolean, semantic_unit_window: number | null, candidate_roots: number, count_basis: string, };
