// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedContentLocator } from "./OwnedContentLocator";
import type { RecordKey } from "./RecordKey";

/**
 * A source field, never an output hash, display label or HTML node ordinal.
 * Callers establish identity from their admitted source and retain this locator
 * alongside the authored DTO. Snapshot-local owners must not reconcile user
 * state across rebuilds by position.
 * `field` is relative to the last owner, for example /system/description/value.
 */
export type SourceContentLocator = { record: RecordKey, owners: Array<OwnedContentLocator>, field: string, };
