// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceByteRange } from "./SourceByteRange";

/**
 * Root, owner chain and field belong to the outer hit/field locator. Hashes bind
 * sections to one source/preparation context; these are not cross-build IDs.
 */
export type SourcePassageAddress = { "kind": "identity", } | { "kind": "html_section", prepared_html_sha256: string, canonical_text_sha256: string, selection_version: string, section_ordinal: number, label: string | null, chunk_bytes: SourceByteRange, } | { "kind": "plain_section", source_text_sha256: string, selection_version: string, section_ordinal: number, label: string | null, chunk_bytes: SourceByteRange, };
