// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellTextPatchOperationView } from "./SpellTextPatchOperationView";

export type SpellTextPatchMemberView = { key: string, order: number, operation: SpellTextPatchOperationView, };
