// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";
import type { SpellChangeView } from "./SpellChangeView";

export type SpellFixedLevelView = { rank: number, changes: FactView<SpellChangeView>, };
