// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";

export type SpellClassificationView = { rank: SpellFactView<number>, traits: SpellFactView<Array<string>>, traditions: SpellFactView<Array<string>>, };
