// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";

export type SpellAreaView = { value: SpellFactView<number>, area_type: SpellFactView<string>, legacy_area_type: SpellFactView<string>, details: SpellFactView<string>, };
