// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageComponentView } from "./DamageComponentView";
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";
import type { SpellAreaView } from "./SpellAreaView";
import type { SpellDefenseView } from "./SpellDefenseView";
import type { SpellFormView } from "./SpellFormView";
import type { SpellHeighteningView } from "./SpellHeighteningView";

export type SpellPresentationView = { rank: NumberFactView, traditions: FactView<Array<string>>, cast: FactView<string>, requirements: FactView<string>, cost: FactView<string>, range: FactView<string>, target: FactView<string>, area: FactView<SpellAreaView>, defense: FactView<SpellDefenseView>, duration: FactView<string>, sustained: FactView<boolean>, damage: FactView<Array<DamageComponentView>>, heightening: FactView<SpellHeighteningView>, forms: FactView<Array<SpellFormView>>, casting_entry: FactView<string>, authored_cast_rank: NumberFactView, };
