// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";
import type { SpellChangeView } from "./SpellChangeView";

export type SpellFormView = { id: string, name: FactView<string>, sort: NumberFactView, changes: FactView<SpellChangeView>, };
