// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellEffectChangeOperationView } from "./SpellEffectChangeOperationView";
import type { SpellEffectChangeView } from "./SpellEffectChangeView";

export type SpellFixedHeighteningChangeView = { "field": "classification" } | { "field": "casting" } | { "field": "targeting" } | { "field": "defense" } | { "field": "effect", operation: SpellEffectChangeOperationView, label: string, value?: SpellEffectChangeView, } | { "field": "duration" } | { "field": "heightening" } | { "field": "rules" };
