// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellDamagePatchMemberView } from "./SpellDamagePatchMemberView";

export type SpellDamagePatchSetView = { members: Array<SpellDamagePatchMemberView>, };
