// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellRulePredicateView } from "./SpellRulePredicateView";

export type SpellItemAlterationRuleView = { item_id: SpellFactView<string>, mode: SpellFactView<string>, predicate: SpellFactView<Array<SpellRulePredicateView>>, property: SpellFactView<string>, value: SpellFactView<string>, };
