// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpellFormCatalogUnavailableReasonView = "unsupported_overlay_root" | "unavailable_overlay_sort";
