// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { SpellDefinitionSurfaceView } from "./SpellDefinitionSurfaceView";
import type { SpellFormCatalogUnavailableReasonView } from "./SpellFormCatalogUnavailableReasonView";
import type { SpellFormView } from "./SpellFormView";
import type { SpellSelectedFormView } from "./SpellSelectedFormView";

export type SpellSurfaceView = { definition: SpellDefinitionSurfaceView, forms: Array<SpellFormView>, selected_form?: SpellSelectedFormView, form_catalog_unavailable?: SpellFormCatalogUnavailableReasonView, content?: Array<CreatureSurfaceContentView>, };
