// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellFormFieldUnavailableView } from "./SpellFormFieldUnavailableView";

export type SpellResolvedFieldView<T> = { "state": "available", value: SpellFactView<T>, } | { "state": "unavailable", unavailable: SpellFormFieldUnavailableView, };
