// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpellFormSelectionUnavailableReasonView = { "reason": "base_rank_unavailable" } | { "reason": "cast_rank_below_base", base_rank: number, cast_rank: number, } | { "reason": "unknown_overlay" } | { "reason": "overlay_root_unavailable" } | { "reason": "duplicate_overlay" } | { "reason": "overlay_identity_unavailable" } | { "reason": "overlay_identity_mismatch" } | { "reason": "unsupported_overlay_type" } | { "reason": "form_id_mismatch" };
