// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";

export type SpellDefenseView = { statistic: FactView<string>, basic: FactView<boolean>, passive: FactView<string>, };
