// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpellFormFieldView = "classification" | "casting" | "targeting" | "defense" | "damage" | "duration" | "heightening" | "rules";
