// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpellRulePredicateView = { "kind": "term", "value": string } | { "kind": "or", "value": Array<string> } | { "kind": "unsupported" };
