// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellAreaView } from "./SpellAreaView";
import type { SpellFactView } from "./SpellFactView";
import type { SpellRangeView } from "./SpellRangeView";

export type SpellTargetingView = { target: SpellFactView<string>, range: SpellFactView<SpellRangeView>, area: SpellFactView<SpellAreaView>, };
