// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";

export type SpellDurationView = { value: SpellFactView<string>, sustained: SpellFactView<boolean>, };
