// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellFixedHeighteningView } from "./SpellFixedHeighteningView";
import type { SpellHeighteningDamageView } from "./SpellHeighteningDamageView";

export type SpellHeighteningView = { "kind": "interval", interval: SpellFactView<number>, area: SpellFactView<number>, damage: SpellFactView<Array<SpellHeighteningDamageView>>, } | { "kind": "fixed", layers: Array<SpellFixedHeighteningView>, };
