// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellCastingView } from "./SpellCastingView";
import type { SpellClassificationView } from "./SpellClassificationView";
import type { SpellDamageView } from "./SpellDamageView";
import type { SpellDefenseView } from "./SpellDefenseView";
import type { SpellDurationView } from "./SpellDurationView";
import type { SpellFactView } from "./SpellFactView";
import type { SpellHeighteningView } from "./SpellHeighteningView";
import type { SpellRitualView } from "./SpellRitualView";
import type { SpellRuleView } from "./SpellRuleView";
import type { SpellTargetingView } from "./SpellTargetingView";

export type SpellDefinitionSurfaceView = { classification: SpellFactView<SpellClassificationView>, casting: SpellFactView<SpellCastingView>, targeting: SpellFactView<SpellTargetingView>, defense: SpellFactView<SpellDefenseView>, damage: SpellFactView<Array<SpellDamageView>>, duration: SpellFactView<SpellDurationView>, heightening: SpellFactView<SpellHeighteningView>, ritual: SpellFactView<SpellRitualView>, rules: SpellFactView<Array<SpellRuleView>>, };
