// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFormKindView } from "./SpellFormKindView";
import type { SpellFormResultView } from "./SpellFormResultView";
import type { SpellPatchView } from "./SpellPatchView";

export type SpellFormView = { id: string, label: string, order: number, cast_rank: number, kind: SpellFormKindView, authored_patch?: SpellPatchView, result: SpellFormResultView, };
