// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellHeighteningTypeView } from "./SpellHeighteningTypeView";
import type { SpellTextPatchSetView } from "./SpellTextPatchSetView";

export type SpellHeighteningPatchView = { kind: SpellFactView<SpellHeighteningTypeView>, interval: SpellFactView<number>, area: SpellFactView<number>, damage: SpellFactView<SpellTextPatchSetView>, };
