// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellRuleDetailView } from "./SpellRuleDetailView";

export type SpellRuleView = { order: number, rule: SpellRuleDetailView, };
