// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFormFieldUnavailableReasonView } from "./SpellFormFieldUnavailableReasonView";
import type { SpellFormFieldView } from "./SpellFormFieldView";
import type { SpellFormPatchSourceView } from "./SpellFormPatchSourceView";

export type SpellFormFieldUnavailableView = { field: SpellFormFieldView, source: SpellFormPatchSourceView, reason: SpellFormFieldUnavailableReasonView, };
