// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFormResultView } from "./SpellFormResultView";

export type SpellEffectiveFormView = { id: string, cast_rank: number, result: SpellFormResultView, };
