// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageComponentView } from "./DamageComponentView";
import type { FactView } from "./FactView";
import type { SpellAreaView } from "./SpellAreaView";
import type { SpellDefenseView } from "./SpellDefenseView";
import type { SpellHeighteningChangeView } from "./SpellHeighteningChangeView";

export type SpellChangeView = { cast: FactView<string>, range: FactView<string>, target: FactView<string>, area: FactView<SpellAreaView>, defense: FactView<SpellDefenseView>, duration: FactView<string>, sustained: FactView<boolean>, traits: FactView<Array<string>>, traditions: FactView<Array<string>>, damage: FactView<Array<DamageComponentView>>, heightening: FactView<SpellHeighteningChangeView>, };
