// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellRulePredicateView } from "./SpellRulePredicateView";

export type SpellEphemeralEffectRuleView = { predicate: SpellFactView<Array<SpellRulePredicateView>>, selectors: SpellFactView<Array<string>>, uuid: SpellFactView<string>, };
