// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellCastingView } from "./SpellCastingView";
import type { SpellClassificationView } from "./SpellClassificationView";
import type { SpellDamagePatchSetView } from "./SpellDamagePatchSetView";
import type { SpellDefenseView } from "./SpellDefenseView";
import type { SpellDurationView } from "./SpellDurationView";
import type { SpellFactView } from "./SpellFactView";
import type { SpellFormFieldView } from "./SpellFormFieldView";
import type { SpellHeighteningPatchView } from "./SpellHeighteningPatchView";
import type { SpellRuleView } from "./SpellRuleView";
import type { SpellTargetingView } from "./SpellTargetingView";

export type SpellPatchView = { classification: SpellFactView<SpellClassificationView>, casting: SpellFactView<SpellCastingView>, targeting: SpellFactView<SpellTargetingView>, defense: SpellFactView<SpellDefenseView>, damage: SpellFactView<SpellDamagePatchSetView>, duration: SpellFactView<SpellDurationView>, heightening: SpellFactView<SpellHeighteningPatchView>, rules: SpellFactView<Array<SpellRuleView>>, unsupported_fields?: Array<SpellFormFieldView>, };
