// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellCastingView } from "./SpellCastingView";
import type { SpellClassificationView } from "./SpellClassificationView";
import type { SpellDamageView } from "./SpellDamageView";
import type { SpellDefenseView } from "./SpellDefenseView";
import type { SpellDurationView } from "./SpellDurationView";
import type { SpellHeighteningView } from "./SpellHeighteningView";
import type { SpellResolvedFieldView } from "./SpellResolvedFieldView";
import type { SpellRuleView } from "./SpellRuleView";
import type { SpellTargetingView } from "./SpellTargetingView";

export type SpellResolvedDefinitionView = { applied_fixed_ranks: Array<number>, classification: SpellResolvedFieldView<SpellClassificationView>, casting: SpellResolvedFieldView<SpellCastingView>, targeting: SpellResolvedFieldView<SpellTargetingView>, defense: SpellResolvedFieldView<SpellDefenseView>, damage: SpellResolvedFieldView<Array<SpellDamageView>>, duration: SpellResolvedFieldView<SpellDurationView>, heightening: SpellResolvedFieldView<SpellHeighteningView>, rules: SpellResolvedFieldView<Array<SpellRuleView>>, };
