// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellPatchView } from "./SpellPatchView";
import type { SpellSourceValueView } from "./SpellSourceValueView";

export type SpellFixedHeighteningView = { order: number, rank: SpellSourceValueView<number>, patch: SpellPatchView, };
