// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";
import type { HeighteningDamageView } from "./HeighteningDamageView";
import type { NumberFactView } from "./NumberFactView";
import type { SpellFixedLevelView } from "./SpellFixedLevelView";

export type SpellHeighteningChangeView = { kind: FactView<string>, interval: NumberFactView, area: NumberFactView, damage: FactView<Array<HeighteningDamageView>>, levels: FactView<Array<SpellFixedLevelView>>, };
