// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellSaveView } from "./SpellSaveView";

export type SpellDefenseView = { passive: SpellFactView<string>, save: SpellFactView<SpellSaveView>, };
