// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFormKindView } from "./SpellFormKindView";

export type SpellFormView = { id: string, label: string, order: number, minimum_cast_rank: number, kind: SpellFormKindView, };
