// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellRulePredicateView } from "./SpellRulePredicateView";

export type SpellDamageDiceRuleView = { selector: SpellFactView<string>, predicate: SpellFactView<Array<SpellRulePredicateView>>, dice_number: SpellFactView<string>, die_size: SpellFactView<string>, damage_type: SpellFactView<string>, hide_if_disabled: SpellFactView<boolean>, };
