// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellTextPatchMemberView } from "./SpellTextPatchMemberView";

export type SpellTextPatchSetView = { members: Array<SpellTextPatchMemberView>, };
