// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellDamageAlterationRuleView } from "./SpellDamageAlterationRuleView";
import type { SpellDamageDiceRuleView } from "./SpellDamageDiceRuleView";
import type { SpellEphemeralEffectRuleView } from "./SpellEphemeralEffectRuleView";
import type { SpellItemAlterationRuleView } from "./SpellItemAlterationRuleView";
import type { SpellRollOptionRuleView } from "./SpellRollOptionRuleView";

export type SpellRuleDetailView = { "kind": "damage_dice", "value": SpellDamageDiceRuleView } | { "kind": "ephemeral_effect", "value": SpellEphemeralEffectRuleView } | { "kind": "damage_alteration", "value": SpellDamageAlterationRuleView } | { "kind": "roll_option", "value": SpellRollOptionRuleView } | { "kind": "item_alteration", "value": SpellItemAlterationRuleView } | { "kind": "unsupported" };
