// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFixedHeighteningChangeView } from "./SpellFixedHeighteningChangeView";
import type { SpellSourceValueView } from "./SpellSourceValueView";

export type SpellFixedHeighteningView = { rank: SpellSourceValueView<number>, changes: Array<SpellFixedHeighteningChangeView>, };
