// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellDamagePatchOperationView } from "./SpellDamagePatchOperationView";

export type SpellDamagePatchMemberView = { key: string, order: number, operation: SpellDamagePatchOperationView, };
