// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentView } from "./CreatureSurfaceContentView";
import type { SpellEffectiveFormView } from "./SpellEffectiveFormView";
import type { SpellFamilyView } from "./SpellFamilyView";
import type { SpellFormCatalogUnavailableReasonView } from "./SpellFormCatalogUnavailableReasonView";
import type { SpellFormView } from "./SpellFormView";

export type SpellSurfaceView = { family: SpellFamilyView, forms: Array<SpellFormView>, effective_form: SpellEffectiveFormView, form_catalog_unavailable?: SpellFormCatalogUnavailableReasonView, content?: Array<CreatureSurfaceContentView>, };
