// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFormSelectionUnavailableReasonView } from "./SpellFormSelectionUnavailableReasonView";
import type { SpellResolvedDefinitionView } from "./SpellResolvedDefinitionView";

export type SpellFormResultView = { "state": "available", definition: SpellResolvedDefinitionView, } | { "state": "unavailable", reason: SpellFormSelectionUnavailableReasonView, };
