// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpellFormFieldUnavailableReasonView = "unsupported_patch" | "duplicate_key" | "incompatible_heightening" | "unknown_fixed_rank" | "fixed_rank_key_mismatch" | "invalid_interval" | "interval_member_unavailable" | "interval_formula_unsupported" | "interval_overflow";
