// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";

export type SpellEffectChangeView = { formula: SpellFactView<string>, damage_type: SpellFactView<string>, category: SpellFactView<string>, kinds: SpellFactView<Array<string>>, materials: SpellFactView<Array<string>>, apply_modifier: SpellFactView<boolean>, };
