// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellDamagePatchView } from "./SpellDamagePatchView";

export type SpellDamagePatchOperationView = { "operation": "merge", "value": SpellDamagePatchView } | { "operation": "delete" } | { "operation": "unsupported" };
