// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceActionCostView } from "./CreatureSurfaceActionCostView";
import type { SpellFactView } from "./SpellFactView";

export type SpellCastingView = { action_cost?: CreatureSurfaceActionCostView, time: SpellFactView<string>, cost: SpellFactView<string>, requirements: SpellFactView<string>, counteraction: SpellFactView<boolean>, };
