// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";
import type { SpellRulePredicateView } from "./SpellRulePredicateView";
import type { SpellRuleSuboptionView } from "./SpellRuleSuboptionView";

export type SpellRollOptionRuleView = { domain: SpellFactView<string>, label: SpellFactView<string>, option: SpellFactView<string>, placement: SpellFactView<string>, predicate: SpellFactView<Array<SpellRulePredicateView>>, suboptions: SpellFactView<Array<SpellRuleSuboptionView>>, toggleable: SpellFactView<boolean>, };
