// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellFactView } from "./SpellFactView";

export type SpellCastingView = { time: SpellFactView<string>, cost: SpellFactView<string>, requirements: SpellFactView<string>, counteraction: SpellFactView<boolean>, };
