// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatModifierView } from "./StatModifierView";

export type StatValueView = { target: string, label: string, base_value: bigint, adjusted_value: bigint, modifiers: Array<StatModifierView>, suppressed_modifiers: Array<StatModifierView>, };
