// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatModifierTypeView } from "./StatModifierTypeView";

export type StatModifierView = { source: string, label: string, modifier_type: StatModifierTypeView, value: bigint, };
