// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatValueView } from "./StatValueView";
import type { UnappliedEffectView } from "./UnappliedEffectView";

export type StatBlockView = { record_key: string, title: string, level?: bigint, adjusted_level?: bigint, values: Array<StatValueView>, unapplied_effects: Array<UnappliedEffectView>, };
