// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SurfaceUnavailableReasonView = "record_family_not_migrated" | "record_unavailable" | "manual_participant";
