// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceAdjustmentView } from "./SurfaceAdjustmentView";
import type { SurfaceNoteView } from "./SurfaceNoteView";
import type { SurfaceScalarView } from "./SurfaceScalarView";
import type { SurfaceValueDisplayView } from "./SurfaceValueDisplayView";

export type SurfaceValueView = { key: string, label: string, value: SurfaceScalarView, base_value?: SurfaceScalarView, adjusted: boolean, display: SurfaceValueDisplayView, adjustments?: Array<SurfaceAdjustmentView>, suppressed_adjustments?: Array<SurfaceAdjustmentView>, notes?: Array<SurfaceNoteView>, };
