// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SurfaceScalarView = { "kind": "number", "value": bigint } | { "kind": "text", "value": string } | { "kind": "formula", "value": string } | { "kind": "distance_feet", "value": bigint };
