// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SurfaceValueDisplayView = "static_number" | "signed_modifier" | "distance" | "formula" | "text";
