// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceScalarView } from "./SurfaceScalarView";

export type SurfaceAdjustmentView = { label: string, source: string, delta?: SurfaceScalarView, reason?: string, };
