// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceValueView } from "./SurfaceValueView";

export type SurfaceValueGroupView = { key: string, label: string, values: Array<SurfaceValueView>, };
