// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNavigationView } from "./RecordNavigationView";
import type { SurfaceNoteView } from "./SurfaceNoteView";
import type { SurfaceValueGroupView } from "./SurfaceValueGroupView";
import type { SurfaceValueView } from "./SurfaceValueView";

export type SurfaceActivityView = { navigation: RecordNavigationView, key: string, label: string, kind: string, usage?: string, values?: Array<SurfaceValueView>, groups?: Array<SurfaceValueGroupView>, notes?: Array<SurfaceNoteView>, };
