// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRollUnavailableView } from "./TableRollUnavailableView";

export type TableRollCapabilityView = { "state": "available", formula: string, sides: number, } | { "state": "unavailable", unavailable: TableRollUnavailableView, };
