// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableRollUnavailableReasonView = "formula_missing" | "formula_null" | "formula_unsupported" | "formula_invalid" | "results_missing" | "results_null" | "results_unsupported" | "unsupported_result" | "range_missing" | "range_null" | "range_unsupported" | "range_out_of_domain";
