// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableResultView } from "./TableResultView";
import type { TableRollUnavailableView } from "./TableRollUnavailableView";

export type TableRollView = { "state": "available", table_key: string, formula: string, total: number, outcomes: Array<TableResultView>, } | { "state": "unavailable", table_key: string, unavailable: TableRollUnavailableView, };
