// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactView } from "./FactView";
import type { NumberFactView } from "./NumberFactView";

export type TableResultPresentationView = { range: FactView<string>, weight: NumberFactView, result_type: FactView<string>, };
