// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRollSubjectView } from "./TableRollSubjectView";
import type { TableRollUnavailableReasonView } from "./TableRollUnavailableReasonView";

export type TableRollUnavailableView = { reason: TableRollUnavailableReasonView, subject: TableRollSubjectView, message: string, };
