// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8FactView } from "./H8FactView";

export type TableResultSourceMetadataView = { flags: H8FactView<string>, };
