// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H8UnsupportedChildView } from "./H8UnsupportedChildView";
import type { TableResultView } from "./TableResultView";

export type TableResultEntryView = { "entry_type": "result", result: TableResultView, } | { "entry_type": "unsupported", unsupported: H8UnsupportedChildView, };
