// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureSurfaceContentBlockView } from "./CreatureSurfaceContentBlockView";
import type { H8FactView } from "./H8FactView";
import type { H8IdentityStabilityView } from "./H8IdentityStabilityView";
import type { H8UnsupportedFieldView } from "./H8UnsupportedFieldView";
import type { TableResultRangeView } from "./TableResultRangeView";
import type { TableResultSourceMetadataView } from "./TableResultSourceMetadataView";

export type TableResultView = { locator: string, identity_stability: H8IdentityStabilityView, source_id: H8FactView<string>, source_ordinal: number, result_kind: H8FactView<string>, text: H8FactView<Array<CreatureSurfaceContentBlockView>>, collection: H8FactView<string>, document_id: H8FactView<string>, weight: H8FactView<string>, range: H8FactView<TableResultRangeView>, drawn: H8FactView<boolean>, image: H8FactView<string>, source_metadata: TableResultSourceMetadataView, unsupported_fields?: Array<H8UnsupportedFieldView>, };
