// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableRollSubjectView = { "subject_type": "table" } | { "subject_type": "result", locator: string, source_ordinal: number, };
