// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateEncounterParticipantConditionRequest = { condition_id: bigint, condition_ref?: string, name: string, value?: bigint, source_participant_key?: string, duration_rounds?: bigint, note?: string, source_note?: string, };
