// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterStatusView } from "./EncounterStatusView";

export type UpdateEncounterRequest = { encounter_key: string, slug: string, name: string, description?: string, note?: string, status: EncounterStatusView, };
