// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateSavedListRequest = { list_key: string, slug: string, name: string, description?: string, };
