// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantSideView } from "./EncounterParticipantSideView";
import type { EncounterParticipantVariantView } from "./EncounterParticipantVariantView";

export type UpdateEncounterParticipantRequest = { participant_key: string, display_name: string, side: EncounterParticipantSideView, participant_variant: EncounterParticipantVariantView, initiative?: number, max_hp?: number, current_hp?: number, temporary_hp: number, defeated: boolean, hidden: boolean, note?: string, };
