// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterParticipantSideView } from "./EncounterParticipantSideView";
import type { EncounterParticipantVariantView } from "./EncounterParticipantVariantView";

export type UpdateEncounterParticipantRequest = { hp_edit: boolean, max_hp_edit: boolean, variant_edit: boolean, use_derived_max: boolean, participant_key: string, display_name: string, side: EncounterParticipantSideView, participant_variant: EncounterParticipantVariantView, initiative?: bigint, max_hp?: bigint, current_hp?: bigint, temporary_hp: bigint, defeated: boolean, hidden: boolean, note?: string, };
