// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VariantEvidenceView = { record_key: string, naming_convention: string, qualifier: string, compatibility: string, };
