export { AFFLICTION_DERIVED_TAG_ONTOLOGY_FAMILIES, AFFLICTION_DERIVED_TAG_ONTOLOGY_TAGS } from "./affliction.js";
export { CREATURE_DERIVED_TAG_ONTOLOGY_FAMILIES, CREATURE_DERIVED_TAG_ONTOLOGY_TAGS } from "./creature.js";
export { EQUIPMENT_DERIVED_TAG_ONTOLOGY_FAMILIES, EQUIPMENT_DERIVED_TAG_ONTOLOGY_TAGS } from "./equipment.js";
export { HAZARD_DERIVED_TAG_ONTOLOGY_FAMILIES, HAZARD_DERIVED_TAG_ONTOLOGY_TAGS } from "./hazard.js";
export { SPELL_DERIVED_TAG_ONTOLOGY_FAMILIES, SPELL_DERIVED_TAG_ONTOLOGY_TAGS } from "./spell.js";
