import { buildProjectionRecord, type CanonicalProjectionSeed } from "../builders.js";
import { CANONICAL_VOCABULARY } from "../vocabulary.js";

const AFFLICTION_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS: Record<string, CanonicalProjectionSeed> = {
  action_denial: {
    adjacentTags: [
      "mobility_impairment",
      "sedation",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because victims become unable to act, respond, or complete normal turns through paralysis, shutdown, or severe stupor.",
      "Operational lockout matters more than ordinary weakness, pain, or mood distortion.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "action_denial",
    description: "Prevents normal action-taking through paralysis, stupefying shutdown, or similarly severe operational lockout.",
    doesNotApplyWhen: [
      "The affliction only slows, weakens, or frightens the victim without truly preventing action-taking.",
      "The stronger fit is mobility_impairment, sedation, or mental_impairment rather than hard action denial.",
    ],
    family: "impact",
  },
  antidote_resolution: {
    adjacentTags: [
      "countermagic_resolution",
      "cure_clock_urgency",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "poison_remediation",
    description: "Naturally retrieved because antitoxins, antidotes, neutralizing medicine, or poison-specific treatment are central to solving it.",
    family: "resolution_profile",
  },
  bestial_transformation: {
    adjacentTags: [
      "transformative_corruption",
      "violence_compulsion",
    ],
    appliesWhen: [
      "The affliction's retrieval value comes from becoming feral, animalistic, lycanthropic, or beast-shaped over time.",
      "Behavioral and bodily slide toward a beast identity are both salient.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "bestial_transformation",
    description: "Defined by animalistic mutation, feral reshaping, or a cursed slide into beastlike behavior and form.",
    doesNotApplyWhen: [
      "The transformation is general corruption without a real animalistic or feral endpoint.",
      "The affliction only compels violent behavior without reshaping the victim's form or identity.",
    ],
    family: "pathogenesis",
  },
  blood_rot: {
    adjacentTags: [
      "hemorrhagic_failure",
      "physical_debilitation",
    ],
    appliesWhen: [
      "Corrupted blood, blackened veins, or bloodstream collapse is the core thematic identity of the affliction.",
      "A user would retrieve it for blood-plague, hemorrhagic corruption, or vein-darkening disease imagery.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "blood_rot",
    description: "Defined by corrupted blood, blackened veins, hemorrhagic poisoning, or other blood-borne bodily collapse.",
    doesNotApplyWhen: [
      "The affliction only causes bleeding as one symptom without a real blood-corruption identity.",
      "The stronger fit is hemorrhagic_failure because the focus is immediate bleeding outcome rather than disease theme.",
    ],
    family: "pathogenesis",
  },
  carrier_vector: {
    adjacentTags: [
      "injury_exposure",
      "waterborne_exposure",
    ],
    appliesWhen: [
      "The affliction's spread is materially tied to rats, mosquitoes, parasites, infected animals, or other living carriers.",
      "Tracing or controlling the living vector is central to understanding the disease.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "carrier_vector",
    description: "Spread through vermin, insects, bites, stings, or other living disease vectors.",
    doesNotApplyWhen: [
      "The disease spreads through air, water, dreams, or contaminated objects without a real living carrier.",
      "Injury transmission happens, but the record does not frame a recurring vector population or host species.",
    ],
    family: "epidemiological_profile",
  },
  cognitive_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "cognitive_impairment",
    description: "Dulls thought, memory, decision-making, or mental clarity without being just fear or confusion.",
    family: "impact",
  },
  community_outbreak: {
    adjacentTags: [
      "epidemic_pestilence",
      "carrier_vector",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved as a spreading local crisis affecting a community, camp, ship, or institution.",
      "Outbreak management, quarantine pressure, or multi-victim spread matters more than a single infected host.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "community_outbreak",
    description: "Framed around camp-, village-, ship-, monastery-, or settlement-scale spread rather than one isolated victim.",
    doesNotApplyWhen: [
      "The affliction remains a one-target curse or isolated infection without wider spread framing.",
      "The stronger fit is epidemic_pestilence only because of plague flavor, but community-scale spread is not actually present.",
    ],
    family: "epidemiological_profile",
  },
  compulsion: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "behavior",
    conceptId: "compulsion",
    description: "Overrides agency through commanded behavior, forced truth-telling, or similarly scripted actions.",
    family: "behavioral_override",
  },
  contact_exposure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "contact_exposure",
    description: "Spread by touch, skin contact, slime, ooze, or another surface-level transfer mechanism.",
    family: "delivery_profile",
  },
  countermagic_resolution: {
    adjacentTags: [
      "antidote_resolution",
      "cursebreaking_resolution",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "active_magic_counteraction",
    description: "Naturally retrieved because counteracting, suppressing, or dispelling an active magical affliction is central to solving it.",
    family: "resolution_profile",
    label: "countermagic",
  },
  cumulative_transformation: {
    adjacentTags: [
      "transformative_corruption",
      "petrifying_corruption",
    ],
    appliesWhen: [
      "The stage-by-stage march toward a changed body is a major reason to retrieve the affliction.",
      "Transformation is progressive and cumulative rather than an instantaneous one-step effect.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "cumulative_transformation",
    description: "Affliction whose stages progressively rewrite the victim into a visibly altered or corrupted form.",
    doesNotApplyWhen: [
      "The affliction only imposes one stable transformed state without escalation.",
      "The stronger fit is delayed_onset, terminal_collapse, or a more specific pathogenesis tag.",
    ],
    family: "progression_profile",
  },
  cure_clock_urgency: {
    adjacentTags: [
      "terminal_collapse",
      "delayed_onset",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "time_critical_resolution",
    description: "Creates immediate pressure to diagnose and cure the affliction before a fast-moving catastrophic endpoint arrives.",
    family: "response_profile",
  },
  curse_marking: {
    adjacentTags: [
      "void_soul_corruption",
      "soul_binding",
    ],
    appliesWhen: [
      "The affliction leaves an explicit mark, sign, sigil, stain, or named curse-brand that matters to its identity.",
      "A user would retrieve it for visible or narratively explicit cursed marking, not just soul damage.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "metaphysical",
    conceptId: "curse_marking",
    description: "Brands the victim with a curse mark, doom sign, inherited hex, or similarly explicit supernatural stigma.",
    doesNotApplyWhen: [
      "The affliction is metaphysical but has no distinct branded or marked stigma.",
      "The stronger fit is void_soul_corruption or soul_binding without a visible curse sign.",
    ],
    family: "metaphysical_profile",
  },
  cursebreaking_resolution: {
    adjacentTags: [
      "countermagic_resolution",
      "ritual_appeasement_resolution",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "curse_remediation",
    description: "Naturally retrieved because lifting a curse, breaking a doom, or ending a supernatural binding is central to recovery.",
    family: "resolution_profile",
  },
  delayed_onset: {
    adjacentTags: [
      "recurrent_flare",
      "cumulative_transformation",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because the real danger appears after an incubation period, hidden delay, or deceptively quiet initial stage.",
      "The timing gap between exposure and serious consequence matters to prep, diagnosis, or quarantine decisions.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "delayed_onset",
    description: "Affliction whose symptoms, danger, or full transformation emerge after a notable delay rather than immediately.",
    doesNotApplyWhen: [
      "The affliction starts harming victims right away even if it worsens later.",
      "The stronger fit is recurrent_flare or cumulative_transformation because the main hook is cycling or progressive change rather than delayed emergence.",
    ],
    family: "progression_profile",
  },
  dreamborne_exposure: {
    adjacentTags: [
      "nightmare_torment",
      "inhaled_exposure",
    ],
    appliesWhen: [
      "The affliction is contracted or transmitted through dreams, sleep, shared nightmares, or oneiric contact.",
      "Dream-state exposure is central to how the condition reaches the victim.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "dreamborne_exposure",
    description: "Spread through sleep, nightmares, dreaming contact, or other oneiric pathways.",
    doesNotApplyWhen: [
      "The affliction only causes nightmares after infection but is actually spread by wounds, air, or cursed objects.",
      "The stronger fit is nightmare_torment because the symptom profile matters more than the exposure path.",
    ],
    family: "delivery_profile",
  },
  epidemic_pestilence: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "epidemic_pestilence",
    description: "A named plague-, fever-, pox-, or pestilence-style disease with explicit outbreak or contagion framing.",
    family: "epidemiological_profile",
  },
  exorcism_resolution: {
    adjacentTags: [
      "cursebreaking_resolution",
      "ritual_appeasement_resolution",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "hostile_presence_expulsion",
    description: "Naturally retrieved because banishing, cleansing, or spiritually expelling a hostile presence is central to solving the affliction.",
    family: "resolution_profile",
    label: "exorcism",
  },
  fungal_growth: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "fungal_growth",
    description: "Defined by fungal bloom, spores, mycelial takeover, or mushroom-like growths spreading through the body.",
    family: "pathogenesis",
  },
  healing_suppression: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "healing_suppression",
    description: "Prevents normal healing or sharply reduces healing received.",
    family: "impact",
  },
  hemorrhagic_failure: {
    adjacentTags: [
      "blood_rot",
      "physical_debilitation",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because bleeding, blood loss, ruptured vessels, or circulatory collapse are major consequences rather than incidental symptoms.",
      "The bodily failure pattern matters more than the source theme of the disease.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "hemorrhagic_failure",
    description: "Causes uncontrolled bleeding, blood loss, vessel rupture, or similar collapse of the body's circulatory integrity.",
    doesNotApplyWhen: [
      "The affliction only references corrupted blood as flavor without major bleeding or circulatory breakdown consequences.",
      "The stronger fit is blood_rot or physical_debilitation because hemorrhage is not the core downstream effect.",
    ],
    family: "physiology_override",
  },
  infestation_implant: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "infestation_implant",
    description: "Defined by eggs, larvae, spores, parasites, or other host-colonizing implantation.",
    family: "pathogenesis",
  },
  ingested_exposure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "ingested_exposure",
    description: "Spread by swallowing contaminated food, drink, medicine, or another consumed substance.",
    family: "delivery_profile",
  },
  inhaled_exposure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "inhaled_exposure",
    description: "Spread through smoke, breath, spores, vapor, dust, or another inhaled medium.",
    family: "delivery_profile",
  },
  injury_exposure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "injury_exposure",
    description: "Spread through bites, stings, punctures, or other blood-entering injury vectors.",
    family: "delivery_profile",
  },
  mental_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mental_impairment",
    description: "Impairs judgment, emotions, or perception through confusion, fear, or delirium.",
    family: "impact",
  },
  mobility_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mobility_impairment",
    description: "Reduces speed, stiffens movement, or leaves the victim immobilized.",
    family: "impact",
  },
  nightmare_torment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "metaphysical",
    conceptId: "nightmare_torment",
    description: "Centers on nightmares, dream-torment, or similarly sleep-haunting affliction framing.",
    family: "metaphysical_profile",
  },
  outbreak_management: {
    adjacentTags: [
      "community_outbreak",
      "quarantine_risk",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "outbreak_containment",
    description: "Naturally retrieved as a disease or curse that creates a wider containment, treatment, and community-management problem rather than only an isolated victim.",
    family: "response_profile",
  },
  petrification: {
    adjacentTags: [
      "petrifying_corruption",
      "mobility_impairment",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because victims end up petrified, stone-locked, or mineralized.",
      "The end-state of stony immobilization matters more than the thematic cause.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "petrification",
    description: "Turns flesh to stone or otherwise locks the body into a rigid mineralized state.",
    doesNotApplyWhen: [
      "The affliction only trends toward calcification without actually functioning as a petrifying condition.",
      "The stronger fit is petrifying_corruption because the gradual corruption process is the real hook.",
    ],
    family: "physiology_override",
  },
  petrifying_corruption: {
    adjacentTags: [
      "petrification",
      "cumulative_transformation",
    ],
    appliesWhen: [
      "The affliction is retrieved for gradual hardening, calcification, or stoneward corruption across stages.",
      "The process of becoming stone-like matters as much as the final condition.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "petrifying_corruption",
    description: "Defined by calcification, ossification, stone-turning, or gradual bodily hardening toward an inert form.",
    doesNotApplyWhen: [
      "The affliction chiefly imposes a final petrified state without broader progressive corruption framing.",
      "The stronger fit is transformative_corruption without specifically stoneward identity.",
    ],
    family: "pathogenesis",
  },
  physical_debilitation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "physical_debilitation",
    description: "Weakens the body through exhaustion, sickness, drained vitality, blood loss, or similar bodily degradation.",
    family: "impact",
  },
  possession_seed: {
    adjacentTags: [
      "compulsion",
      "soul_binding",
    ],
    appliesWhen: [
      "The affliction prepares a victim to be ridden, entered, replaced, or overtaken by another presence.",
      "A latent invading spirit or takeover-ready foothold is central to the condition's danger.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "metaphysical",
    conceptId: "possession_seed",
    description: "Plants an invading spirit, hostile presence, or takeover-ready metaphysical foothold inside the victim.",
    doesNotApplyWhen: [
      "The affliction only compels behavior without an actual possessing entity or metaphysical foothold.",
      "The stronger fit is soul_binding or compulsion because takeover is not really part of the disease model.",
    ],
    family: "metaphysical_profile",
  },
  quarantine_containment_resolution: {
    adjacentTags: [
      "outbreak_management",
      "quarantine_risk",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "outbreak_containment",
    description: "Naturally retrieved because isolation, contact control, and containment are core to preventing further spread while treatment proceeds.",
    family: "resolution_profile",
  },
  quarantine_risk: {
    adjacentTags: [
      "community_outbreak",
      "inhaled_exposure",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "outbreak_containment",
    description: "Creates a strong need to isolate victims, restrict contact, or manage who can safely enter or leave an affected area.",
    family: "response_profile",
  },
  recurrent_flare: {
    adjacentTags: [
      "delayed_onset",
      "terminal_collapse",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because symptoms repeatedly subside and then surge back in cycles, attacks, or flare-ups.",
      "Its pacing matters as a recurring problem rather than a single steady decline.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "recurrent_flare",
    description: "Affliction that subsides and returns in episodes, repeating attacks, or cyclical symptom spikes.",
    doesNotApplyWhen: [
      "The affliction mainly incubates once and then worsens in a straight line.",
      "The stronger fit is delayed_onset or terminal_collapse because recurrence is not the main progression hook.",
    ],
    family: "progression_profile",
  },
  respiratory_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "respiratory_impairment",
    description: "Prevents normal breathing or fills the victim's lungs with water, fluid, or similar suffocating effects.",
    family: "physiology_override",
  },
  ritual_appeasement_resolution: {
    adjacentTags: [
      "cursebreaking_resolution",
      "exorcism_resolution",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "ritual_appeasement",
    description: "Naturally retrieved because restitution, offerings, ritual respect, or meeting a spiritual demand is central to ending the affliction.",
    family: "resolution_profile",
  },
  rot_decay: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "disease_model",
    conceptId: "rot_decay",
    description: "Defined by bodily rot, necrosis, blight, mummification, or similar physical decay.",
    family: "pathogenesis",
  },
  sedation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "sedation",
    description: "Induces sleep, deep drowsiness, trance-like unconsciousness, or difficulty waking.",
    family: "impact",
  },
  self_destructive_impulse: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "behavior",
    conceptId: "self_destructive_impulse",
    description: "Drives reckless self-harm, suicidal behavior, or dangerous compulsions against the victim's own interests.",
    family: "behavioral_override",
  },
  sensory_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "sensory_impairment",
    description: "Blinds, deafens, or otherwise suppresses perception and the senses.",
    family: "impact",
  },
  soul_binding: {
    adjacentTags: [
      "curse_marking",
      "possession_seed",
    ],
    appliesWhen: [
      "The affliction's metaphysical identity depends on the victim's soul being anchored, trapped, pledged, or externally entangled.",
      "A user would retrieve it for ghost anchors, cursed bindings, oath-linked doom, or similar soul-tether effects.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "metaphysical",
    conceptId: "soul_binding",
    description: "Pins, traps, anchors, or otherwise entangles the victim's soul with an object, oath, place, or hostile power.",
    doesNotApplyWhen: [
      "The affliction only marks, weakens, or spiritually corrupts the victim without actually binding the soul to something.",
      "The stronger fit is curse_marking or possession_seed rather than tethering or anchoring.",
    ],
    family: "metaphysical_profile",
  },
  source_cleanup_resolution: {
    adjacentTags: [
      "source_tracing",
      "quarantine_containment_resolution",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "source_cleanup",
    description: "Naturally retrieved because the contaminated site, cursed source, infected carrier chain, or environmental origin must be found and cleaned up.",
    family: "resolution_profile",
  },
  source_tracing: {
    adjacentTags: [
      "carrier_vector",
      "community_outbreak",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "source_discovery",
    description: "Naturally retrieved because finding the contaminated source, carrier chain, cursed origin, or initial spread event is central to solving the problem.",
    family: "response_profile",
  },
  surgical_extraction_resolution: {
    adjacentTags: [
      "source_cleanup_resolution",
      "infestation_implant",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "response",
    conceptId: "parasite_removal",
    description: "Naturally retrieved because removing eggs, larvae, parasites, implants, or invasive growth from the body is a central answer path.",
    family: "resolution_profile",
  },
  terminal_collapse: {
    adjacentTags: [
      "cumulative_transformation",
      "physical_debilitation",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because the later stages end in death, total ruin, or another catastrophic final break point.",
      "The inevitability of a terminal end state matters more than day-to-day impairment or transformation imagery.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "terminal_collapse",
    description: "Affliction explicitly framed around catastrophic bodily failure, death, or a final ruinous end state if unchecked.",
    doesNotApplyWhen: [
      "The affliction is dangerous but does not build toward a distinct catastrophic endpoint.",
      "The stronger fit is cumulative_transformation or physical_debilitation because ongoing deterioration matters more than terminal collapse.",
    ],
    family: "progression_profile",
  },
  transformative_corruption: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "transformative_corruption",
    description: "Progressively transforms the body into crystal, plant matter, fungus, or another corrupted form.",
    family: "physiology_override",
  },
  truth_compulsion: {
    adjacentTags: [
      "compulsion",
      "self_destructive_impulse",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because victims are forced to confess, answer honestly, or reveal hidden information.",
      "Involuntary disclosure matters more than broad obedience, mood change, or self-harm.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "behavior",
    conceptId: "truth_compulsion",
    description: "Forces confession, honesty, or involuntary revelation against the victim's will.",
    doesNotApplyWhen: [
      "The affliction only compels action or speech generally without a truth-telling or confession-facing hook.",
      "The stronger fit is compulsion or cognitive_impairment rather than forced honesty.",
    ],
    family: "behavioral_override",
  },
  violence_compulsion: {
    adjacentTags: [
      "compulsion",
      "self_destructive_impulse",
    ],
    appliesWhen: [
      "The affliction is naturally retrieved because it drives victims to attack, maul, murder, or lash out at others.",
      "Violent outward aggression matters more than truthful speech, self-harm, or generic loss of agency.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "behavior",
    conceptId: "violence_compulsion",
    description: "Forces hostile aggression, murderous rage, or other attack-driven loss of self-control.",
    doesNotApplyWhen: [
      "The affliction only makes the victim reckless, confused, or generally compelled without a real violence-forward pattern.",
      "The stronger fit is self_destructive_impulse or compulsion because aggression toward others is not central.",
    ],
    family: "behavioral_override",
  },
  void_soul_corruption: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "metaphysical",
    conceptId: "void_soul_corruption",
    description: "Attacks life force or the bond between body and soul through void or deathly corruption.",
    family: "metaphysical_profile",
  },
  wasting_hunger: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "wasting_hunger",
    description: "Imposes unnatural starvation, ravenous craving, or a consuming metabolic drive that degrades the body over time.",
    family: "physiology_override",
  },
  waterborne_exposure: {
    adjacentTags: [
      "ingested_exposure",
      "carrier_vector",
    ],
    appliesWhen: [
      "Contaminated water, immersion, flood contact, or cursed liquid exposure is central to how victims contract the affliction.",
      "A user would retrieve it for tainted wells, river contagion, drowning curses, or similar water-linked spread.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "disease_model",
    conceptId: "waterborne_exposure",
    description: "Spread through tainted water, drowning contact, flood exposure, or cursed immersion.",
    doesNotApplyWhen: [
      "The affliction merely affects aquatic creatures without actually spreading through water contact.",
      "The stronger fit is inhaled_exposure, ingested_exposure, or carrier_vector instead of water-linked transmission.",
    ],
    family: "delivery_profile",
  },
};

export const AFFLICTION_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG = buildProjectionRecord(
  CANONICAL_VOCABULARY.CATEGORY.AFFLICTION,
  AFFLICTION_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS,
);
