import { buildProjectionRecord, type CanonicalProjectionSeed } from "../builders.js";
import { CANONICAL_VOCABULARY } from "../vocabulary.js";

const EQUIPMENT_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS: Record<string, CanonicalProjectionSeed> = {
  action_economy_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "action_economy_support",
    description: "Especially valuable because it compresses setup, speeds access, or meaningfully improves in-combat action efficiency.",
    family: "play_pattern",
  },
  alarm: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "alarm",
    description: "Alerts you or others when a watched area, threshold, or device is triggered.",
    family: "security",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  alchemical_crafting: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "alchemical_crafting",
    description: "Supports alchemical preparation, formula work, reagent handling, or crafting-related field setup.",
    family: "crafting_support",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ally_cover: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "ally_cover",
    description: "Provides cover or upgraded cover to nearby allies.",
    family: "defense_profile",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "shield",
    ],
  },
  ally_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "ally_support",
    description: "Support consumable that can directly benefit another creature.",
    family: "consumable_role",
    subcategories: [
      "consumable",
    ],
  },
  ammo_management: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "ammo_management",
    description: "Magazines or related gear that manage repeating-weapon ammunition or reload workflow.",
    family: "access_system",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "ammo",
      "armor",
      "weapon",
    ],
  },
  anti_bleed: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "bleed_remediation",
    description: "Helps staunch bleeding, end persistent bleed damage, or close ongoing wounds.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_caster_disruption: {
    adjacentTags: [
      "silencing",
      "countermagic",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "caster_disruption_remediation",
    description: "Punishes casting, disrupts concentration, or is naturally retrieved to make enemy spell use unreliable.",
    family: "offensive_profile",
    subcategories: [
      "ammo",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_confusion: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "confusion_remediation",
    description: "Helps clear confusion, restore mental steadiness, or recover from disordered thinking.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_disease: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "disease_remediation",
    description: "Helps resist, prevent, or recover from disease.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_fear: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "fear_remediation",
    description: "Helps resist fear, recover from frightened effects, or steady courage.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_paralysis: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "paralysis_remediation",
    description: "Helps break paralysis, restore movement, or free a creature from immobilizing body shutdown.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_petrification: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "petrification_remediation",
    description: "Helps prevent or reverse petrification and other stone-turning effects.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_poison: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "poison_remediation",
    description: "Helps resist, prevent, or recover from poison.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  anti_tracking: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "anti_tracking",
    description: "Helps hide your trail, mask scent, or make pursuit harder.",
    family: "reconnaissance",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  aquatic_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "aquatic_support",
    description: "Helps with swimming, underwater breathing, flotation, water-surface travel, or watercraft use.",
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  barrier_breaking: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "barrier_breaking",
    description: "Designed to tear through walls, barricades, ice, webs, or other physical obstructions.",
    family: "breaching",
    subcategories: [
      "gear",
      "kit",
      "consumable",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  barrier_bypass: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "barrier_bypass",
    description: "Helps get through barred windows, grates, force screens, or other blocked passage without relying on brute-force breaching.",
    family: "access_bypass",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  breaching: {
    adjacentTags: [
      "door_breaching",
      "barrier_breaking",
      "demolition",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "door_breaching",
      "barrier_breaking",
      "excavation",
      "siege_support",
      "demolition",
    ],
    conceptId: "breaching",
    description: "Broad force-entry umbrella for equipment used to break doors, barriers, fortifications, or route-blocking structures.",
    family: "breaching",
    subcategories: [
      "gear",
      "kit",
      "consumable",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  buff_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "buff_support",
    description: "Provides a general beneficial enhancement or bonus.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  burst_damage: {
    adjacentTags: [
      "crowd_clearing",
      "persistent_damage",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "burst_damage",
    description: "Delivers a front-loaded blast, detonation, or splash pattern that users naturally retrieve as immediate damage.",
    family: "offensive_profile",
    subcategories: [
      "ammo",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  camp_setup: {
    adjacentTags: [
      "sustenance",
      "carry_support",
    ],
    appliesWhen: [
      "The item is naturally retrieved for making camp, resting outdoors, or supporting expedition downtime.",
      "Its value is in field habitation rather than only carrying gear or feeding travelers.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "camp_setup",
    description: "Supports campsite creation, resting infrastructure, shelter setup, or extended overland staging.",
    doesNotApplyWhen: [
      "The item only provides sustenance, mobility, or transport without campsite infrastructure.",
      "The item is merely general survival gear with no setup or shelter-facing role.",
    ],
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  carry_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "carry_support",
    description: "Helps stow, carry, or organize equipment.",
    family: "carry_logistics",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  caster_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "caster_support",
    description: "Especially valuable to spellcasters for magical prep, casting reliability, spell defense, or spell-adjacent utility.",
    family: "party_role",
  },
  climbing: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "climbing",
    description: "Helps climb, rappel, or navigate vertical obstacles.",
    family: "movement_traversal",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  combat_maneuver_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "combat_maneuver_support",
    description: "Especially valuable to builds that rely on grappling, tripping, shoving, disarming, or other combat maneuvers to control enemies.",
    family: "play_pattern",
  },
  communication: {
    adjacentTags: [
      "signaling",
      "telepathic_communication",
      "message_delivery",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "signaling",
      "telepathic_communication",
      "message_delivery",
      "translation_support",
    ],
    conceptId: "communication",
    description: "Broad communication umbrella for equipment used to signal allies, relay messages, bridge language barriers, or coordinate silently.",
    family: "communication",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  companion_handling_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "companion_handling_support",
    description: "Especially valuable when a character's tactical workflow depends on commanding, outfitting, transporting, or protecting companions and mounts.",
    family: "play_pattern",
  },
  companion_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "companion_support",
    description: "Especially valuable to handlers of animal companions, mounts, familiars, or other creature-side support play patterns.",
    family: "party_role",
  },
  concealable: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "concealable",
    description: "Easy to hide on the person or carry discreetly.",
    family: "infiltration",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  concealment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "concealment",
    description: "Helps obscure a creature, item, or area from sight or make it harder to perceive.",
    family: "infiltration",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  condition_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "condition_support",
    description: "Helps clear or mitigate harmful conditions.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  contact_offense: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "contact_offense",
    description: "Offensive consumable delivered through touch or skin contact.",
    family: "delivery_profile",
    subcategories: [
      "consumable",
    ],
  },
  contamination_cleanup: {
    adjacentTags: [
      "quarantine_containment",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "contamination_cleanup",
    description: "Helps neutralize tainted residue, clean corrupted surfaces, purify contaminated supplies, or scrub a dangerous site back to safety.",
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  countermagic: {
    adjacentTags: [
      "magic_protection",
      "scrying_protection",
    ],
    appliesWhen: [
      "The item's main value is actively cancelling, suppressing, or interfering with hostile or ongoing magic.",
      "A user would retrieve it as an anti-magic tool rather than a general protective charm.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "active_magic_counteraction",
    description: "Counteracts, dispels, suppresses, or shuts down magic.",
    doesNotApplyWhen: [
      "The item only protects the wearer from magical harm without disrupting the spell itself.",
      "The item focuses on blocking surveillance or hiding information rather than broader anti-magic interference.",
    ],
    family: "anti_magic",
    label: "countermagic",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  creature_bane: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "creature_bane",
    description: "Tailored ammunition for a selected creature type or trait.",
    family: "ammunition_payload",
    subcategories: [
      "ammo",
    ],
  },
  crowd_clearing: {
    adjacentTags: [
      "burst_damage",
      "line_of_sight_control",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "crowd_clearing",
    description: "Excels at damaging clusters, swarms, or tightly packed weaker enemies rather than focusing on one target.",
    family: "offensive_profile",
    subcategories: [
      "ammo",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  curse_removal: {
    adjacentTags: [
      "sanctification",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "curse_remediation",
    description: "Helps remove, break, or counteract curses as a direct answer path rather than only easing symptoms.",
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  defender_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "defender_support",
    description: "Especially valuable to shield users, bodyguards, line-holders, or other defender-style characters.",
    family: "party_role",
  },
  demolition: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "demolition",
    description: "Designed for blasting, collapsing, or otherwise violently dismantling structures and obstacles.",
    family: "breaching",
    subcategories: [
      "gear",
      "kit",
      "consumable",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  disguise: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "disguise",
    description: "Helps alter appearance or impersonate another identity.",
    family: "infiltration",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  door_breaching: {
    adjacentTags: [
      "lock_bypass",
      "barrier_breaking",
    ],
    appliesWhen: [
      "The item's retrieval value is getting through doors, shutters, gates, or secured entry points.",
      "It solves access by force rather than by keys, stealth, or lock tools.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "door_breaching",
    description: "Helps force doors, shutters, gates, or similar entry points open by strength, impact, or destructive entry.",
    doesNotApplyWhen: [
      "The item is for larger demolition or siegework rather than point-of-entry breach.",
      "The item bypasses access quietly through locks or trickery instead of force.",
    ],
    family: "breaching",
    subcategories: [
      "gear",
      "kit",
      "consumable",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  elemental_payload: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "elemental_payload",
    description: "Ammunition that delivers an elemental or reagent-based payload on impact.",
    family: "ammunition_payload",
    subcategories: [
      "ammo",
    ],
  },
  emergency_recovery: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "emergency_recovery",
    description: "Especially valuable as a panic-button item for sudden healing, escape, stabilization, or critical condition rescue.",
    family: "party_role",
  },
  energy_resistance: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "energy_resistance",
    description: "Grants resistance against one or more energy types.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  environmental_adaptation: {
    adjacentTags: [
      "aquatic_support",
      "camp_setup",
      "hazard_shielding",
    ],
    appliesWhen: [
      "The item's retrieval value comes from surviving punishing climate, altitude, breathing hazards, immersion pressure, or similar expedition environments.",
      "It is naturally sought as environmental survival gear rather than a general defense item or campsite tool.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "environmental_adaptation",
    description: "Helps travelers endure extreme weather, thin air, smoke, pressure, or other dangerous environmental exposure.",
    doesNotApplyWhen: [
      "The item only protects against one incoming attack or hazard burst without broader travel-survival use.",
      "The item mainly creates camp infrastructure, carries provisions, or improves aquatic movement instead of adapting the user to the environment.",
    ],
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  escape_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "escape_support",
    description: "Helps flee, slip away, or break free.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  excavation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "excavation",
    description: "Helps dig, cut through earth or stone, or otherwise open a route by excavation or practical earth-moving work.",
    family: "breaching",
    subcategories: [
      "gear",
      "kit",
      "consumable",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  expedition: {
    adjacentTags: [
      "survival",
      "sustenance",
      "environmental_adaptation",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "survival",
      "mounted_support",
      "sustenance",
      "aquatic_support",
      "environmental_adaptation",
      "camp_setup",
    ],
    conceptId: "expedition",
    description: "Broad expedition umbrella for travel gear, camp support, sustainment, mounts, aquatic operations, and hostile-environment endurance.",
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  explosive_payload: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "explosive_payload",
    description: "Ammunition that detonates or scatters area damage on impact.",
    family: "ammunition_payload",
    subcategories: [
      "ammo",
    ],
  },
  extradimensional_storage: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "extradimensional_storage",
    description: "Provides bag-of-holding-style storage through extradimensional or magically expanded space.",
    family: "access_system",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "ammo",
      "armor",
      "weapon",
    ],
  },
  face_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "face_support",
    description: "Especially valuable to negotiators, deceivers, diplomats, or other socially forward characters who need influence, disguise, or presentation support.",
    family: "party_role",
  },
  fall_protection: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "fall_protection",
    description: "Reduces falling harm, cushions impact, or protects against vertical movement accidents and collapse.",
    family: "defense_profile",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "shield",
    ],
  },
  focus_magic_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "focus_magic_support",
    description: "Especially valuable to focus-spell-heavy or magic-routine-driven builds that want more reliable magical cadence and recovery.",
    family: "play_pattern",
  },
  forgery_support: {
    adjacentTags: [
      "disguise",
      "writing_recordkeeping",
    ],
    appliesWhen: [
      "The item's retrieval value comes from imitating documents, seals, credentials, or official paperwork.",
      "It supports passing administrative scrutiny rather than just changing clothing or physical appearance.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "forgery_support",
    description: "Supports document falsification, seal imitation, signature copying, or bureaucratic deception.",
    doesNotApplyWhen: [
      "The item only changes appearance or supports social disguise without document work.",
      "The item is a normal writing or archival tool with no deception-facing use.",
    ],
    family: "crafting_support",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  fortune_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "fortune_support",
    description: "Improves a creature's odds with rerolls, better-result effects, or failure rescue.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  hazard_shielding: {
    adjacentTags: [
      "projectile_defense",
      "magic_protection",
    ],
    appliesWhen: [
      "The item is naturally retrieved for surviving traps, breath weapons, alchemical blasts, or other hazardous exposure.",
      "Protection against scenes and effects matters more than only deflecting direct weapon attacks.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "hazard_shielding",
    description: "Protects against environmental hazards, area effects, or other damaging exposures.",
    doesNotApplyWhen: [
      "The item's main value is cover against arrows or weapon strikes rather than wider hazard exposure.",
      "The item mainly protects against spells specifically, making magic_protection the stronger hook.",
    ],
    family: "defense_profile",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "shield",
    ],
  },
  healer_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "healer_support",
    description: "Especially valuable to medics, battlefield healers, or builds expected to stabilize, treat, or recover allies under pressure.",
    family: "party_role",
  },
  healing_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "healing_support",
    description: "Restores hit points or provides direct healing.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  illumination: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "illumination",
    description: "Produces or improves light in dark environments.",
    family: "reconnaissance",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  infiltration: {
    adjacentTags: [
      "stealth_support",
      "disguise",
      "social_infiltration",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "stealth_support",
      "concealable",
      "disguise",
      "social_infiltration",
      "concealment",
    ],
    conceptId: "infiltration",
    description: "Broad infiltration umbrella for quiet-entry, discreet-carry, disguise, and covert-passing equipment.",
    family: "infiltration",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ingested_offense: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "ingested_offense",
    description: "Offensive consumable delivered when swallowed or consumed.",
    family: "delivery_profile",
    subcategories: [
      "consumable",
    ],
  },
  line_of_sight_control: {
    adjacentTags: [
      "sensory_impairment",
      "restraint_capture",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "line_of_sight_control",
    description: "Obscures vision, fills an area with smoke, or otherwise denies clear sight lines as the item's main offensive or tactical job.",
    family: "offensive_profile",
    subcategories: [
      "ammo",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  lock_bypass: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "lock_bypass",
    description: "Helps open locks or bypass secured entry points.",
    family: "access_bypass",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  magic_protection: {
    adjacentTags: [
      "countermagic",
      "hazard_shielding",
    ],
    appliesWhen: [
      "The item's value comes from warding the bearer against curses, spells, hostile magical conditions, or magical damage.",
      "Protection matters more than actually counteracting or suppressing the incoming magic.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "magic_protection",
    description: "Protects the user or target against hostile magical effects.",
    doesNotApplyWhen: [
      "The item mainly shuts down active magic rather than defending a wearer or target.",
      "The stronger fit is scrying_protection because surveillance denial is the specific retrieval hook.",
    ],
    family: "anti_magic",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mechanism_manipulation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "mechanism_manipulation",
    description: "Helps operate levers, latches, panels, pressure surfaces, or similar scene mechanisms from a safer or more advantageous position.",
    family: "access_bypass",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  medical_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "medical_support",
    description: "Supports first aid, diagnosis, treatment, or ongoing medical care outside direct magical healing.",
    family: "crafting_support",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mental_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mental_impairment",
    description: "Impairs thought, judgment, composure, or behavior through fear, confusion, or similar effects.",
    family: "impact",
    subcategories: [
      "ammo",
      "consumable",
    ],
  },
  mental_recovery: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mental_recovery",
    description: "Helps stabilize emotions or recover from mental conditions.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  message_delivery: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "message_delivery",
    description: "Sends, stores, or relays actual content across time or distance.",
    family: "communication",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mobility: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "mobility",
    description: "Improves movement or traversal flexibility.",
    family: "movement_traversal",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mobility_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mobility_impairment",
    description: "Impairs movement through slowing, restraining, sticking, or immobilizing effects.",
    family: "impact",
    subcategories: [
      "ammo",
      "consumable",
    ],
  },
  mounted_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "mounted_support",
    description: "Supports mounted combat, rider control, saddle use, or mount-specific loadouts.",
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  movement_traversal: {
    adjacentTags: [
      "climbing",
      "navigation",
      "transport",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "climbing",
      "mobility",
      "navigation",
      "transport",
    ],
    conceptId: "movement_traversal",
    description: "Broad movement-and-travel umbrella for equipment that solves climbing, routefinding, repositioning, or transport problems.",
    family: "movement_traversal",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  navigation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "navigation",
    description: "Helps track direction, route, or position.",
    family: "movement_traversal",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  offensive: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "offensive",
    description: "Hostile consumable primarily meant to harm or debilitate a target.",
    family: "consumable_role",
    subcategories: [
      "consumable",
    ],
  },
  persistent_damage: {
    adjacentTags: [
      "burst_damage",
      "physical_debilitation",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "persistent_damage",
    description: "Imposes ongoing damage through burning, acid, bleed, poison, or another lingering payload that keeps hurting after the initial hit.",
    family: "offensive_profile",
    subcategories: [
      "ammo",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  physical_debilitation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "physical_debilitation",
    description: "Weakens the body through drained vitality, sickness, fatigue, clumsiness, or similar bodily degradation.",
    family: "impact",
    subcategories: [
      "ammo",
      "consumable",
    ],
  },
  projectile_defense: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "projectile_defense",
    description: "Intercepts, redirects, or absorbs ranged attacks and projectiles.",
    family: "defense_profile",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "shield",
    ],
  },
  quarantine_containment: {
    adjacentTags: [
      "contamination_cleanup",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "outbreak_containment",
    description: "Helps isolate victims, secure contaminated areas, or impose practical containment procedures that stop spread while treatment proceeds.",
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ranged_striker_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "ranged_striker_support",
    description: "Especially valuable to archers, gunners, or other builds that pressure from range through repeated attacks or reload workflows.",
    family: "party_role",
  },
  reconnaissance: {
    adjacentTags: [
      "scouting",
      "tracking",
      "anti_tracking",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "scouting",
      "illumination",
      "surveillance_recording",
      "tracking",
      "anti_tracking",
    ],
    conceptId: "reconnaissance",
    description: "Broad recon umbrella for equipment used to scout, illuminate, record evidence, track targets, or frustrate pursuit.",
    family: "reconnaissance",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  reload_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "reload_support",
    description: "Especially valuable to ranged builds whose action flow depends on reloading efficiently or keeping ammunition ready.",
    family: "play_pattern",
  },
  repair_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "repair_support",
    description: "Supports item repair, patchwork, upkeep, or restoring damaged gear and structures.",
    family: "crafting_support",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  resolution: {
    adjacentTags: [
      "curse_removal",
      "ritual_appeasement",
      "source_revelation",
      "contamination_cleanup",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "curse_removal",
      "sanctification",
      "ritual_appeasement",
      "source_revelation",
      "quarantine_containment",
      "contamination_cleanup",
      "source_cleanup",
    ],
    conceptId: "problem_resolution",
    description: "Broad resolution umbrella for equipment used to break curses, sanctify places, contain spread, clean contamination, or solve a problem at its source.",
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  restraint_capture: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "restraint_capture",
    description: "Helps capture, bind, or keep a target restrained.",
    family: "restraint",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  restraint_escape: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "restraint_escape",
    description: "Helps break free from grabs, restraints, or similar immobilizing holds.",
    family: "restraint",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ritual_appeasement: {
    adjacentTags: [
      "ritual_support",
      "sanctification",
    ],
    appliesWhen: [
      "The item's retrieval value comes from helping perform offerings, appeasement rites, restitution rituals, or ceremonial observance meant to settle a supernatural grievance.",
      "It is naturally sought for placation or ritual satisfaction rather than direct cleansing, banishment, or ordinary worship.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "ritual_appeasement",
    description: "Supports offerings, restitution, funerary observance, or appeasement ceremonies used to satisfy a spirit, haunt, curse, or sacred demand without directly expelling it.",
    doesNotApplyWhen: [
      "The item only supports broad ritual process with no real appeasement, offering, or restitution-facing role.",
      "The stronger fit is sanctification or ritual_support because the item purifies generally or supports any rite rather than a placation answer path.",
    ],
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ritual_support: {
    adjacentTags: [
      "alchemical_crafting",
      "magic_protection",
    ],
    appliesWhen: [
      "The item meaningfully supports ceremonial, circle-based, offering-based, or extended-casting magic work.",
      "A user would retrieve it for magic preparation rather than ordinary crafting or adventuring gear.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "ritual_support",
    description: "Supports ritual casting, ceremonial setup, circles, offerings, or other extended magical preparation.",
    doesNotApplyWhen: [
      "The item is only generally magical without helping ritual process or setup.",
      "The item is mainly a focus of worship or symbolism rather than ritual procedure.",
    ],
    family: "crafting_support",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sanctification: {
    adjacentTags: [
      "ritual_support",
      "ritual_appeasement",
      "curse_removal",
    ],
    appliesWhen: [
      "The item's retrieval value comes from consecrating, hallowing, purifying, or spiritually cleansing a target or place.",
      "It is naturally sought as part of sacred-site cleanup, anti-haunt work, or ritual purification rather than general divine symbolism.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "sacred_taint_sanctification",
    description: "Supports hallowing, consecration, spiritual purification, or cleansing rites applied to a creature, object, or site.",
    doesNotApplyWhen: [
      "The item is only religious, ceremonial, or devotional without materially helping purification or consecration.",
      "The stronger fit is ritual_support because the item supports a broad rite rather than sanctification in particular.",
    ],
    family: "resolution",
    label: "sanctification",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  scout_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "scout_support",
    description: "Especially valuable to scouts, infiltrators, or advance-party play through quiet entry, recon, and information-gathering support.",
    family: "party_role",
  },
  scouting: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "scouting",
    description: "Helps observe, survey, or reconnoiter an area.",
    family: "reconnaissance",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  scrying_protection: {
    adjacentTags: [
      "alarm",
      "concealment",
    ],
    appliesWhen: [
      "The item's main value is preventing magical spying, remote observation, or divination-led tracking.",
      "A user would retrieve it to keep plans, rooms, or identities hidden from magical surveillance.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "scrying_protection",
    description: "Blocks magical observation, remote viewing, or information leakage through divination-like effects.",
    doesNotApplyWhen: [
      "The item only improves ordinary stealth or concealment without anti-divination protection.",
      "The item counters magic generally but is not particularly about observation or information leakage.",
    ],
    family: "security",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  security: {
    adjacentTags: [
      "alarm",
      "scrying_protection",
      "tamper_evidence",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "alarm",
      "scrying_protection",
      "tamper_evidence",
    ],
    conceptId: "security",
    description: "Broad security umbrella for gear that warns about intrusion, blocks magical spying, or reveals after-the-fact interference.",
    family: "security",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sedation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "sedation",
    description: "Induces sleep, lethargy, unconsciousness, or similar incapacitating drowsiness.",
    family: "impact",
    subcategories: [
      "ammo",
      "consumable",
    ],
  },
  self_buff: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "self_buff",
    description: "Support consumable primarily applied to the user.",
    family: "consumable_role",
    subcategories: [
      "consumable",
    ],
  },
  senses_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "senses_support",
    description: "Improves vision or other senses.",
    family: "function",
    subcategories: [
      "consumable",
    ],
  },
  sensory_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "sensory_impairment",
    description: "Impairs sight, hearing, or other senses through blinding, dazzling, or deafening effects.",
    family: "impact",
    subcategories: [
      "ammo",
      "consumable",
    ],
  },
  shield_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "shield_support",
    description: "Especially valuable to shield-forward play through improved blocking, readiness, or defensive shield workflow.",
    family: "play_pattern",
  },
  siege_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "siege_support",
    description: "Supports attacking gates, fortifications, vehicles, or other larger hardened targets.",
    family: "breaching",
    subcategories: [
      "gear",
      "kit",
      "consumable",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  signaling: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "signaling",
    description: "Helps draw attention, mark a location, or coordinate allies.",
    family: "communication",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  silencing: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "silencing",
    description: "Suppresses speech, voice, or other sound-dependent action through gagging, muting, or numbing effects.",
    family: "impact",
    subcategories: [
      "ammo",
      "consumable",
    ],
  },
  skirmisher_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "skirmisher_support",
    description: "Especially valuable to mobile flankers, hit-and-run melee characters, or other skirmisher-style builds.",
    family: "party_role",
  },
  social_infiltration: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "social_infiltration",
    description: "Helps blend into a group or pass under social scrutiny.",
    family: "infiltration",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  source_cleanup: {
    adjacentTags: [
      "source_revelation",
      "contamination_cleanup",
      "ritual_support",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "source_cleanup",
    description: "Helps find, remove, neutralize, or safely dispose of the cursed object, infected material, corrupted remains, or other source driving the problem.",
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  source_revelation: {
    adjacentTags: [
      "source_cleanup",
      "contamination_cleanup",
    ],
    appliesWhen: [
      "The item's retrieval value comes from finding or confirming the hidden source of a curse, contamination, outbreak, or spiritually tainted problem.",
      "It is naturally sought for tracing the origin or anchor rather than directly cleansing or disposing of it.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "source_discovery",
    description: "Helps identify the cursed anchor, contaminated material, infected origin, hidden carrier, or other source driving the problem before cleanup begins.",
    doesNotApplyWhen: [
      "The item only helps perform a cleanup, disposal, or purification step after the source is already known.",
      "The stronger fit is medical_support, tracking, or ritual_support because the item supports a broader process without specifically revealing the source.",
    ],
    family: "resolution",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  spell_payload: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "spell_payload",
    description: "Ammunition that delivers, casts, or imposes a spell effect on hit.",
    family: "ammunition_payload",
    subcategories: [
      "ammo",
    ],
  },
  stealth_entry_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "stealth_entry_support",
    description: "Especially valuable to quiet-entry, infiltration, burglary, or reconnaissance play that depends on avoiding notice and solving access problems discreetly.",
    family: "play_pattern",
  },
  stealth_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "stealth_support",
    description: "Helps move quietly, avoid notice, muffle noise, or otherwise support covert entry and low-profile movement.",
    family: "infiltration",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  surveillance_recording: {
    adjacentTags: [
      "scouting",
      "tamper_evidence",
    ],
    appliesWhen: [
      "The item's retrieval value comes from preserving sights, sounds, or observations for later replay, proof, or analysis.",
      "It is naturally sought as evidence capture, remote monitoring, or watch-post support rather than live conversation gear.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "surveillance_recording",
    description: "Captures, stores, or replays images, sound, or other evidence for later review.",
    doesNotApplyWhen: [
      "The item only sends a live message or helps coordinate allies without retaining evidence.",
      "The item protects against observation instead of performing it.",
    ],
    family: "reconnaissance",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  survival: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "survival",
    description: "Supports wilderness travel, shelter, or long-term field use.",
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sustenance: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "sustenance",
    description: "Provides food, feed, water, or other practical nourishment for travel and survival.",
    family: "expedition",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
      "armor",
      "shield",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  tamper_evidence: {
    adjacentTags: [
      "alarm",
      "surveillance_recording",
    ],
    appliesWhen: [
      "The item is naturally retrieved to reveal whether a lock, crate, seal, letter, cache, or room has been disturbed.",
      "Evidence of interference matters more than immediate warning, direct defense, or anti-scrying.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "tamper_evidence",
    description: "Makes intrusion, opening, theft, or interference easier to notice after the fact.",
    doesNotApplyWhen: [
      "The item mainly alerts in real time when someone crosses a boundary.",
      "The item hides or protects a target without preserving signs of intrusion.",
    ],
    family: "security",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  telepathic_communication: {
    adjacentTags: [
      "signaling",
      "message_delivery",
    ],
    appliesWhen: [
      "The item's retrieval value comes from silent psychic coordination, mind-to-mind speech, or communication that bypasses ordinary sound.",
      "It is naturally sought when stealth, silence, distance, or noise would make spoken coordination unreliable.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "telepathic_communication",
    description: "Enables silent mind-to-mind coordination, psychic speech, or communication that bypasses normal hearing.",
    doesNotApplyWhen: [
      "The item only boosts ordinary signaling, writing, or message relay without true mind-to-mind communication.",
      "The item is mainly about surveillance or recording rather than live coordination.",
    ],
    family: "communication",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  thrown_offense: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "thrown_offense",
    description: "Offensive consumable delivered by throwing it.",
    family: "delivery_profile",
    subcategories: [
      "consumable",
    ],
  },
  thrown_weapon_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "party_role",
    conceptId: "thrown_weapon_support",
    description: "Especially valuable to builds that solve problems through thrown weapons, quick draws, or repeatable thrown-item pressure.",
    family: "play_pattern",
  },
  tracking: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "tracking",
    description: "Helps follow trails, mark a target, or relocate something later.",
    family: "reconnaissance",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  translation_support: {
    adjacentTags: [
      "telepathic_communication",
      "message_delivery",
    ],
    appliesWhen: [
      "The item's retrieval value comes from understanding foreign languages, translating speech, or decoding otherwise unreadable text or symbols.",
      "It is naturally sought when communication fails because of language barriers rather than distance or secrecy.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "translation_support",
    description: "Bridges language barriers through translation, deciphering, script interpretation, or speech-understanding aids.",
    doesNotApplyWhen: [
      "The item only stores, relays, or broadcasts messages without solving comprehension.",
      "The item only provides psychic communication between already understood participants.",
    ],
    family: "communication",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  transport: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "transport",
    description: "Helps move creatures or cargo from place to place.",
    family: "movement_traversal",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  trap_bypass: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "trap_bypass",
    description: "Helps disarm, disable, or get past traps.",
    family: "access_bypass",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "armor",
      "weapon",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  weapon_applied: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "weapon_applied",
    description: "Offensive consumable applied to a weapon before use.",
    family: "delivery_profile",
    subcategories: [
      "consumable",
    ],
  },
  weapon_staging: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "item_mechanical",
    conceptId: "weapon_staging",
    description: "Holsters, sheaths, scabbards, or bandoliers that stage weapons for quick draw or organized carry.",
    family: "access_system",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "vehicle",
      "ammo",
      "armor",
      "weapon",
    ],
  },
  writing_recordkeeping: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "writing_recordkeeping",
    description: "Supports note-taking, mapmaking, copying text, archival work, or durable information storage.",
    family: "crafting_support",
    subcategories: [
      "gear",
      "backpack",
      "kit",
      "consumable",
    ],
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
};

export const EQUIPMENT_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG = buildProjectionRecord(
  CANONICAL_VOCABULARY.CATEGORY.EQUIPMENT,
  EQUIPMENT_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS,
);
