import type { CategoryProjectionFamilyDescriptor } from "../builders.js";

export const CANONICAL_PROJECTION_FAMILIES = {
  AFFLICTION: {
    BEHAVIOR_BEHAVIORAL_OVERRIDE: { category: "affliction", axis: "behavior", family: "behavioral_override" },
    DISEASE_MODEL_DELIVERY_PROFILE: { category: "affliction", axis: "disease_model", family: "delivery_profile" },
    DISEASE_MODEL_EPIDEMIOLOGICAL_PROFILE: {
      category: "affliction",
      axis: "disease_model",
      family: "epidemiological_profile",
    },
    DISEASE_MODEL_PATHOGENESIS: { category: "affliction", axis: "disease_model", family: "pathogenesis" },
    DISEASE_MODEL_PROGRESSION_PROFILE: { category: "affliction", axis: "disease_model", family: "progression_profile" },
    EFFECT_IMPACT: { category: "affliction", axis: "effect", family: "impact" },
    EFFECT_PHYSIOLOGY_OVERRIDE: { category: "affliction", axis: "effect", family: "physiology_override" },
    METAPHYSICAL_METAPHYSICAL_PROFILE: { category: "affliction", axis: "metaphysical", family: "metaphysical_profile" },
    RESPONSE_RESOLUTION_PROFILE: { category: "affliction", axis: "response", family: "resolution_profile" },
    RESPONSE_RESPONSE_PROFILE: { category: "affliction", axis: "response", family: "response_profile" },
  },
  CREATURE: {
    ENCOUNTER_COHORT_ROLE: { category: "creature", axis: "encounter", family: "cohort_role" },
    ENCOUNTER_COMBAT_ROLE: { category: "creature", axis: "encounter", family: "combat_role" },
    ENCOUNTER_THREAT_PROFILE: { category: "creature", axis: "encounter", family: "threat_profile" },
    NPC_ROLE_SCENE_ROLE: { category: "creature", axis: "npc_role", family: "scene_role" },
    NPC_ROLE_SOCIAL_ROLE: { category: "creature", axis: "npc_role", family: "social_role" },
    PRESENTATION_BOUND_OBJECT: { category: "creature", axis: "presentation", family: "bound_object" },
    PRESENTATION_GENRE_MOTIF: { category: "creature", axis: "presentation", family: "genre_motif" },
    PRESENTATION_STORY_MOTIF: { category: "creature", axis: "presentation", family: "story_motif" },
    PRESENTATION_VISUAL_MOTIF: { category: "creature", axis: "presentation", family: "visual_motif" },
    SETTING_HABITAT_SETTING: { category: "creature", axis: "setting", family: "habitat_setting" },
    SETTING_PLANAR_SETTING: { category: "creature", axis: "setting", family: "planar_setting" },
    SETTING_REGIONAL_SETTING: { category: "creature", axis: "setting", family: "regional_setting" },
    SETTING_SITE_SETTING: { category: "creature", axis: "setting", family: "site_setting" },
    SPECIALIZATION_CASTING_PROFILE: { category: "creature", axis: "specialization", family: "casting_profile" },
    SPECIALIZATION_CORRUPTION_PROFILE: { category: "creature", axis: "specialization", family: "corruption_profile" },
    SPECIALIZATION_ONTOLOGY_CLUSTER: { category: "creature", axis: "specialization", family: "ontology_cluster" },
  },
  EQUIPMENT: {
    EFFECT_CONSUMABLE_ROLE: { category: "equipment", axis: "effect", family: "consumable_role" },
    EFFECT_DELIVERY_PROFILE: { category: "equipment", axis: "effect", family: "delivery_profile" },
    EFFECT_FUNCTION: { category: "equipment", axis: "effect", family: "function" },
    EFFECT_IMPACT: { category: "equipment", axis: "effect", family: "impact" },
    EFFECT_OFFENSIVE_PROFILE: { category: "equipment", axis: "effect", family: "offensive_profile" },
    ITEM_MECHANICAL_ACCESS_SYSTEM: { category: "equipment", axis: "item_mechanical", family: "access_system" },
    ITEM_MECHANICAL_AMMUNITION_PAYLOAD: {
      category: "equipment",
      axis: "item_mechanical",
      family: "ammunition_payload",
    },
    ITEM_MECHANICAL_DEFENSE_PROFILE: { category: "equipment", axis: "item_mechanical", family: "defense_profile" },
    PARTY_ROLE_PARTY_ROLE: { category: "equipment", axis: "party_role", family: "party_role" },
    PARTY_ROLE_PLAY_PATTERN: { category: "equipment", axis: "party_role", family: "play_pattern" },
    UTILITY_ACCESS_BYPASS: { category: "equipment", axis: "utility", family: "access_bypass" },
    UTILITY_ANTI_MAGIC: { category: "equipment", axis: "utility", family: "anti_magic" },
    UTILITY_BREACHING: { category: "equipment", axis: "utility", family: "breaching" },
    UTILITY_CARRY_LOGISTICS: { category: "equipment", axis: "utility", family: "carry_logistics" },
    UTILITY_COMMUNICATION: { category: "equipment", axis: "utility", family: "communication" },
    UTILITY_CRAFTING_SUPPORT: { category: "equipment", axis: "utility", family: "crafting_support" },
    UTILITY_EXPEDITION: { category: "equipment", axis: "utility", family: "expedition" },
    UTILITY_INFILTRATION: { category: "equipment", axis: "utility", family: "infiltration" },
    UTILITY_MOVEMENT_TRAVERSAL: { category: "equipment", axis: "utility", family: "movement_traversal" },
    UTILITY_RECONNAISSANCE: { category: "equipment", axis: "utility", family: "reconnaissance" },
    UTILITY_RESOLUTION: { category: "equipment", axis: "utility", family: "resolution" },
    UTILITY_RESTRAINT: { category: "equipment", axis: "utility", family: "restraint" },
    UTILITY_SECURITY: { category: "equipment", axis: "utility", family: "security" },
  },
  HAZARD: {
    EFFECT_ATTACK_VECTOR: { category: "hazard", axis: "effect", family: "attack_vector" },
    EFFECT_ENVIRONMENTAL_DANGER: { category: "hazard", axis: "effect", family: "environmental_danger" },
    EFFECT_FORCED_POSITION: { category: "hazard", axis: "effect", family: "forced_position" },
    EFFECT_IMPACT: { category: "hazard", axis: "effect", family: "impact" },
    EFFECT_PERCEPTION_CONTROL: { category: "hazard", axis: "effect", family: "perception_control" },
    ENCOUNTER_FUNCTION: { category: "hazard", axis: "encounter", family: "function" },
    HAUNT_HAUNT_MANIFESTATION: { category: "hazard", axis: "haunt", family: "haunt_manifestation" },
    MECHANISM_MECHANISM: { category: "hazard", axis: "mechanism", family: "mechanism" },
    PROBLEM_PROBLEM_SHAPE: { category: "hazard", axis: "problem", family: "problem_shape" },
    RESOLUTION_COUNTERMEASURE_PROFILE: { category: "hazard", axis: "resolution", family: "countermeasure_profile" },
    SETTING_SETTING: { category: "hazard", axis: "setting", family: "setting" },
  },
  SPELL: {
    BATTLEFIELD_CONTROL: { category: "spell", axis: "battlefield", family: "control" },
    EFFECT_IMPACT: { category: "spell", axis: "effect", family: "impact" },
    INFLUENCE_INFLUENCE: { category: "spell", axis: "influence", family: "influence" },
    SUMMONING_SUMMONING: { category: "spell", axis: "summoning", family: "summoning" },
    SUPPORT_SUPPORT: { category: "spell", axis: "support", family: "support" },
    TRANSFORMATION_TRANSFORMATION: { category: "spell", axis: "transformation", family: "transformation" },
    UTILITY_ACCESS_BYPASS: { category: "spell", axis: "utility", family: "access_bypass" },
    UTILITY_COMMUNICATION: { category: "spell", axis: "utility", family: "communication" },
    UTILITY_CONSULTATION: { category: "spell", axis: "utility", family: "consultation" },
    UTILITY_EXPEDITION: { category: "spell", axis: "utility", family: "expedition" },
    UTILITY_INFILTRATION: { category: "spell", axis: "utility", family: "infiltration" },
    UTILITY_RECONNAISSANCE: { category: "spell", axis: "utility", family: "reconnaissance" },
    UTILITY_RESOLUTION: { category: "spell", axis: "utility", family: "resolution" },
    UTILITY_REVELATION: { category: "spell", axis: "utility", family: "revelation" },
    UTILITY_SECURITY: { category: "spell", axis: "utility", family: "security" },
    UTILITY_SENSORY_SUPPORT: { category: "spell", axis: "utility", family: "sensory_support" },
    UTILITY_TELEPORTATION: { category: "spell", axis: "utility", family: "teleportation" },
    UTILITY_WAYFINDING: { category: "spell", axis: "utility", family: "wayfinding" },
  },
} as const satisfies Record<string, Record<string, CategoryProjectionFamilyDescriptor>>;
