import { buildProjectionRecord, type CanonicalProjectionSeed } from "../builders.js";
import { CANONICAL_VOCABULARY } from "../vocabulary.js";

const HAZARD_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS: Record<string, CanonicalProjectionSeed> = {
  acid_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "acid_application",
    description: "Hazard centered on acid, corrosive spray, caustic runoff, or similar corrosive exposure.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  alarm: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "alarm",
    description: "Alerts guardians, onlookers, or nearby creatures to an intrusion.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ambush_burst: {
    adjacentTags: [
      "zone_denial",
      "attrition_pressure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved for a sudden opener, trap-spring punish, or first-contact burst that catches intruders before a longer fight develops.",
      "The surprise spike matters more than sustained zone control or prolonged attrition.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "ambush_burst",
    description: "Hazard designed to open with a sudden high-damage strike or surprise punish on first contact.",
    doesNotApplyWhen: [
      "The hazard mainly holds territory over time, guards a place persistently, or taxes resources across repeated rounds.",
      "The stronger fit is zone_denial or attrition_pressure rather than a front-loaded strike.",
    ],
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  appeasement_countermeasure: {
    adjacentTags: [
      "exorcism_countermeasure",
      "judgment_haunt",
    ],
    appliesWhen: [
      "The hazard meaningfully invites negotiation-by-ritual, restitution, reverence, or satisfying an unmet dead or sacred demand.",
      "The nonviolent spiritual answer is more central than simply disabling mechanics or dispelling magic.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "ritual_appeasement",
    description: "Hazard best resolved through offerings, ritual respect, social appeasement, or meeting a spiritual demand.",
    doesNotApplyWhen: [
      "The hazard only needs a standard disable check, counteract, or forceful destruction.",
      "The hazard is haunted but has no appeasement-style resolution path.",
    ],
    family: "countermeasure_profile",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  aquatic_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "aquatic_hazard",
    description: "Hazard strongly associated with flooded chambers, rivers, docks, ships, reefs, or underwater spaces.",
    family: "setting",
  },
  area_denial: {
    adjacentTags: [
      "zone_denial",
      "sentinel_guardian",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "area_denial",
    description: "Legacy synonym for zone_denial preserved for compatibility while downstream hazard planning surfaces migrate to the simpler area-control vocabulary.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  attrition_pressure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "attrition_pressure",
    description: "Hazard whose primary role is to wear the party down over time rather than deliver one decisive spike.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  barrier_lockdown: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "barrier_lockdown",
    description: "Hazard that seals, closes, or blocks passage to trap or delay intruders.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  battlefield_disruption: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "battlefield_disruption",
    description: "Haunt that reshapes the scene with barriers, violent manifestations, or other encounter-disrupting effects.",
    family: "haunt_manifestation",
  },
  battlefield_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "battlefield_hazard",
    description: "Hazard strongly associated with siegeworks, trenches, killing grounds, war engines, or other battlefield scenes.",
    family: "setting",
  },
  blight_hazard: {
    adjacentTags: [
      "contamination_hazard",
      "overgrowth_hazard",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "blight_application",
    description: "Hazard centered on ecological ruin, land-sickening corruption, withering growth, or terrain spoiled by supernatural blight.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  bridge_passage_hazard: {
    adjacentTags: [
      "threshold_lockdown",
      "forced_movement",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved for narrow crossings, gates, stairwells, or other spaces where intruders must pass through a constrained route.",
      "Forced-passage geometry matters more than a broader dungeon, urban, or wilderness setting identity.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "bridge_passage_hazard",
    description: "Hazard strongly associated with bridges, chokepoints, gates, stairwells, or forced passage bottlenecks.",
    doesNotApplyWhen: [
      "The hazard only happens to sit near a doorway or bridge once without the chokepoint being central to its design.",
      "The stronger fit is threshold_lockdown or forced_movement because the route bottleneck is not the main retrieval hook.",
    ],
    family: "setting",
  },
  cold_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "cold_application",
    description: "Hazard centered on ice, frost, freezing, blizzards, or other cold exposure.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  collapse_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "collapse_application",
    description: "Hazard built around collapsing structures, cave-ins, rockfalls, or crumbling ground.",
    family: "forced_position",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  contamination_cleanup_countermeasure: {
    adjacentTags: [
      "quarantine_containment_countermeasure",
      "source_cleanup_countermeasure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because cleansing tainted ground, polluted air, cursed runoff, spores, or lingering residue is a core answer path.",
      "The cleanup process matters more than only suppressing the effect temporarily or bypassing the area.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "contamination_cleanup",
    description: "Hazard best resolved through decontamination, purification, cleansing residue, or scrubbing the hazardous space back to safety.",
    doesNotApplyWhen: [
      "The hazard only has an immediate trigger or burst with no meaningful lingering contamination to clean up.",
      "The stronger fit is exorcism_countermeasure or dispel_countermeasure because the answer is purging a presence or ending an effect rather than cleaning a tainted site.",
    ],
    family: "countermeasure_profile",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  contamination_hazard: {
    adjacentTags: [
      "poison_hazard",
      "respiratory_hazard",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "contamination_application",
    description: "Hazard centered on tainted residue, corruptive seepage, drifting spores, cursed runoff, or other lingering contamination of a space.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  control_interface: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "mechanism",
    conceptId: "control_interface",
    description: "Hazard operated through a button, lever, console, panel, switch, or similar control surface.",
    family: "mechanism",
  },
  cursefield_hazard: {
    adjacentTags: [
      "contamination_hazard",
      "judgment_haunt",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "cursefield_application",
    description: "Hazard centered on cursed ground, spiritually poisoned space, or a zone whose danger comes from active supernatural contamination rather than one mechanism.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  dispel_countermeasure: {
    adjacentTags: [
      "physical_disarm",
      "ward_trigger",
    ],
    appliesWhen: [
      "A user would plausibly retrieve the hazard because anti-magic answers are central to resolving it.",
      "Magical suppression matters more than physical disarm or spiritual appeasement.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "active_magic_counteraction",
    description: "Hazard meaningfully invites counteract, dispel, or magical suppression as a core answer path.",
    doesNotApplyWhen: [
      "The hazard is magical but best solved through rituals, offerings, or physical tampering instead.",
      "Counteracting is only a minor optional answer path.",
    ],
    family: "countermeasure_profile",
    label: "countermagic",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  displacement_hazard: {
    adjacentTags: [
      "pitfall",
      "collapse_hazard",
      "forced_separation",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "effect",
    compositeOfAnyTags: [
      "pitfall",
      "collapse_hazard",
      "forced_movement",
      "forced_separation",
    ],
    conceptId: "displacement_application",
    description: "Broad displacement umbrella for hazards that drop, collapse, shove, or split creatures apart through positional disruption.",
    family: "forced_position",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  dungeon_hazard: {
    adjacentTags: [
      "tomb_hazard",
      "temple_hazard",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved as a classic corridor, chamber, or trap-complex defense in a dungeon environment.",
      "Its encounter identity is more about underground built-space adventuring than a narrower tomb or temple context.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "dungeon_hazard",
    description: "Hazard strongly associated with dungeon corridors, chambers, trapped passages, or underground complexes.",
    doesNotApplyWhen: [
      "The hazard is more specifically tomb-, temple-, bridge-, or aquatic-coded than generic dungeon-coded.",
      "The hazard merely happens to appear indoors once without dungeon-like scene identity.",
    ],
    family: "setting",
  },
  electric_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "electric_application",
    description: "Hazard centered on lightning, shock, static discharge, or electrical exposure.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  endurance_pressure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "problem",
    conceptId: "endurance_pressure",
    description: "Hazard whose main prep problem is surviving repeated exposure long enough to finish the scene rather than landing one clean solve immediately.",
    family: "problem_shape",
  },
  environmental_hazard: {
    adjacentTags: [
      "fire_hazard",
      "poison_hazard",
      "contamination_hazard",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "effect",
    compositeOfAnyTags: [
      "acid_hazard",
      "cold_hazard",
      "fire_hazard",
      "electric_hazard",
      "poison_hazard",
      "respiratory_hazard",
      "sound_hazard",
      "water_hazard",
      "contamination_hazard",
      "blight_hazard",
      "overgrowth_hazard",
      "cursefield_hazard",
    ],
    conceptId: "environmental_application",
    description: "Broad environmental umbrella for elemental, toxic, contaminating, and terrain-corrupting hazards that threaten a space through recurring exposure.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  exorcism_countermeasure: {
    adjacentTags: [
      "appeasement_countermeasure",
      "dispel_countermeasure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because cleansing, banishing, or sanctifying the hostile presence is a core answer path.",
      "A spiritual purge matters more than appeasement, anti-magic suppression, or physical mechanism work.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "hostile_presence_expulsion",
    description: "Hazard best resolved through banishment, exorcism, consecration, or another spirit-cleansing answer.",
    doesNotApplyWhen: [
      "The hazard mainly wants offerings, restitution, or ritual respect rather than expulsion.",
      "The hazard is magical or mechanical but not really spirit-cleansed out of existence.",
    ],
    family: "countermeasure_profile",
    label: "exorcism",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  false_safe_route: {
    adjacentTags: [
      "navigation_disruption",
      "procedural_bypass",
    ],
    appliesWhen: [
      "The hazard actively misdirects intruders toward a route that looks protective, faster, or safer but is actually the danger.",
      "The retrieval hook is deceptive path choice rather than only illusion damage or generic navigation confusion.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "false_safe_route",
    description: "Hazard that tempts intruders toward a seemingly safer path or escape line that is itself the trap.",
    doesNotApplyWhen: [
      "The hazard merely scrambles orientation without presenting a tempting fake safe path.",
      "The hazard is solved through procedure, but misleading route presentation is not central to how it works.",
    ],
    family: "perception_control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  fire_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "fire_application",
    description: "Hazard centered on open fire, flames, burning spread, or explosive ignition.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  floor_eruption: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "floor_eruption",
    description: "Hazard that attacks upward from the ground, floor, or a concealed underfoot chamber.",
    family: "attack_vector",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  forced_movement: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "forced_movement",
    description: "Hazard that pushes, pulls, drags, submerges, or otherwise forcibly repositions creatures.",
    family: "forced_position",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  forced_separation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "forced_separation",
    description: "Hazard that splits allies apart through walls, drops, slides, teleports, or other positional disruption.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  forced_separation_hazard: {
    adjacentTags: [
      "forced_separation",
      "pursuit_punisher",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "forced_separation_hazard",
    description: "Legacy synonym for forced_separation preserved for compatibility while downstream surfaces migrate to the simpler split-party vocabulary.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  guarding_hazard: {
    adjacentTags: [
      "alarm",
      "barrier_lockdown",
      "sentinel_guardian",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "encounter",
    compositeOfAnyTags: [
      "alarm",
      "barrier_lockdown",
      "sentinel_guardian",
    ],
    conceptId: "guarding_hazard",
    description: "Broad guarding umbrella for hazards that warn, lock down, or stand watch over a threshold, object, or protected space.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  illusion_assault: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "illusion_assault",
    description: "Hazard that attacks through deceptive reflections, phantasms, or other hostile illusion-driven distortions.",
    family: "perception_control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  judgment_haunt: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "judgment_haunt",
    description: "Haunt that condemns trespassers through accusation, punishment, curse-like verdicts, or moral reckoning.",
    family: "haunt_manifestation",
  },
  layered_resolution: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "problem",
    conceptId: "multi_stage_resolution",
    description: "Hazard that asks the party to solve multiple linked pieces rather than one single disable check or obvious answer.",
    family: "problem_shape",
  },
  life_drain_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "life_drain_hazard",
    description: "Haunt that drains life force, vitality, or souls from victims.",
    family: "haunt_manifestation",
  },
  lure_compulsion: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "lure_compulsion",
    description: "Haunt that beckons, lures, or compels creatures into moving or acting against their judgment.",
    family: "haunt_manifestation",
  },
  mental_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mental_impairment",
    description: "Impairs judgment, emotions, or perception through fear, confusion, or similar effects.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mobility_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mobility_impairment",
    description: "Paralyzes, immobilizes, or otherwise heavily hampers movement.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  navigation_disruption: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "navigation_disruption",
    description: "Hazard that confounds routes, loops intruders, or scrambles navigation through distorted perception.",
    family: "perception_control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  observation_first: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "problem",
    conceptId: "observation_driven",
    description: "Hazard that rewards careful watching, clue gathering, or reading the environment before a safe approach becomes obvious.",
    family: "problem_shape",
  },
  overgrowth_hazard: {
    adjacentTags: [
      "blight_hazard",
      "forced_movement",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "overgrowth_application",
    description: "Hazard centered on choking roots, hostile vines, grasping thorns, or other dangerous living overgrowth that turns terrain against intruders.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  overhead_strike: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "overhead_strike",
    description: "Hazard that drops, crashes, or attacks from the ceiling or another overhead position.",
    family: "attack_vector",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  perception_hazard: {
    adjacentTags: [
      "navigation_disruption",
      "illusion_assault",
      "false_safe_route",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "effect",
    compositeOfAnyTags: [
      "navigation_disruption",
      "illusion_assault",
      "false_safe_route",
    ],
    conceptId: "perception_application",
    description: "Broad perception umbrella for hazards that attack through distorted routes, hostile illusion, or deceptive pathing rather than direct force alone.",
    family: "perception_control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  phantom_assailants: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "phantom_assailants",
    description: "Haunt that manifests ghostly, spectral, or phantom attackers as separate assailants.",
    family: "haunt_manifestation",
  },
  physical_disarm: {
    adjacentTags: [
      "procedural_bypass",
      "dispel_countermeasure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because tools, hands-on disable work, or mechanism access are central to solving it.",
      "Mechanical tampering matters more than safe sequencing, anti-magic, or spiritual negotiation.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "physical_disarm",
    description: "Hazard meaningfully invites physical mechanism tampering, disassembly, or trigger-blocking as the core answer path.",
    doesNotApplyWhen: [
      "The hazard is mainly solved by learning the right pattern, dispelling an effect, or meeting a spiritual demand.",
      "Physical interaction exists only as one optional fallback rather than the main resolution mode.",
    ],
    family: "countermeasure_profile",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  pitfall: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "pitfall",
    description: "Hazard built around a concealed pit, drop, or similar vertical fall trap.",
    family: "forced_position",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  planar_breach: {
    adjacentTags: [
      "dispel_countermeasure",
      "procedural_bypass",
    ],
    appliesWhen: [
      "An unstable portal, planar tear, extradimensional rupture, or reality breach is the central mechanism of the hazard.",
      "The hazard is naturally retrieved for cosmological leakage, portal instability, or something dangerous coming through a breach.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "mechanism",
    conceptId: "planar_breach",
    description: "Hazard centered on a portal, rift, tear, breach, or other unstable opening in reality.",
    doesNotApplyWhen: [
      "The hazard is merely magical or teleportive without a real opening in reality as the core hazard engine.",
      "The stronger fit is dispel_countermeasure or procedural_bypass because the planar flavor is incidental.",
    ],
    family: "mechanism",
  },
  poison_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "poison_application",
    description: "Hazard centered on poison gas, toxic delivery, or other poisonous exposure.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  possession_haunt: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "possession_haunt",
    description: "Haunt that enters, rides, or briefly controls a victim rather than only attacking them externally.",
    family: "haunt_manifestation",
  },
  pressure_trigger: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "mechanism",
    conceptId: "pressure_trigger",
    description: "Hazard triggered by stepping on, weighing down, or depressing a pressure surface.",
    family: "mechanism",
  },
  procedural_bypass: {
    adjacentTags: [
      "physical_disarm",
      "false_safe_route",
    ],
    appliesWhen: [
      "The clean answer is learning and executing the hazard's safe procedure, sequence, or pattern rather than destroying it.",
      "A GM would plausibly retrieve the hazard for puzzle-like bypass, safe-route discovery, or passphrase-style navigation.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "procedural_bypass",
    description: "Hazard best bypassed through the right route, timing, command phrase, ritual sequence, or other correct procedure rather than direct disarm.",
    doesNotApplyWhen: [
      "The main answer is simple mechanism tampering, counteracting magic, or appeasing a spirit.",
      "The hazard only has a minor caution or tactical workaround without a real procedural solution.",
    ],
    family: "countermeasure_profile",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  projectile_emitter: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "projectile_emitter",
    description: "Hazard that fires bolts, beams, jets, sprays, or similar directed emissions from a fixed emitter.",
    family: "attack_vector",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  proximity_burst: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "proximity_burst",
    description: "Hazard that erupts in an immediate burst, blast, or detonation when a victim comes near or crosses a point.",
    family: "attack_vector",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  pursuit_punisher: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "pursuit_punisher",
    description: "Hazard that punishes retreat, pursuit, escape routes, or movement through chase-style spaces.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  quarantine_containment_countermeasure: {
    adjacentTags: [
      "contamination_cleanup_countermeasure",
      "source_cleanup_countermeasure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because the first meaningful answer is locking down spread, controlling access, or containing dangerous exposure.",
      "Containment procedures matter more than immediately dispelling, disarming, or appeasing the hazard.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "outbreak_containment",
    description: "Hazard best managed by isolating victims, sealing off the site, or imposing containment boundaries that stop spread while the danger is being handled.",
    doesNotApplyWhen: [
      "The hazard is dangerous but does not meaningfully spread, linger, or demand isolation and access control.",
      "The stronger fit is barrier_lockdown or sentinel_guardian because preventing passage is the hazard's function, not the party's resolution plan.",
    ],
    family: "countermeasure_profile",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  replayed_tragedy: {
    adjacentTags: [
      "judgment_haunt",
      "appeasement_countermeasure",
    ],
    appliesWhen: [
      "The haunt is naturally retrieved because it replays a specific past calamity, crime, execution, or emotional flashpoint as its core manifestation.",
      "The narrative repetition of an old event matters more than generic life drain, possession, or battlefield disruption.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "haunt",
    conceptId: "replayed_tragedy",
    description: "Haunt that re-enacts a murder, betrayal, execution, disaster, or other fixed traumatic event.",
    doesNotApplyWhen: [
      "The haunt is only sad, angry, or spiritually active without reenacting a fixed historical scene.",
      "The stronger fit is judgment_haunt or lure_compulsion because the recurring tragedy itself is not the central hook.",
    ],
    family: "haunt_manifestation",
  },
  resource_drain: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "resource_drain",
    description: "Hazard that taxes healing, spellcasting, equipment durability, or other party resources over time.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  respiratory_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "respiratory_application",
    description: "Hazard centered on smoke, choking vapor, breathlessness, or impaired breathing.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  restraint_capture: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "restraint_capture",
    description: "Hazard that binds, restrains, or holds intruders in place.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sensory_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "sensory_impairment",
    description: "Blinds, deafens, dazzles, or otherwise suppresses a victim's ability to perceive the environment clearly.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sentinel_guardian: {
    adjacentTags: [
      "alarm",
      "zone_denial",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved as a guardian layer protecting a place, object, or route from intrusion.",
      "Its value is in persistent watchfulness or defensive coverage, not just burst damage.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "guard_post",
    description: "Hazard whose role is to guard an area, treasure, threshold, or sanctum as a standing defense layer.",
    doesNotApplyWhen: [
      "The hazard mainly creates open-area denial with no strong guard-post identity.",
      "The hazard is mostly an ambush opener or chase-punishment device.",
    ],
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sound_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "sound_application",
    description: "Hazard centered on sonic force, deafening noise, vibration, or resonant disruption.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  source_cleanup_countermeasure: {
    adjacentTags: [
      "quarantine_containment_countermeasure",
      "contamination_cleanup_countermeasure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because the real answer is finding and dealing with the source object, origin point, or contamination engine.",
      "Neutralizing the origin matters more than only enduring the space or treating downstream symptoms.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "resolution",
    conceptId: "source_cleanup",
    description: "Hazard best resolved by locating and neutralizing the cursed source, leaking node, corrupted remains, or other origin driving the dangerous field.",
    doesNotApplyWhen: [
      "The hazard has no meaningful source object, leak point, or origin to clean up beyond the hazard itself.",
      "The stronger fit is procedural_bypass or physical_disarm because the answer is executing a sequence or tampering with a mechanism rather than eliminating an origin source.",
    ],
    family: "countermeasure_profile",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  source_tracing: {
    adjacentTags: [
      "observation_first",
      "source_cleanup_countermeasure",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because identifying the source object, origin point, or contamination engine is a major part of solving it.",
      "Finding what is powering the danger matters more than merely surviving exposure or executing a known disable procedure.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "problem",
    conceptId: "source_discovery",
    description: "Hazard whose real puzzle is locating the hidden anchor, leak point, cursed source, contamination engine, or origin node before a clean solution becomes possible.",
    doesNotApplyWhen: [
      "The hazard is fully understandable up front and the real challenge is timing, endurance, or multi-step execution rather than finding an origin.",
      "The stronger fit is source_cleanup_countermeasure because the source is already obvious and the remaining task is neutralizing it.",
    ],
    family: "problem_shape",
  },
  spawned_attackers: {
    adjacentTags: [
      "alarm",
      "phantom_assailants",
    ],
    appliesWhen: [
      "The hazard is naturally retrieved because it adds new hostile creatures, constructs, swarms, or manifestations to the scene.",
      "The extra attackers matter as separate encounter pressure rather than only as a damage effect.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "spawned_attackers",
    description: "Hazard that summons, creates, or releases separate attackers into the scene.",
    doesNotApplyWhen: [
      "The hazard only deals direct damage, restrains victims, or creates a temporary illusion without generating distinct assailants.",
      "The stronger fit is phantom_assailants when the threat is specifically a haunt manifestation rather than a broader hazard function.",
    ],
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  temple_hazard: {
    adjacentTags: [
      "dungeon_hazard",
      "appeasement_countermeasure",
    ],
    appliesWhen: [
      "Sacred architecture, ritual sanctums, or faith-site defense is central to the hazard's scene identity.",
      "The hazard is naturally retrieved for shrine, sanctum, or temple protection rather than generic indoor defense.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "temple_hazard",
    description: "Hazard strongly associated with shrines, sanctums, cathedrals, monasteries, or consecrated sites.",
    doesNotApplyWhen: [
      "The hazard is merely magical or haunted without specific sacred-site framing.",
      "The stronger setting is dungeon_hazard or urban_hazard rather than temple-focused.",
    ],
    family: "setting",
  },
  threshold_lockdown: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "mechanism",
    conceptId: "threshold_lockdown",
    description: "Hazard that seals, locks, or bars a threshold, doorway, or gate.",
    family: "mechanism",
  },
  timing_window: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "problem",
    conceptId: "timing_window",
    description: "Hazard that is best handled by acting during the right cycle, opening, lull, or repeating timing pattern.",
    family: "problem_shape",
  },
  tomb_hazard: {
    adjacentTags: [
      "dungeon_hazard",
      "temple_hazard",
    ],
    appliesWhen: [
      "Burial sites, funerary wards, grave robbing countermeasures, or undead-rest protections are central to the hazard.",
      "A user would retrieve it for crypts, tombs, barrows, or similar funerary scenes.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "tomb_hazard",
    description: "Hazard strongly associated with tombs, barrows, mausoleums, crypts, or burial defenses.",
    doesNotApplyWhen: [
      "The hazard is only underground or haunted without real funerary or burial-site identity.",
      "The stronger placement is temple_hazard or generic dungeon_hazard.",
    ],
    family: "setting",
  },
  tripwire_trigger: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "mechanism",
    conceptId: "tripwire_trigger",
    description: "Hazard triggered by tugging, crossing, or disturbing a tripwire.",
    family: "mechanism",
  },
  urban_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "urban_hazard",
    description: "Hazard strongly associated with civic districts, alleys, rooftops, sewers, shops, or other built urban spaces.",
    family: "setting",
  },
  ward_trigger: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "mechanism",
    conceptId: "ward_trigger",
    description: "Hazard triggered by a rune, glyph, sigil, ward, or similar inscribed mechanism.",
    family: "mechanism",
  },
  water_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "water_application",
    description: "Hazard centered on floods, geysers, waves, surges, or other dangerous water exposure.",
    family: "environmental_danger",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  wilderness_hazard: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "setting",
    conceptId: "wilderness_hazard",
    description: "Hazard strongly associated with forests, trails, camps, ruins in the wild, or other outdoor expedition scenes.",
    family: "setting",
  },
  zone_denial: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "encounter",
    conceptId: "zone_denial",
    description: "Hazard that makes an area costly to enter, cross, or remain inside.",
    family: "function",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
};

export const HAZARD_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG = buildProjectionRecord(
  CANONICAL_VOCABULARY.CATEGORY.HAZARD,
  HAZARD_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS,
);
