import { buildProjectionRecord, type CanonicalProjectionSeed } from "../builders.js";
import { CANONICAL_VOCABULARY } from "../vocabulary.js";

const SPELL_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS: Record<string, CanonicalProjectionSeed> = {
  action_denial: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "battlefield",
    conceptId: "action_denial",
    description: "Denies actions through paralysis, stupefying shutdown, slowed tempo, or similarly severe turn disruption.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  affliction_cleanup: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "affliction_cleanup",
    description: "Cleanses, cures, neutralizes, or removes disease, poison, curse, or similar afflictions.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  alarm: {
    adjacentTags: [
      "protective_ward",
      "scrying_protection",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to warn about intrusion, threshold crossing, tampering, or unwanted entry.",
      "Detection and notice matter more than directly stopping the intruder.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "alarm",
    description: "Alerts you or others when a watched area, threshold, or ward is crossed.",
    doesNotApplyWhen: [
      "The spell mainly protects, blocks, or hides the target without providing a warning function.",
      "The spell only reveals truth or magic generally rather than guarding a watched perimeter.",
    ],
    family: "security",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  animal_form: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "transformation",
    conceptId: "animal_form",
    description: "Transforms a creature into an animal, beast, pest, or similar natural form.",
    family: "transformation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_bleed: {
    adjacentTags: [
      "healing_support",
      "condition_support",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "bleed_remediation",
    description: "Staunches bleeding, ends persistent bleed damage, or closes wounds that keep draining a target.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_caster_disruption: {
    adjacentTags: [
      "countermagic",
      "silencing",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "battlefield",
    conceptId: "caster_disruption_remediation",
    description: "Disrupts casting, punishes spell use, or specifically suppresses hostile spellcasters in the moment.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_confusion: {
    adjacentTags: [
      "condition_support",
      "anti_fear",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "confusion_remediation",
    description: "Ends confusion, steadies a disordered mind, or protects a target from confusion-like mental unraveling.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_disease: {
    adjacentTags: [
      "affliction_cleanup",
      "anti_poison",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "disease_remediation",
    description: "Cures disease, counteracts infections, or protects a target against plague, fever, and similar disease effects.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_fear: {
    adjacentTags: [
      "condition_support",
      "anti_confusion",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "fear_remediation",
    description: "Counters frightened or fear effects, bolsters courage, or protects a target against fear.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_paralysis: {
    adjacentTags: [
      "condition_support",
      "escape_support",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "paralysis_remediation",
    description: "Ends paralysis, restores bodily function, or frees a target from magic or afflictions that leave it unable to move.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_petrification: {
    adjacentTags: [
      "affliction_cleanup",
      "condition_support",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "petrification_remediation",
    description: "Prevents, reverses, or counteracts petrification and other turn-to-stone effects.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  anti_poison: {
    adjacentTags: [
      "affliction_cleanup",
      "anti_disease",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "poison_remediation",
    description: "Cures poison, counters toxic afflictions, or protects a target against venom and similar poisoning effects.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  aquatic_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "aquatic_support",
    description: "Helps with swimming, underwater breathing, water-surface travel, or other aquatic movement.",
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  barrier_bypass: {
    adjacentTags: [
      "lock_bypass",
      "countermagic",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to pass through, nullify, or ignore a blocking wall, sealed threshold, force barrier, or magical ward.",
      "Crossing the obstruction matters more than simply traveling farther or counteracting magic in the abstract.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "barrier_bypass",
    description: "Gets a creature through a blocked threshold, wall, seal, force barrier, or magical ward that otherwise prevents passage.",
    doesNotApplyWhen: [
      "The spell only unlocks a door or manipulates a mechanism without really solving a barrier or ward.",
      "The spell's value is ordinary travel or relocation rather than penetrating a blocked passage.",
    ],
    family: "access_bypass",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  barrier_creation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "battlefield",
    conceptId: "barrier_creation",
    description: "Creates a wall, dome, cage, force barrier, or other discrete blocking structure that reshapes access lines.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  battle_form: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "transformation",
    conceptId: "battle_form",
    description: "Transforms a creature into a combat-ready form with new statistics or battle-form language.",
    family: "transformation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  battlefield_disruption: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "battlefield",
    conceptId: "battlefield_disruption",
    description: "Creates area denial, difficult terrain, barriers, or other battlefield obstacles.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  burst_damage: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "burst_damage",
    description: "Delivers concentrated damage in a spike or splash pattern that users naturally retrieve as a damage-first answer.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  charm_influence: {
    adjacentTags: [
      "emotion_control",
      "compulsion_control",
    ],
    appliesWhen: [
      "The spell's main value is improving a target's attitude, trust, or willingness to cooperate.",
      "The spell changes social reception more than it scripts exact behavior.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "influence",
    conceptId: "charm_influence",
    description: "Wins cooperation through friendliness, fascination, admiration, or magically altered social regard.",
    doesNotApplyWhen: [
      "The spell compels exact actions, overrides agency, or takes total control.",
      "The spell only manipulates mood without establishing a social bond or regard shift.",
    ],
    family: "influence",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  communication: {
    adjacentTags: [
      "signaling",
      "telepathic_communication",
      "message_delivery",
      "translation_support",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "signaling",
      "telepathic_communication",
      "message_delivery",
      "translation_support",
    ],
    conceptId: "communication",
    description: "Broad communication umbrella for spells used to signal allies, relay messages, bridge language barriers, or coordinate silently.",
    family: "communication",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  compulsion_control: {
    adjacentTags: [
      "charm_influence",
      "domination",
    ],
    appliesWhen: [
      "The spell explicitly pressures the target into doing something, moving somewhere, or obeying a commanded pattern.",
      "Loss of agency is more important than affection, calm, or broad mood change.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "influence",
    conceptId: "compulsion_control",
    description: "Forces scripted behavior, movement, or obedience against a target's normal will.",
    doesNotApplyWhen: [
      "The spell merely charms or emotionally softens the target.",
      "The spell fully dominates the target over sustained actions rather than issuing narrower commands.",
    ],
    family: "influence",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  concealment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "battlefield",
    conceptId: "concealment",
    description: "Makes a creature hard to see, hidden, concealed, or undetected.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  condition_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "condition_support",
    description: "Delays, suppresses, or removes afflictions and conditions.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  consultation: {
    adjacentTags: [
      "lore_consultation",
      "problem_diagnosis",
      "omen_guidance",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "lore_consultation",
      "problem_diagnosis",
      "omen_guidance",
    ],
    conceptId: "consultation",
    description: "Broad consultation umbrella for spells used to seek cosmic answers, diagnose mysteries, or gain non-sensory divinatory guidance.",
    family: "consultation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  contamination_cleanup: {
    adjacentTags: [
      "quarantine_containment",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "contamination_cleanup",
    description: "Cleanses tainted residue, neutralizes corrupted ground, removes lingering pollution, or purifies a contaminated space.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  countermagic: {
    adjacentTags: [
      "magic_detection",
      "protective_ward",
    ],
    appliesWhen: [
      "The spell is naturally retrieved because stopping, unravelling, or suppressing existing magic is its main job.",
      "Anti-magic response matters more than simple protection, detection, or concealment.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "battlefield",
    conceptId: "active_magic_counteraction",
    description: "Counteracts, dispels, suppresses, or shuts down magic.",
    doesNotApplyWhen: [
      "The spell mainly protects targets from harm without actually disrupting hostile magic.",
      "The spell only reveals or warns about magic rather than counteracting it.",
    ],
    family: "control",
    label: "countermagic",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  creature_summoning: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "summoning",
    conceptId: "creature_summoning",
    description: "Summons, conjures, or calls creatures to act as temporary allies, tools, or battlefield assets.",
    family: "summoning",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  crowd_clearing: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "crowd_clearing",
    description: "Damages or wipes clusters of weaker foes and is naturally retrieved as an anti-group answer.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  curse_removal: {
    adjacentTags: [
      "exorcism",
      "sanctification",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "curse_remediation",
    description: "Breaks, removes, or counteracts curses as a direct answer path rather than only suppressing symptoms.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  curse_revelation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "curse_discovery",
    description: "Identifies curses, spiritual corruption, or other malign supernatural bindings on a target.",
    family: "revelation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  death_prevention: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "death_prevention",
    description: "Prevents death, stabilizes the dying, or brings a creature back from the brink.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  disguise: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "disguise",
    description: "Helps alter appearance or impersonate another identity.",
    family: "infiltration",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  domination: {
    adjacentTags: [
      "compulsion_control",
      "action_denial",
    ],
    appliesWhen: [
      "The spell grants ongoing, high-authority control over what the target does rather than just one compelled action.",
      "A user would retrieve it as a takeover spell, not merely a charm or suggestion spell.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "influence",
    conceptId: "domination",
    description: "Seizes sustained control over a target's actions, body, or tactical decision-making.",
    doesNotApplyWhen: [
      "The spell only improves attitude, stirs emotion, or issues narrower one-off compulsions.",
      "The spell mainly suppresses actions without redirecting them under the caster's control.",
    ],
    family: "influence",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  eidolon_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "eidolon_support",
    description: "Directly benefits an eidolon or the summoner-eidolon bond.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  elemental_form: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "transformation",
    conceptId: "elemental_form",
    description: "Transforms a creature into an elemental form.",
    family: "transformation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  emotion_control: {
    adjacentTags: [
      "fear_pressure",
      "charm_influence",
    ],
    appliesWhen: [
      "The spell is naturally retrieved for changing a creature's feelings, morale, or emotional volatility.",
      "The emotional state change matters more than explicit obedience or truth extraction.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "influence",
    conceptId: "emotion_control",
    description: "Directly manipulates fear, calm, rage, love, despair, or other emotional states.",
    doesNotApplyWhen: [
      "The spell chiefly compels discrete actions or sustained domination.",
      "The spell only inflicts fear as damage pressure without broader emotional steering.",
    ],
    family: "influence",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  environmental_adaptation: {
    adjacentTags: [
      "aquatic_support",
      "field_shelter",
      "resistance_support",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to survive extreme heat, cold, altitude, smoke, pressure, or other punishing environmental conditions during travel or exploration.",
      "Environmental endurance matters more than only resisting one attack form or creating a place to rest.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "environmental_adaptation",
    description: "Helps creatures endure hostile climates, thin air, smoke, pressure, vacuum, or other expedition-grade environmental extremes.",
    doesNotApplyWhen: [
      "The spell mainly grants combat resistance, a protective ward, or aquatic mobility without broader expedition-survival value.",
      "The spell only creates shelter or sustenance rather than adapting creatures to the surrounding environment.",
    ],
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  escape_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "escape_support",
    description: "Helps a creature slip away, break free, flee, or evade pursuit.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  exorcism: {
    adjacentTags: [
      "curse_removal",
      "sanctification",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "hostile_presence_expulsion",
    description: "Banishes, expels, or spiritually drives out a hostile spirit, possession, haunt, or invading supernatural presence.",
    family: "resolution",
    label: "exorcism",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  expedition: {
    adjacentTags: [
      "navigation",
      "field_shelter",
      "environmental_adaptation",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "navigation",
      "flight",
      "aquatic_support",
      "sustenance",
      "field_shelter",
      "environmental_adaptation",
      "wayfinding",
    ],
    conceptId: "expedition",
    description: "Broad expedition umbrella for spells used for routefinding, travel-ready movement, shelter, sustainment, aquatic operations, and hostile-environment survival.",
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  extraction_teleport: {
    adjacentTags: [
      "short_range_teleport",
      "escape_support",
    ],
    appliesWhen: [
      "The spell is naturally retrieved as an escape, rescue, or anti-capture tool rather than only a movement spell.",
      "The reposition breaks danger, confinement, or immediate battlefield pressure.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "extraction_teleport",
    description: "Teleports a creature out of danger, through restraints, or away from immediate threat pressure.",
    doesNotApplyWhen: [
      "The spell is mostly a neutral short-range blink or a long-distance travel effect.",
      "The spell primarily opens planar movement rather than emergency extraction.",
    ],
    family: "teleportation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  fear_pressure: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "battlefield",
    conceptId: "fear_pressure",
    description: "Forces fear, panic, dread, or morale collapse onto a target.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  field_shelter: {
    adjacentTags: [
      "protective_ward",
      "planar_travel",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to create a campsite refuge, safe resting place, or expedition shelter in hostile territory.",
      "Its value is prolonged field habitation or protected rest rather than momentary combat defense.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "field_shelter",
    description: "Creates shelter, refuge, or a protected resting place in the field.",
    doesNotApplyWhen: [
      "The spell only creates a brief combat ward, cover effect, or instant defensive barrier.",
      "The spell merely transports creatures away instead of establishing a place to rest.",
    ],
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  flight: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "flight",
    description: "Grants flying movement, sustained aerial travel, or practical airborne maneuvering.",
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  forced_movement: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "battlefield",
    conceptId: "forced_movement",
    description: "Pushes, pulls, drags, or otherwise repositions a target against its will.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  hazard_revelation: {
    adjacentTags: [
      "magic_detection",
      "scouting",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to uncover traps, hidden dangers, secret magical wards, or dangerous concealed features in a location.",
      "Hazard discovery matters more than general magical detection or long-range scouting.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "hazard_discovery",
    description: "Reveals hidden traps, secret wards, concealed passage dangers, or other obscured environmental threats.",
    doesNotApplyWhen: [
      "The spell only detects magic, invisible creatures, or truth without specifically surfacing dangerous hidden features.",
      "The spell merely scouts an area from afar without exposing concealed trap logic or hazard placement.",
    ],
    family: "revelation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  healing_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "healing_support",
    description: "Directly restores hit points or accelerates recovery.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  illumination: {
    adjacentTags: [
      "senses_support",
      "line_of_sight_control",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "illumination",
    description: "Produces practical light that brightens darkness, reveals an area, or lets creatures see more clearly.",
    family: "sensory_support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  infiltration: {
    adjacentTags: [
      "stealth_support",
      "disguise",
      "social_infiltration",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "stealth_support",
      "disguise",
      "social_infiltration",
    ],
    conceptId: "infiltration",
    description: "Broad infiltration umbrella for quiet-entry, disguise, and covert social-passing spells.",
    family: "infiltration",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  initiative_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "initiative_support",
    description: "Improves initiative, pre-combat readiness, or the party's opening tempo before the first turn.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  invisibility_reveal: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "invisibility_discovery",
    description: "Exposes invisible, hidden, concealed, or magically obscured creatures and objects.",
    family: "revelation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  line_of_sight_control: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "battlefield",
    conceptId: "line_of_sight_control",
    description: "Blocks vision, obscures sight lines, or denies clear observation across an area.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  lock_bypass: {
    adjacentTags: [
      "trap_bypass",
      "barrier_bypass",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to unlock, unseal, or open a secured entry point, door, chest, manacle, or similar closure.",
      "Accessing something closed matters more than broad movement, damage, or generic anti-magic.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "lock_bypass",
    description: "Opens locks, sealed containers, secured doors, or similar closed access points through magic rather than physical lockpicking.",
    doesNotApplyWhen: [
      "The spell mainly destroys the obstacle, bypasses the whole wall, or teleports past the problem without interacting with the locked access point.",
      "The spell only manipulates unattended objects generally and opening secured access is not a real retrieval hook.",
    ],
    family: "access_bypass",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  long_range_teleport: {
    adjacentTags: [
      "short_range_teleport",
      "planar_travel",
    ],
    appliesWhen: [
      "The spell is naturally retrieved for strategic travel, relocation, or bypassing long routes.",
      "The destination scale is substantially larger than one encounter map or immediate tactical space.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "long_range_teleport",
    description: "Teleports creatures across major overland distances, settlements, or remote destinations.",
    doesNotApplyWhen: [
      "The spell is mainly a tactical blink, extraction, or planar crossing effect.",
      "The spell only repositions creatures within the same immediate scene.",
    ],
    family: "teleportation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  lore_consultation: {
    adjacentTags: [
      "truth_reveal",
      "problem_diagnosis",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "lore_consultation",
    description: "Provides interpretive insight, shared knowledge, or focused understanding about a subject, clue, history, or magical situation.",
    family: "consultation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  magic_detection: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "magic_discovery",
    description: "Reveals magical auras, spell presence, active effects, or other supernatural signatures.",
    family: "revelation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mechanism_manipulation: {
    adjacentTags: [
      "lock_bypass",
      "trap_bypass",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to operate a lever, button, latch, control panel, pressure surface, or similar mechanism from a safe or unusual position.",
      "The mechanism interaction itself matters more than broad telekinesis, damage, or ordinary object movement.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "mechanism_manipulation",
    description: "Precisely triggers, moves, holds, or operates levers, buttons, switches, pressure plates, locks, or similar scene mechanisms.",
    doesNotApplyWhen: [
      "The spell only moves creatures or loose objects without a real access-, control-, or mechanism-facing use case.",
      "The spell bypasses the obstacle by teleporting or destroying it instead of operating the mechanism.",
    ],
    family: "access_bypass",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  memory_manipulation: {
    adjacentTags: [
      "truth_reveal",
      "charm_influence",
    ],
    appliesWhen: [
      "The spell is naturally retrieved for altering what a target remembers, forgets, or believes it experienced.",
      "Memory editing is more central than charm, emotion, or truth exposure.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "influence",
    conceptId: "memory_manipulation",
    description: "Edits, suppresses, restores, or rewrites memories, recollection, and remembered events.",
    doesNotApplyWhen: [
      "The spell only reveals truth or emotions without changing stored recollection.",
      "The spell primarily imposes obedience or domination in the present moment.",
    ],
    family: "influence",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mental_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "mental_impairment",
    description: "Impairs thought, composure, or agency through fear, confusion, or similarly hostile mental effects.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  message_delivery: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "message_delivery",
    description: "Sends, stores, or relays actual content across time or distance.",
    family: "communication",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mobility: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "mobility",
    description: "Helps move faster, gain movement modes, or traverse terrain more effectively.",
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  mobility_denial: {
    adjacentTags: [
      "forced_movement",
      "restraint_capture",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "battlefield",
    conceptId: "mobility_denial",
    description: "Pins, slows, grounds, or otherwise prevents normal repositioning without necessarily functioning as a full restraint effect.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  navigation: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "navigation",
    description: "Helps orient, guide a route, or identify a destination's direction.",
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  offensive_summons: {
    adjacentTags: [
      "creature_summoning",
      "screening_summons",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "summoning",
    conceptId: "offensive_summons",
    description: "Creates summons primarily retrieved for direct damage, flanking pressure, or aggressive battlefield threat.",
    family: "summoning",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  omen_guidance: {
    adjacentTags: [
      "lore_consultation",
      "wayfinding",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "omen_guidance",
    description: "Asks for omens, directional guidance, or advisory insight about the best course of action, likely outcome, or strategic choice.",
    family: "consultation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  persistent_damage: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "persistent_damage",
    description: "Directly inflicts persistent damage or grants attacks that reliably impose persistent damage.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  planar_travel: {
    adjacentTags: [
      "long_range_teleport",
      "field_shelter",
    ],
    appliesWhen: [
      "Crossing into another plane, demiplane, or extraplanar route is central to the spell's retrieval value.",
      "The spell is naturally retrieved for cosmological travel rather than mundane relocation.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "planar_travel",
    description: "Moves creatures between planes, through planar routes, or into extraplanar destinations.",
    doesNotApplyWhen: [
      "The spell only teleports within the same plane or functions as a normal long-distance travel tool.",
      "Extradimensional storage or shelter is present without real plane-crossing travel.",
    ],
    family: "teleportation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  problem_diagnosis: {
    adjacentTags: [
      "curse_revelation",
      "magic_detection",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "problem_diagnosis",
    description: "Helps determine what hidden magical, spiritual, cursed, or otherwise obscure problem is actually affecting a target, site, or situation.",
    family: "consultation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  protective_ward: {
    adjacentTags: [
      "alarm",
      "resistance_support",
    ],
    appliesWhen: [
      "The spell is naturally retrieved as a defensive ward, sanctuary, or protective boundary rather than only a resistance buff.",
      "Its value comes from shielding a creature, object, or space against incoming harm or intrusion.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "protective_ward",
    description: "Places a ward, sanctuary, shield, or protective boundary.",
    doesNotApplyWhen: [
      "The spell only grants resistance, temporary Hit Points, or healing without a real warding or boundary element.",
      "The spell is mainly an alarm, anti-scrying, or mobility tool rather than direct protection.",
    ],
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  quarantine_containment: {
    adjacentTags: [
      "protective_ward",
      "contamination_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "outbreak_containment",
    description: "Helps isolate victims, secure a dangerous area, or impose protective boundaries that stop spread while the problem is being solved.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  quickened_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "quickened_support",
    description: "Grants extra actions, quickened condition benefits, or similar action-economy acceleration.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  reconnaissance: {
    adjacentTags: [
      "scouting",
      "tracking",
      "scouting_summons",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "scouting",
      "tracking",
      "scouting_summons",
    ],
    conceptId: "reconnaissance",
    description: "Broad scouting umbrella for spells that gather remote information, extend senses, or track a target from afar.",
    family: "reconnaissance",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  resistance_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "resistance_support",
    description: "Grants resistance or immunity against energy, damage, or hazards.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  resolution: {
    adjacentTags: [
      "curse_removal",
      "exorcism",
      "ritual_appeasement",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "curse_removal",
      "exorcism",
      "sanctification",
      "ritual_appeasement",
      "quarantine_containment",
      "contamination_cleanup",
      "source_revelation",
      "source_cleanup",
    ],
    conceptId: "problem_resolution",
    description: "Broad resolution umbrella for spells that break curses, expel hostile presences, contain spread, purify contamination, or solve a supernatural problem at its source.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  restraint_capture: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "battlefield",
    conceptId: "restraint_capture",
    description: "Restrains, immobilizes, entangles, or traps a target in place.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  revelation: {
    adjacentTags: [
      "magic_detection",
      "truth_reveal",
      "hazard_revelation",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "magic_detection",
      "invisibility_reveal",
      "truth_reveal",
      "curse_revelation",
      "hazard_revelation",
    ],
    conceptId: "problem_discovery",
    description: "Broad reveal umbrella for spells that detect magic, uncover deceptions, expose invisible threats, or identify hidden supernatural problems.",
    family: "revelation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  ritual_appeasement: {
    adjacentTags: [
      "sanctification",
      "exorcism",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "ritual_appeasement",
    description: "Ends a supernatural problem through offerings, restitution, funerary respect, ritual observance, or otherwise satisfying a spiritual demand rather than expelling the presence outright.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sanctification: {
    adjacentTags: [
      "ritual_appeasement",
      "exorcism",
      "protective_ward",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "sacred_taint_sanctification",
    description: "Consecrates, hallowes, purifies, or spiritually cleanses a creature, object, or site to solve a malign supernatural problem.",
    family: "resolution",
    label: "sanctification",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  scouting: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "scouting",
    description: "Helps observe at a distance, extend senses, or locate a target.",
    family: "reconnaissance",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  scouting_summons: {
    adjacentTags: [
      "summoned_servitor",
      "creature_summoning",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "summoning",
    conceptId: "scouting_summons",
    description: "Creates a summon primarily valued for reconnaissance, watch duty, sensing, or forward information gathering.",
    family: "summoning",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  screening_summons: {
    adjacentTags: [
      "creature_summoning",
      "temporary_hp_support",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "summoning",
    conceptId: "screening_summons",
    description: "Creates bodies mainly used to block space, absorb hits, or protect allies rather than maximize damage.",
    family: "summoning",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  scrying_protection: {
    adjacentTags: [
      "alarm",
      "countermagic",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to keep plans, sanctums, identities, or conversations hidden from magical spying.",
      "Its core value is denying observation or divination rather than only raising an intrusion alarm.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "scrying_protection",
    description: "Blocks magical observation, remote viewing, divinatory surveillance, or other information leakage from a protected target or space.",
    doesNotApplyWhen: [
      "The spell only improves mundane concealment or silence without real anti-divination protection.",
      "The spell counters magic broadly but is not specifically about surveillance or remote observation.",
    ],
    family: "security",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  security: {
    adjacentTags: [
      "alarm",
      "scrying_protection",
      "protective_ward",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "alarm",
      "scrying_protection",
      "protective_ward",
      "countermagic",
    ],
    conceptId: "security",
    description: "Broad security umbrella for spells that warn about intrusion, protect private spaces, or harden a target against magical observation and interference.",
    family: "security",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  senses_support: {
    adjacentTags: [
      "scouting",
      "invisibility_reveal",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "senses_support",
    description: "Enhances vision or other senses through darkvision, see invisible, sharpened perception, scent, or similar perceptual upgrades.",
    family: "sensory_support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sensory_impairment: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "effect",
    conceptId: "sensory_impairment",
    description: "Blinds, deafens, or otherwise directly suppresses a creature's senses.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  short_range_teleport: {
    adjacentTags: [
      "extraction_teleport",
      "long_range_teleport",
    ],
    appliesWhen: [
      "The spell repositions a creature within the current encounter or scene rather than serving as expedition travel.",
      "The tactical blink or reposition is itself a major reason to retrieve the spell.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "short_range_teleport",
    description: "Teleports a creature across a short tactical distance, usually within the same scene or encounter area.",
    doesNotApplyWhen: [
      "The spell is mainly about escaping custody, extracting allies, or long-distance transport.",
      "The spell primarily crosses planes or major overland distances.",
    ],
    family: "teleportation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  signaling: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "signaling",
    description: "Helps draw attention, mark a location, or coordinate allies.",
    family: "communication",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  silencing: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "battlefield",
    conceptId: "silencing",
    description: "Suppresses speech, sound production, verbal casting, or other voice-dependent action.",
    family: "control",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  single_target_removal: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "effect",
    conceptId: "single_target_removal",
    description: "Drops, banishes, petrifies, or otherwise decisively removes one important creature from the fight.",
    family: "impact",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sleep_magic: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "influence",
    conceptId: "sleep_magic",
    description: "Puts creatures to sleep, into magical slumber, or into a similarly enforced dormant state.",
    family: "influence",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  social_infiltration: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "social_infiltration",
    description: "Helps blend into a group or pass under social scrutiny.",
    family: "infiltration",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  source_cleanup: {
    adjacentTags: [
      "source_revelation",
      "contamination_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "source_cleanup",
    description: "Neutralizes, destroys, seals, or cleans up the cursed object, infected origin, corrupted site, or anchored source driving the problem.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  source_revelation: {
    adjacentTags: [
      "problem_diagnosis",
      "source_cleanup",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "source_discovery",
    description: "Reveals the hidden source, curse anchor, carrier, infected origin, or spreading point of a supernatural or outbreak problem.",
    family: "resolution",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  stealth_support: {
    adjacentTags: [
      "concealment",
      "silencing",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to help a creature move quietly, avoid notice, pass unseen, or keep a covert approach from drawing attention.",
      "The retrieval hook is quiet entry or low-profile movement rather than only broad battlefield obscurity.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "stealth_support",
    description: "Helps move quietly, avoid notice, suppress noisy presence, or otherwise support covert entry and low-profile movement.",
    doesNotApplyWhen: [
      "The spell only creates a combat concealment effect or visual obstruction without really supporting a covert approach.",
      "The spell changes appearance or social presentation without materially helping the target move unnoticed.",
    ],
    family: "infiltration",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  summoned_servitor: {
    adjacentTags: [
      "creature_summoning",
      "scouting",
    ],
    appliesWhen: [
      "The spell is naturally retrieved for utility help, labor, scouting, transport, or task performance rather than frontline combat stats.",
      "The conjured ally behaves more like a helper or specialist tool than a main battle summon.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "summoning",
    conceptId: "summoned_servitor",
    description: "Creates a helper, laborer, scout, mount, or similarly task-focused magical servitor rather than a pure combat summon.",
    doesNotApplyWhen: [
      "The spell's main value is summoning a combat creature to attack, flank, or absorb hits.",
      "The spell only creates an object, barrier, or terrain effect without a real servant-like entity.",
    ],
    family: "summoning",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  sustenance: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.DETERMINISTIC,
    axis: "utility",
    conceptId: "sustenance",
    description: "Provides food, water, rations, or practical nourishment for travel and survival.",
    family: "expedition",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  telepathic_communication: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "telepathic_communication",
    description: "Creates direct mind-to-mind communication, silent tactical coordination, or psychic speech between creatures.",
    family: "communication",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  temporary_hp_support: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "support",
    conceptId: "temporary_hp_support",
    description: "Grants temporary Hit Points or similar buffer protection instead of restoring lost Hit Points.",
    family: "support",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  tracking: {
    adjacentTags: [
      "scouting",
      "navigation",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to find a named target, trace a quarry, or point the caster toward a specific creature, object, or place.",
      "Target location matters more than broad sensory surveillance or general route guidance.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "tracking",
    description: "Locates a specific creature, object, or destination, or follows a supernatural trail toward it.",
    doesNotApplyWhen: [
      "The spell mainly reveals an area, extends senses, or scouts without locking onto a specific target.",
      "The spell only helps orient a journey or choose a route once the destination is already known.",
    ],
    family: "reconnaissance",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  transformation: {
    adjacentTags: [
      "battle_form",
      "animal_form",
      "elemental_form",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "transformation",
    compositeOfAnyTags: [
      "battle_form",
      "animal_form",
      "elemental_form",
    ],
    conceptId: "transformation",
    description: "Spells that alter a creature's body, form, or battle shape.",
    family: "transformation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  translation_support: {
    adjacentTags: [
      "telepathic_communication",
      "message_delivery",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to understand, translate, or make oneself understood across otherwise incompatible languages or scripts.",
      "Language access matters more than merely sending a message or speaking silently.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "translation_support",
    description: "Bridges spoken or written language barriers through translation, comprehension, deciphering, or magically shared understanding.",
    doesNotApplyWhen: [
      "The spell only transmits content farther or more privately without solving a language barrier.",
      "The spell reveals truth, thoughts, or memories without actually translating speech or writing.",
    ],
    family: "communication",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  trap_bypass: {
    adjacentTags: [
      "lock_bypass",
      "mechanism_manipulation",
    ],
    appliesWhen: [
      "The spell is naturally retrieved to disable, neutralize, or get past a trap or trapped access point without simply enduring the hazard.",
      "Trap-solving matters more than generic revelation, scouting, or damage prevention.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "trap_bypass",
    description: "Disarms, suppresses, safely triggers, or helps bypass a trap, warded threshold, or similar trapped access problem.",
    doesNotApplyWhen: [
      "The spell only reveals that a trap exists without helping bypass or disable it.",
      "The spell mainly counters open combat hazards or battlefield effects rather than access-facing traps.",
    ],
    family: "access_bypass",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  truth_reveal: {
    adjacentTags: [
      "magic_detection",
      "memory_manipulation",
    ],
    appliesWhen: [
      "The spell's retrieval value comes from exposing deception, forcing truthful answers, or stripping away false presentation.",
      "A user would plausibly look for it when they need an answer spell rather than a sensor spell.",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "utility",
    conceptId: "truth_discovery",
    description: "Forces honesty, exposes lies, or reveals disguised, false, or hidden truths.",
    doesNotApplyWhen: [
      "The spell only detects magic, invisibility, or general auras without interrogating truth or deception.",
      "The spell mainly alters memory or emotions rather than revealing facts.",
    ],
    family: "revelation",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  undead_summoning: {
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.HYBRID,
    axis: "summoning",
    conceptId: "undead_summoning",
    description: "Summons, calls, or manifests undead entities, spirits of the dead, or corpse-driven servitors.",
    family: "summoning",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
  wayfinding: {
    adjacentTags: [
      "navigation",
      "tracking",
      "long_range_teleport",
    ],
    assignmentMode: CANONICAL_VOCABULARY.ASSIGNMENT.MODE.COMPOSITE,
    axis: "utility",
    compositeOfAnyTags: [
      "navigation",
      "tracking",
      "long_range_teleport",
      "planar_travel",
    ],
    conceptId: "wayfinding",
    description: "Broad route-and-destination umbrella for spells that orient travel, locate a target destination, or bypass distance through strategic movement magic.",
    family: "wayfinding",
    translationStatus: CANONICAL_VOCABULARY.TRANSLATION.STATUS.PROVISIONAL,
  },
};

export const SPELL_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG = buildProjectionRecord(
  CANONICAL_VOCABULARY.CATEGORY.SPELL,
  SPELL_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG_SEEDS,
);
