import { DERIVED_TAG_CANONICAL_PROJECTIONS_BY_CATEGORY } from "../concepts/index.js";

export const HAZARD_DERIVED_TAG_CANONICAL_PROJECTIONS_BY_TAG = DERIVED_TAG_CANONICAL_PROJECTIONS_BY_CATEGORY.hazard;
