import { DerivedTagCatalogEntry } from "../../types.js";

export const CREATURE_DERIVED_TAG_CATALOG: DerivedTagCatalogEntry[] = [
  {
    category: "creature",
    family: "setting",
    description: "Creature environment and setting tags.",
    tags: [
      { value: "aquatic_setting", description: "Strongly associated with open water, underwater spaces, or aquatic environments." },
      { value: "freshwater_setting", description: "Strongly associated with rivers, lakes, ponds, streams, springs, or other inland waters." },
      { value: "coastal_setting", description: "Strongly associated with coasts, shores, reefs, or littoral edges." },
      { value: "astral_setting", description: "Strongly associated with Astral Plane scenes, silver-void travel, or stable portal routes." },
      { value: "first_world_setting", description: "Strongly associated with the First World, fey realms, or thin-boundary crossings into that plane." },
      { value: "boneyard_setting", description: "Strongly associated with the Boneyard, psychopomp duties, or soul-processing afterlife scenes." },
      { value: "island_setting", description: "Strongly associated with islands, archipelagos, or isolated isles." },
      { value: "nautical_setting", description: "Strongly associated with ships, sailors, wrecks, or harbors." },
      { value: "forest_setting", description: "Strongly associated with forests, jungles, groves, or briar-choked wilds." },
      { value: "plains_setting", description: "Strongly associated with open plains, grasslands, prairies, or savannas." },
      { value: "canyon_setting", description: "Strongly associated with canyons, gorges, mesas, or badlands." },
      { value: "swamp_setting", description: "Strongly associated with bogs, marshes, fens, or mires." },
      { value: "underground_setting", description: "Strongly associated with caves, tunnels, crypts, or subterranean spaces." },
      { value: "urban_setting", description: "Strongly associated with cities, streets, alleys, markets, or sewers." },
      { value: "arctic_setting", description: "Strongly associated with snow, ice, tundra, or frozen reaches." },
      { value: "desert_setting", description: "Strongly associated with dunes, sand, or arid wastes." },
      { value: "wasteland_setting", description: "Strongly associated with barren wastes, blasted wastelands, or desolate badlands." },
      { value: "mountain_setting", description: "Strongly associated with cliffs, peaks, passes, or rocky heights." },
      { value: "graveyard_setting", description: "Strongly associated with cemeteries, tombs, barrows, or burial grounds." },
      { value: "ruins_setting", description: "Strongly associated with ancient ruins or derelict structures." },
      { value: "temple_setting", description: "Strongly associated with temples, shrines, monasteries, or other sacred sites." },
      { value: "fortress_setting", description: "Strongly associated with castles, fortresses, citadels, or strongholds." },
      { value: "volcanic_setting", description: "Strongly associated with volcanoes, calderas, lava, or magma." },
      { value: "rural_setting", description: "Strongly associated with villages, hamlets, farms, pastures, or other countryside scenes." },
    ],
  },
  {
    category: "creature",
    family: "encounter_role",
    description: "Creature practical-fit tags for socially embedded NPCs and role-defined humanoid combatants.",
    tags: [
      {
        value: "profession_npc",
        description: "Role-defined NPC such as a captain, guard, merchant, or commoner.",
        seedRecordKeys: [
          "pathfinder-npc-core:OB4x3FBwjJBfOsi3",
          "pathfinder-npc-core:D3SJlR6iZYMgL2s8",
          "pathfinder-npc-core:Y0MSOv0l5ePhP3Co",
          "pathfinder-npc-core:eF87AWFclYpu1cgD",
          "pathfinder-npc-core:AxB7Sh2Bbt9AcDPp",
          "pathfinder-npc-core:qtD7Xa8Mgl0Y63os",
          "pathfinder-npc-core:lhhdqML98o90gXqO",
          "pathfinder-npc-core:UWBT8xEvGfHaAj0U",
          "pathfinder-npc-core:B9NoqcAASkg2Gjz3",
          "pathfinder-npc-core:MxcprNbX7hcpAU8p",
          "pathfinder-npc-core:Wv4jaiD6X8negvH2",
          "pathfinder-npc-core:XnfZwf1g4rfan1gY",
          "pathfinder-npc-core:msItO7UjfQfWe9nZ",
          "pathfinder-npc-core:9wdaQ6ZuBAZx9Vjk",
          "pathfinder-npc-core:Dd7E7pMKxPhrXaa8",
          "pathfinder-npc-core:GuYToKMrt5mxxZW6",
          "pathfinder-npc-core:fDUocyyYWJU1grxV",
          "pathfinder-npc-core:9EzCOBw3rMsyfr5Q",
          "pathfinder-npc-core:taNAx8xPuOJ3EmxC",
          "pathfinder-npc-core:BYpxg06tP5hI6CzQ",
          "pathfinder-npc-core:3m8fkhbaUubLeckt",
          "pathfinder-npc-core:z1tLeckmpJuStmlx",
          "pathfinder-npc-core:GKDMvepxkEsUnN5d",
          "pathfinder-npc-core:V6UV4BeMRUUwGL0g",
          "pathfinder-npc-core:8WFse73d3kgTPbje",
          "pathfinder-npc-core:hXcBMFGA45ES01Lb",
          "pathfinder-npc-core:rY3uqGq5QyvNOU91",
          "hellbreakers-bestiary:9a0GH3YuaACzsyof",
          "hellbreakers-bestiary:pjEz149NBKw1h96g",
          "hellbreakers-bestiary:PYqZIgsj26WyJOlN",
          "lost-omens-bestiary:95IcOUvxABvj5lvo",
          "revenge-of-the-runelords-bestiary:bWqwwzOECcOmXLQD",
        ],
      },
      {
        value: "civic_npc",
        description: "Fits the civic or social fabric of a scene and usually isn't the primary monster answer.",
        seedRecordKeys: [
          "pathfinder-npc-core:Y0MSOv0l5ePhP3Co",
          "pathfinder-npc-core:eF87AWFclYpu1cgD",
          "pathfinder-npc-core:AxB7Sh2Bbt9AcDPp",
          "pathfinder-npc-core:qtD7Xa8Mgl0Y63os",
          "pathfinder-npc-core:lhhdqML98o90gXqO",
          "pathfinder-npc-core:UWBT8xEvGfHaAj0U",
          "pathfinder-npc-core:B9NoqcAASkg2Gjz3",
          "pathfinder-npc-core:MxcprNbX7hcpAU8p",
          "pathfinder-npc-core:Wv4jaiD6X8negvH2",
          "pathfinder-npc-core:XnfZwf1g4rfan1gY",
          "pathfinder-npc-core:msItO7UjfQfWe9nZ",
          "pathfinder-npc-core:9wdaQ6ZuBAZx9Vjk",
          "pathfinder-npc-core:Dd7E7pMKxPhrXaa8",
          "pathfinder-npc-core:GuYToKMrt5mxxZW6",
          "pathfinder-npc-core:fDUocyyYWJU1grxV",
          "pathfinder-npc-core:9EzCOBw3rMsyfr5Q",
          "pathfinder-npc-core:taNAx8xPuOJ3EmxC",
          "pathfinder-npc-core:BYpxg06tP5hI6CzQ",
          "pathfinder-npc-core:3m8fkhbaUubLeckt",
          "pathfinder-npc-core:z1tLeckmpJuStmlx",
          "pathfinder-npc-core:GKDMvepxkEsUnN5d",
          "pathfinder-npc-core:V6UV4BeMRUUwGL0g",
          "pathfinder-npc-core:8WFse73d3kgTPbje",
          "pathfinder-npc-core:hXcBMFGA45ES01Lb",
          "pathfinder-npc-core:rY3uqGq5QyvNOU91",
          "hellbreakers-bestiary:9a0GH3YuaACzsyof",
          "hellbreakers-bestiary:PYqZIgsj26WyJOlN",
        ],
      },
      {
        value: "combatant_npc",
        description: "Role-defined humanoid combatant such as a soldier, bandit, mercenary, or cultist.",
        seedRecordKeys: [
          "pathfinder-npc-core:D3SJlR6iZYMgL2s8",
          "pathfinder-npc-core:Iax22298eQbIhIQK",
          "pathfinder-npc-core:02AGznZTv5jjcnOg",
          "pathfinder-npc-core:GZxDz6PKbHs9f2WN",
          "pathfinder-npc-core:O0n4NLOuY3ZkEKbF",
          "pathfinder-npc-core:AhyWwDKH1gIVSfys",
          "pathfinder-npc-core:m7UKHHTw1WpDCfsL",
          "pathfinder-npc-core:WzBMIigC3lfvZyhJ",
          "pathfinder-npc-core:0cj7cQhgNnLxbUmR",
          "pathfinder-npc-core:2hBS767YPGZwXeiP",
          "pathfinder-npc-core:tGndoQjOV5Mj5Foh",
          "pathfinder-monster-core:PLZk6zY5iwccPTPS",
          "pathfinder-monster-core:V90OYOMyyPLPJuod",
          "pathfinder-npc-core:A4XWtiK4iStEDAUu",
          "pathfinder-npc-core:C8Bo22NBYGoj9Fwd",
          "pathfinder-npc-core:fSwCwS75z9FeUazU",
          "pathfinder-npc-core:xnHaTClGCleGFoLP",
          "age-of-ashes-bestiary:SVh7cPwyGgmZORVz",
          "age-of-ashes-bestiary:egTpOr4Wc0L5e0iY",
          "agents-of-edgewatch-bestiary:xN3FDmrCKWW0psBu",
          "blood-lords-bestiary:JiT7B2Y7yYG8G0ZL",
          "hellbreakers-bestiary:9a0GH3YuaACzsyof",
          "hellbreakers-bestiary:pjEz149NBKw1h96g",
          "hellbreakers-bestiary:PYqZIgsj26WyJOlN",
          "lost-omens-bestiary:95IcOUvxABvj5lvo",
          "kingmaker-bestiary:z1Hk6z6RU4sF9aJU",
          "prey-for-death-bestiary:tKqmm3jB9aZBJYHN",
          "revenge-of-the-runelords-bestiary:bWqwwzOECcOmXLQD",
        ],
      },
    ],
  },
  {
    category: "creature",
    family: "ontology_cluster",
    description: "Creature semantic groupings that aggregate fragmented native ontology when exact traits are too narrow.",
    tags: [
      {
        value: "undead_adjacent",
        description: "Groups undead and closely undead-coded native signals into one retrieval bucket.",
        nativeOntologyPolicy: "aggregates_native_signals",
      },
      {
        value: "sinspawn_family",
        description: "Groups sinspawn and close runelord-bred sinspawn offshoots into one retrieval bucket.",
        nativeOntologyPolicy: "aggregates_native_signals",
        seedRecordKeys: [
          "pathfinder-monster-core:3nUt7cW8fqE5IpyE",
          "pathfinder-monster-core:eke1AhiUjNPpyRhG",
          "pathfinder-monster-core:pkhNqTDUttoAzcKn",
          "pathfinder-monster-core:k4fqHhiax2GPrkbh",
          "pathfinder-monster-core:h4cMwW2K34KheWtD",
          "pathfinder-monster-core:ccAeM0tNgf5aVokj",
          "pathfinder-monster-core:yv7hdQ3MO3pLgCF5",
          "pathfinder-monster-core-2:KxVSaTjRAUwTWeDX",
          "battlecry-bestiary:DZiYwwjNKlAlyNU2",
          "revenge-of-the-runelords-bestiary:CPkNCHW9cGAUq099",
          "revenge-of-the-runelords-bestiary:EsCu5ehBgpwRHKGZ",
          "revenge-of-the-runelords-bestiary:bwpKnfGrRdLrSEyJ",
          "seven-dooms-for-sandpoint-bestiary:xoh5JAue3PtjH6dS",
        ],
      },
    ],
  },
  {
    category: "creature",
    family: "threat_profile",
    description: "Creature prep-driving threat patterns based on behavior, counterplay, or encounter consequence rather than type.",
    tags: [
      { value: "possession_threat", description: "Can possess, body-snatch, or take control of a victim from within." },
      { value: "life_drain_threat", description: "Threat defined by draining blood, vitality, life force, or souls from victims." },
      { value: "spawn_creator", description: "Creates additional threats through infestation, spawn-making, conversion, or implanted offspring." },
      { value: "petrification_threat", description: "Threat defined by petrifying victims or turning them to stone." },
      { value: "regeneration_threat", description: "Regenerates or requires special suppression or finishing countermeasures." },
      { value: "ambush_grabber", description: "Captures prey through grabbing, constriction, swallowing whole, webbing, or drag-off ambush tactics." },
    ],
  },
  {
    category: "creature",
    family: "motif",
    description: "Creature motif tags for recurring scene and presentation themes not captured by native traits.",
    tags: [
      { value: "carnival_show", description: "Strongly associated with carnivals, circuses, clowns, jesters, or sideshow-style presentation." },
      { value: "living_toy", description: "Strongly associated with dolls, puppets, mannequins, or other animated playthings." },
      { value: "living_artwork", description: "Strongly associated with paintings, graffiti, murals, portraits, or other artworks brought to life." },
      { value: "trickster_chaos", description: "Strongly associated with pranks, mischief, whimsy, or explicit trickster behavior." },
      { value: "mask_motif", description: "Strongly associated with masks, veils, ceremonial face-coverings, or deliberately obscured presentation." },
      { value: "faceless_horror", description: "Strongly associated with missing, hidden, stolen, or featureless faces." },
      {
        value: "disguised_pretender",
        description: "Strongly associated with false identities, impersonation, infiltration, shapeshifting, or replacement.",
        seedRecordKeys: [
          "pathfinder-npc-core:G2AJ9Ya7QG7ebNPO",
          "book-of-the-dead-bestiary:zqftTUpxqkdLx2IY",
          "kingmaker-bestiary:Dxn6t9aoWUwPn6CE",
          "kingmaker-bestiary:nDFogS2qQJomjfmR",
          "pathfinder-bestiary:AdQVjlOWB6rmBRVp",
          "pathfinder-bestiary:3nOBhH8j9I7ps6fC",
          "pathfinder-bestiary:hOXpmWmXU8N3n4Bw",
          "pathfinder-monster-core:kngoPtu4Cr3BtgW8",
          "pathfinder-monster-core:pH2yNe16EnoJ8R0i",
          "season-of-ghosts-bestiary:52dTAJPXCnE48a5a",
          "season-of-ghosts-bestiary:APu2EqTJ4QdHkwtR",
          "season-of-ghosts-bestiary:QSa1PbcvbgDv8Zpr",
          "season-of-ghosts-bestiary:Mt053Q3jCVLXp6us",
          "season-of-ghosts-bestiary:6UkZJRICusE2EOhS",
        ],
      },
    ],
  },
  {
    category: "creature",
    family: "bound_object",
    description: "Creature tags for animated objects, statues, and other bound physical forms.",
    tags: [
      {
        value: "animated_object",
        description: "Strongly associated with animated objects, furniture, tools, or other constructed items.",
        seedRecordKeys: [
          "age-of-ashes-bestiary:yrU0xi4eKBmcGudo",
          "blood-lords-bestiary:DIDEV6UK5S5jQunK",
          "curtain-call-bestiary:SGWcXt1bqMh09qab",
          "gatewalkers-bestiary:itAkkjCM3EUQ4heC",
          "lost-omens-bestiary:8AANjQtU703ghIsR",
          "lost-omens-bestiary:fXlmbjtV3spZlmGS",
          "myth-speaker-bestiary:o2O3dPdWCCgRcIO3",
          "one-shot-bestiary:Z6aUTOMtvX2erFeA",
          "outlaws-of-alkenstar-bestiary:t60zBqM2apOZtOaC",
          "pathfinder-monster-core-2:jaKVhw83CPKpW9UJ",
          "quest-for-the-frozen-flame-bestiary:wuV8k7N1cEJBYNbK",
          "season-of-ghosts-bestiary:V67VC975O8iC1Yq2",
        ],
      },
      {
        value: "animated_statue",
        description: "Strongly associated with animated statues, effigies, idols, or monuments.",
      },
    ],
  },
];
