import { DerivedTagCatalogEntry } from "../../types.js";

export const HAZARD_DERIVED_TAG_CATALOG: DerivedTagCatalogEntry[] = [
  {
    category: "hazard",
    family: "mechanism",
    description: "Hazards whose threat comes from trigger mechanisms, locking thresholds, control surfaces, or planar breaches.",
    tags: [
      {
        value: "ward_trigger",
        description: "Hazard triggered by a rune, glyph, sigil, ward, or similar inscribed mechanism.",
        seedRecordKeys: [
          "sky-kings-tomb-bestiary:yGlzyyqtMfngIBON",
          "shades-of-blood-bestiary:ITCAohOOP7A1AK2X",
          "quest-for-the-frozen-flame-bestiary:HMpKt3b2LfrXa9yV",
          "blood-lords-bestiary:mZUwni8Hhv27vj4s",
          "blood-lords-bestiary:NogvW222v6TGMz5w",
          "kingmaker-bestiary:oBPdL0icCG5zmknB",
          "agents-of-edgewatch-bestiary:qy53ECS2agScE7G3",
          "extinction-curse-bestiary:1HYH5BgFGtFxVMpc",
          "age-of-ashes-bestiary:lDgabn0WtDKbLtfc",
          "curtain-call-bestiary:RzrRRymlgfoGIevs",
          "extinction-curse-bestiary:1CjTIaMYUvQUkQI2",
          "hazards:m4PRYxFq9ojcwesh",
          "strength-of-thousands-bestiary:ZDiRrUHkhFz0mLc7",
          "the-slithering-bestiary:IUAbDA2cbIB4ONlD",
          "strength-of-thousands-bestiary:5f8EKdudDgYRBmqA",
          "hazards:nO4osrBRnpWKFCMP",
          "agents-of-edgewatch-bestiary:HXiA7x1jWnB1BqUy",
          "agents-of-edgewatch-bestiary:QHcBauLnHzfwkDBK",
          "blood-lords-bestiary:s16EyzsD3GLLY43o",
          "season-of-ghosts-bestiary:DueMGlf6tX1bqwSS",
        ],
      },
      { value: "pressure_trigger", description: "Hazard triggered by stepping on, weighing down, or depressing a pressure surface." },
      { value: "tripwire_trigger", description: "Hazard triggered by tugging, crossing, or disturbing a tripwire." },
      {
        value: "threshold_lockdown",
        description: "Hazard that seals, locks, or bars a threshold, doorway, or gate.",
        seedRecordKeys: [
          "curtain-call-bestiary:CbDmMyhdy0O6Nndy",
          "curtain-call-bestiary:wJTI5OsZaV7n2VUp",
        ],
      },
      { value: "control_interface", description: "Hazard operated through a button, lever, console, panel, switch, or similar control surface." },
      {
        value: "planar_breach",
        description: "Hazard centered on a portal, rift, tear, breach, or other unstable opening in reality.",
        seedRecordKeys: [
          "pathfinder-dark-archive:P2fNCqJsR0gazMzM",
          "hazards:yM4G2LvMwvkIRx0G",
          "blood-lords-bestiary:I83vD5fNYIC1s3Xg",
        ],
      },
    ],
  },
  {
    category: "hazard",
    family: "function",
    description: "Hazard practical-function tags for alerts and restraint effects.",
    tags: [
      { value: "alarm", description: "Alerts guardians, onlookers, or nearby creatures to an intrusion." },
      {
        value: "restraint_capture",
        description: "Hazard that binds, restrains, or holds intruders in place.",
        seedRecordKeys: [
          "book-of-the-dead-bestiary:PH4GHPsekbDdyX3j",
        ],
      },
      {
        value: "barrier_lockdown",
        description: "Hazard that seals, closes, or blocks passage to trap or delay intruders.",
        seedRecordKeys: [
          "curtain-call-bestiary:CbDmMyhdy0O6Nndy",
          "curtain-call-bestiary:wJTI5OsZaV7n2VUp",
          "outlaws-of-alkenstar-bestiary:QQ2Ci8E2lkxG8QIV",
        ],
      },
      {
        value: "spawned_attackers",
        description: "Hazard that summons, creates, or releases separate attackers into the scene.",
        seedRecordKeys: [
          "extinction-curse-bestiary:1CjTIaMYUvQUkQI2",
          "gatewalkers-bestiary:6c4I4D3DgJmsSZEI",
          "hazards:4jAJh3cTLIgkqtou",
          "curtain-call-bestiary:0w2my6fBuCH98gV9",
          "hellbreakers-bestiary:KqRkvwwQWX6C8YAx",
        ],
      },
    ],
  },
  {
    category: "hazard",
    family: "haunt_manifestation",
    description: "Haunt manifestations that materially change the encounter through attackers, lures, or life-draining effects.",
    tags: [
      { value: "life_drain_hazard", description: "Haunt that drains life force, vitality, or souls from victims." },
      {
        value: "phantom_assailants",
        description: "Haunt that manifests ghostly, spectral, or phantom attackers as separate assailants.",
        seedRecordKeys: [
          "gatewalkers-bestiary:6c4I4D3DgJmsSZEI",
          "book-of-the-dead-bestiary:GabMKY8QJOulyqAr",
          "book-of-the-dead-bestiary:PH4GHPsekbDdyX3j",
          "curtain-call-bestiary:NKj4bVrJwkf85jwV",
          "triumph-of-the-tusk-bestiary:AteURENKIt5Zg2sS",
        ],
      },
      { value: "lure_compulsion", description: "Haunt that beckons, lures, or compels creatures into moving or acting against their judgment." },
      { value: "battlefield_disruption", description: "Haunt that reshapes the scene with barriers, violent manifestations, or other encounter-disrupting effects." },
    ],
  },
  {
    category: "hazard",
    family: "impact",
    description: "Hazard impact tags for mental destabilization and movement-limiting effects.",
    tags: [
      { value: "mental_impairment", description: "Impairs judgment, emotions, or perception through fear, confusion, or similar effects." },
      { value: "mobility_impairment", description: "Paralyzes, immobilizes, or otherwise heavily hampers movement." },
    ],
  },
  {
    category: "hazard",
    family: "environmental_danger",
    description: "Hazards defined by recurring elemental or toxic environmental threats.",
    tags: [
      { value: "acid_hazard", description: "Hazard centered on acid, corrosive spray, caustic runoff, or similar corrosive exposure." },
      { value: "cold_hazard", description: "Hazard centered on ice, frost, freezing, blizzards, or other cold exposure." },
      {
        value: "fire_hazard",
        description: "Hazard centered on open fire, flames, burning spread, or explosive ignition.",
        seedRecordKeys: [
          "spore-war-bestiary:eTFchJ8UliMAaKzY",
          "hazards:2GAOUxDfoA48uCWP",
          "hazards:O0qA1ElCOgYGEBtL",
          "fists-of-the-ruby-phoenix-bestiary:BcRxQjtyMNgiEpvb",
          "quest-for-the-frozen-flame-bestiary:XhzGe3CAlugFu8AM",
          "shades-of-blood-bestiary:9I6hHRcVLPbqcZvo",
          "claws-of-the-tyrant-bestiary:3wLksd7BQeyxygyR",
          "stolen-fate-bestiary:UX7QKytewemOnNeX",
          "kingmaker-bestiary:I8pvGB7SiXQ6SnGn",
          "troubles-in-otari-bestiary:aqDFxmLMx6cOnGlx",
          "blood-lords-bestiary:lycxuueclDmiIAOF",
        ],
      },
      { value: "electric_hazard", description: "Hazard centered on lightning, shock, static discharge, or electrical exposure." },
      {
        value: "poison_hazard",
        description: "Hazard centered on poison gas, toxic delivery, or other poisonous exposure.",
        seedRecordKeys: [
          "extinction-curse-bestiary:0fe7PVMIq92fkUJK",
          "extinction-curse-bestiary:wQHcJGJ9rSyFQFPB",
          "prey-for-death-bestiary:2c6GMe3gATc3l7ZV",
          "gatewalkers-bestiary:GJCVwAFKDG91TXok",
          "agents-of-edgewatch-bestiary:rAUaIxp3QFgT3bzl",
          "one-shot-bestiary:E6e8iE0BgIxLYqQZ",
          "extinction-curse-bestiary:b7ADAguVQLHCauWO",
          "gatewalkers-bestiary:F0YvQwAEdIuZ7mQI",
          "hazards:AqK60DreNDtgDb4o",
          "wardens-of-wildwood-bestiary:7jeSUb3zjcsBYfEP",
          "gatewalkers-bestiary:y9W4wnQ5mzs09Px8",
          "outlaws-of-alkenstar-bestiary:QQ2Ci8E2lkxG8QIV",
          "strength-of-thousands-bestiary:JRn1QlBUtlU7xjYR",
          "hazards:A93flWUsot3FmC7t",
        ],
      },
      {
        value: "respiratory_hazard",
        description: "Hazard centered on smoke, choking vapor, breathlessness, or impaired breathing.",
        seedRecordKeys: [
          "gatewalkers-bestiary:F0YvQwAEdIuZ7mQI",
          "gatewalkers-bestiary:y9W4wnQ5mzs09Px8",
          "outlaws-of-alkenstar-bestiary:QQ2Ci8E2lkxG8QIV",
        ],
      },
      { value: "sound_hazard", description: "Hazard centered on sonic force, deafening noise, vibration, or resonant disruption." },
      { value: "water_hazard", description: "Hazard centered on floods, geysers, waves, surges, or other dangerous water exposure." },
    ],
  },
  {
    category: "hazard",
    family: "forced_position",
    description: "Hazards that drop, collapse, or forcibly reposition creatures.",
    tags: [
      { value: "pitfall", description: "Hazard built around a concealed pit, drop, or similar vertical fall trap." },
      { value: "collapse_hazard", description: "Hazard built around collapsing structures, cave-ins, rockfalls, or crumbling ground." },
      { value: "forced_movement", description: "Hazard that pushes, pulls, drags, submerges, or otherwise forcibly repositions creatures." },
    ],
  },
  {
    category: "hazard",
    family: "perception_control",
    description: "Hazards that distort routes, orientation, or the perceived layout of a space.",
    tags: [
      { value: "navigation_disruption", description: "Hazard that confounds routes, loops intruders, or scrambles navigation through distorted perception." },
      { value: "illusion_assault", description: "Hazard that attacks through deceptive reflections, phantasms, or other hostile illusion-driven distortions." },
    ],
  },
  {
    category: "hazard",
    family: "attack_vector",
    description: "Hazards categorized by how their attack is delivered into the scene.",
    tags: [
      { value: "overhead_strike", description: "Hazard that drops, crashes, or attacks from the ceiling or another overhead position." },
      { value: "projectile_emitter", description: "Hazard that fires bolts, beams, jets, sprays, or similar directed emissions from a fixed emitter." },
    ],
  },
];
