import { DerivedTagCatalogEntry } from "../../types.js";

export const SPELL_DERIVED_TAG_CATALOG: DerivedTagCatalogEntry[] = [
  {
    category: "spell",
    family: "infiltration",
    description: "Appearance-changing and social-passing spells.",
    tags: [
      { value: "disguise", description: "Helps alter appearance or impersonate another identity." },
      { value: "social_infiltration", description: "Helps blend into a group or pass under social scrutiny." },
    ],
  },
  {
    category: "spell",
    family: "communication",
    description: "Spells for signaling, telepathy, and message exchange.",
    tags: [
      { value: "signaling", description: "Helps draw attention, mark a location, or coordinate allies." },
      { value: "message_delivery", description: "Sends, stores, or relays actual content across time or distance." },
    ],
  },
  {
    category: "spell",
    family: "reconnaissance",
    description: "Remote-observation and scouting spells.",
    tags: [
      {
        value: "scouting",
        description: "Helps observe at a distance, extend senses, or locate a target.",
        seedRecordKeys: [
          "spells-srd:a5uwCgOe7ayHPtHe",
          "spells-srd:Xrz6wPXDBUr27izR",
          "spells-srd:tj86Rnq3QuQnDtG3",
          "spells-srd:LQzlKbYjZSMFQawP",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "wayfinding",
    description: "Spells that guide direction, route-finding, or destination travel.",
    tags: [
      {
        value: "navigation",
        description: "Helps orient, guide a route, or identify a destination's direction.",
        seedRecordKeys: [
          "spells-srd:ThE5zPYKF4weiljj",
          "spells-srd:ru3YdXajUREbKQDV",
          "spells-srd:F1qxaqsEItmBura2",
          "spells-srd:nnYxDWU3Vzg9WenB",
          "spells-srd:5bTt2CvYHPvaR7QQ",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "traversal",
    description: "Spells that improve movement modes, speed, or practical traversal.",
    tags: [
      {
        value: "mobility",
        description: "Helps move faster, gain movement modes, or traverse terrain more effectively.",
        seedRecordKeys: [
          "spells-srd:b5sGjGlBf58f8jn0",
          "spells-srd:6XscENSWyYRHqK0A",
          "spells-srd:1xM9muPRa8hiyJtI",
          "spells-srd:cCFDnmFB1EGeQUeA",
          "spells-srd:fI20AVwOzJMHXRdo",
          "spells-srd:U0hL0LLaprcnAyzC",
          "spells-srd:Seaah9amXg70RKw2",
          "spells-srd:F1qxaqsEItmBura2",
          "spells-srd:nnYxDWU3Vzg9WenB",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "transformation",
    description: "Spells that alter a creature's body, form, or battle shape.",
    promoteFamilyToTag: true,
    tags: [
      { value: "battle_form", description: "Transforms a creature into a combat-ready form with new statistics or battle-form language." },
      { value: "animal_form", description: "Transforms a creature into an animal, beast, pest, or similar natural form." },
      { value: "elemental_form", description: "Transforms a creature into an elemental form." },
    ],
  },
  {
    category: "spell",
    family: "control",
    description: "Spells that pressure morale, obscure sight, or reshape the battlefield.",
    tags: [
      { value: "fear_pressure", description: "Forces fear, panic, dread, or morale collapse onto a target." },
      { value: "concealment", description: "Makes a creature hard to see, hidden, concealed, or undetected." },
      { value: "line_of_sight_control", description: "Blocks vision, obscures sight lines, or denies clear observation across an area." },
      { value: "battlefield_disruption", description: "Creates area denial, difficult terrain, barriers, or other battlefield obstacles." },
    ],
  },
  {
    category: "spell",
    family: "support",
    description: "Spells that restore, protect, ward, or reinforce allies and targets.",
    tags: [
      {
        value: "healing_support",
        description: "Directly restores hit points or accelerates recovery.",
        seedRecordKeys: [
          "spells-srd:x5rGOmhDRDVQPrnW",
          "spells-srd:9kOI14Jep97TzGO7",
          "spells-srd:2gQYrCPwBmwau26O",
          "spells-srd:2Vkd1IxylPceUAAF",
          "spells-srd:RGBZrVRIEDb2G48h",
          "spells-srd:SnjhtQYexDtNDdEg",
          "spells-srd:szIyEsvihc5e1w8n",
          "spells-srd:tBC1QmB33KWIuBFX",
          "spells-srd:9iJaD4S7ptUeq5vO",
          "spells-srd:ikSb3LRGnrwXJBVX",
          "spells-srd:fAlzXtQAASaJx0mY",
          "spells-srd:IERHT6v4o5ISvuJG",
        ],
      },
      {
        value: "condition_support",
        description: "Delays, suppresses, or removes afflictions and conditions.",
        seedRecordKeys: [
          "spells-srd:EfFMLVbmkBWmzoLF",
          "spells-srd:SnaLVgxZ9ryUFmUr",
          "spells-srd:tf4PMMMzR5xxJDun",
          "spells-srd:ziHDISWkFSwz3pmn",
          "spells-srd:szIyEsvihc5e1w8n",
          "spells-srd:4MOew29Z1oCX8O28",
        ],
      },
      {
        value: "affliction_cleanup",
        description: "Cleanses, cures, neutralizes, or removes disease, poison, curse, or similar afflictions.",
        seedRecordKeys: [
          "spells-srd:SnaLVgxZ9ryUFmUr",
          "spells-srd:tf4PMMMzR5xxJDun",
          "spells-srd:ziHDISWkFSwz3pmn",
          "spells-srd:4MOew29Z1oCX8O28",
        ],
      },
      { value: "escape_support", description: "Helps a creature slip away, break free, flee, or evade pursuit." },
      {
        value: "protective_ward",
        description: "Places a ward, sanctuary, shield, or protective boundary.",
        seedRecordKeys: [
          "spells-srd:lY9fOk1qBDDhBT8s",
          "spells-srd:VrhCpCIQB8PFax77",
          "spells-srd:lJdAvY1sJyEmNDc6",
          "spells-srd:nsQvjNyg4Whw2mek",
          "spells-srd:aAbfKn8maGjJjk2W",
          "spells-srd:DH9Y3RQGWO0GzXGU",
          "spells-srd:4k99nOJudmeNnBTF",
          "spells-srd:CIjj9CU5ekeq1oLT",
          "spells-srd:h47yv6j6x1pUtzlr",
        ],
      },
      { value: "death_prevention", description: "Prevents death, stabilizes the dying, or brings a creature back from the brink." },
      {
        value: "resistance_support",
        description: "Grants resistance or immunity against energy, damage, or hazards.",
        seedRecordKeys: [
          "spells-srd:lJdAvY1sJyEmNDc6",
          "spells-srd:DH9Y3RQGWO0GzXGU",
          "spells-srd:YrzBLPLd3r9m6t1p",
          "spells-srd:e36Z2t6tLdW3RUzZ",
          "spells-srd:9kOI14Jep97TzGO7",
          "spells-srd:NzXpEzcZAjuDTZjK",
          "spells-srd:IHUs4qn27RrdFQ5Y",
          "spells-srd:vQMAdnIwnV9prPiG",
        ],
      },
      { value: "temporary_hp_support", description: "Grants temporary Hit Points or similar buffer protection instead of restoring lost Hit Points." },
    ],
  },
  {
    category: "spell",
    family: "attrition",
    description: "Spells that inflict ongoing harm through lingering persistent damage.",
    tags: [
      {
        value: "persistent_damage",
        description: "Directly inflicts persistent damage or grants attacks that reliably impose persistent damage.",
        seedRecordKeys: [
          "spells-srd:IT1aaqDBAISlHDUV",
          "spells-srd:f8hRqLJaxBVhF1u0",
          "spells-srd:9h9YCncqah6VNsKf",
          "spells-srd:gISYsBFby1TiXfBt",
          "spells-srd:XEhzFKNTSARsofav",
          "spells-srd:OJ91rm1FkJSlf3nk",
          "spells-srd:EPTmSiURVp2ldkVB",
          "spells-srd:dKWc83KKiXoIJkhp",
          "spells-srd:NacrNSvfODxpZena",
          "spells-srd:7uL4XhHpxZpgNJPh",
          "spells-srd:3qx1axryNbl97ker",
          "spells-srd:hoR6w8BqX2F35Tdx",
          "spells-srd:ES6FkwXXqYr4ujQH",
          "spells-srd:TaaMEYdZXQXF0Sks",
          "spells-srd:CXpOlv2ZZq2jVbRX",
          "spells-srd:VXUrO8TwRqBpNzdU",
          "spells-srd:V4IpjSlefultlOuY",
          "spells-srd:S708JF3E0kuhuRzG",
          "spells-srd:eidmNlfl2DUVIclc",
          "spells-srd:vGMbpV7GWIFPNUaZ",
          "spells-srd:g1eY1vN44mgluE33",
          "spells-srd:bVvGpSOg2WaTUItS",
          "spells-srd:Z3kJty995FkrsZRb",
          "spells-srd:1hLxZznnA2kvXlIt",
          "spells-srd:f9m9DayyGy3meqUX",
          "spells-srd:AWxS2lr86qNNQVDT",
          "spells-srd:MFPvs0ARxtThYPFq",
          "spells-srd:A16eFTRh82xIjMu8",
          "spells-srd:PrlR2sLWeiuTcPF2",
          "spells-srd:eexkxcqnkXazsGfK",
          "spells-srd:Ru9v8U9IRk3LtWx8",
          "spells-srd:MLYTWHfewOpI3Cz7",
          "spells-srd:bIz6QnUIxu5Z7vEH",
          "spells-srd:p6ebe2PliRkGbmiV",
          "spells-srd:WV2aMNN9DO5ZBjSv",
          "spells-srd:b6AQvzs8EotmlK56",
          "spells-srd:5KmyO4YSGEAUdgAS",
          "spells-srd:3VxVbZqIRvpKkg3O",
          "spells-srd:dgMauNKWeRIu8pMN",
          "spells-srd:MPxbKoR54gkYkqLO",
          "spells-srd:k34hDOfIIMAxNL4a",
          "spells-srd:v4KzRPol5XQOOmk0",
          "spells-srd:3GXU3ugrwLv0P7AH",
          "spells-srd:6DfLZBl8wKIV03Iq",
          "spells-srd:sUvTGELaggrBSgGm",
          "spells-srd:Vbj8bTQ1nwrOBbYF",
          "spells-srd:3ZxaIw1FOOocJboH",
          "spells-srd:BWvGBx51RevizICD",
          "spells-srd:3A3ueS9Q0s3U8KXE",
          "spells-srd:R8bqnYiThB6MYTxD",
          "spells-srd:D7ZEhTNIDWDLC2J4",
          "spells-srd:0AZOIMRvZtePuGOw",
          "spells-srd:0fYE64odlKqISzft",
          "spells-srd:xn0V2HDrmDWNzPEt",
          "spells-srd:I2IgZu4Rd2dz0J6v",
          "spells-srd:5QD75UbyB5EiG3yz",
          "spells-srd:r3NeUnsgt9mS03Sn",
          "spells-srd:1Yoipc5jNcMehtEW",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "expedition",
    description: "Spells that support travel, survival, and aquatic operations.",
    tags: [
      { value: "aquatic_support", description: "Helps with swimming, underwater breathing, water-surface travel, or other aquatic movement." },
      { value: "sustenance", description: "Provides food, water, rations, or practical nourishment for travel and survival." },
      { value: "field_shelter", description: "Creates shelter, refuge, or a protected resting place in the field." },
    ],
  },
  {
    category: "spell",
    family: "tempo",
    description: "Spells that improve action economy or accelerate allies.",
    tags: [
      { value: "quickened_support", description: "Grants extra actions, quickened condition benefits, or similar action-economy acceleration." },
      {
        value: "initiative_support",
        description: "Improves initiative, pre-combat readiness, or the party's opening tempo before the first turn.",
        seedRecordKeys: [
          "spells-srd:EUMjrJJwSgsqNidi",
          "spells-srd:dqaCLzINHBiKjh4J",
          "spells-srd:BAu5AgqoO556clyK",
          "spells-srd:LTUaK3smfm5eDiFK",
          "spells-srd:I8CPe9Pp7GABqOyB",
          "spells-srd:l6zjNysNedpJcmDT",
          "spells-srd:MLdMUOdwSKegOGlo",
          "spells-srd:ovx7O2FHvkjXhMcA",
          "spells-srd:M5dp7ILSCKID9fDK",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "summoner_support",
    description: "Spells that specifically protect, enhance, or reposition an eidolon.",
    tags: [
      {
        value: "eidolon_support",
        description: "Directly benefits an eidolon or the summoner-eidolon bond.",
        seedRecordKeys: [
          "spells-srd:HStu2Yhw3iQER9tY",
          "spells-srd:CR8OKDbeFJoZbOCu",
          "spells-srd:hW9pgce6vTme61g1",
          "spells-srd:cwXiKPkZrIupjwlQ",
          "spells-srd:vb2dFNtbofJ7A9BW",
          "spells-srd:AfOpnnwdZwHi2Tnc",
          "spells-srd:TYbCj4dgXDOZou9k",
          "spells-srd:lV8FkHZtzZu7Cy6j",
          "spells-srd:lOZhcvtej10TqlQm",
          "spells-srd:PIdXUPtE6ZGpFpXV",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "magic_interference",
    description: "Spells that disrupt, dispel, or suppress magic.",
    tags: [
      {
        value: "countermagic",
        description: "Counteracts, dispels, suppresses, or shuts down magic.",
        seedRecordKeys: [
          "spells-srd:My7FvAoLYgGDDBzy",
          "spells-srd:EoKBlgf6Smt8opaU",
          "spells-srd:C2w3YfBKjIRS07DP",
          "spells-srd:pfFxj4NI5KwO119I",
          "spells-srd:AnWCohzPgK4L9GVl",
          "spells-srd:RCbLd7dfquHnuvrZ",
          "spells-srd:h47yv6j6x1pUtzlr",
        ],
      },
    ],
  },
  {
    category: "spell",
    family: "security",
    description: "Area-warning and intrusion-alert spells.",
    tags: [
      { value: "alarm", description: "Alerts you or others when a watched area, threshold, or ward is crossed." },
    ],
  },
  {
    category: "spell",
    family: "impact",
    description: "Spells that impair minds or senses, forcibly reposition targets, or trap them in place.",
    tags: [
      { value: "mental_impairment", description: "Impairs thought, composure, or agency through fear, confusion, or similarly hostile mental effects." },
      { value: "sensory_impairment", description: "Blinds, deafens, or otherwise directly suppresses a creature's senses." },
      { value: "forced_movement", description: "Pushes, pulls, drags, or otherwise repositions a target against its will." },
      { value: "restraint_capture", description: "Restrains, immobilizes, entangles, or traps a target in place." },
    ],
  },
];
