import assert from 'node:assert/strict';
import { readFile, mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import test from 'node:test';
import { generate, generateInput } from '../src/generation/generate.js';
import { artifactFiles } from '../src/generation/generated-files.js';
import { defaultCache } from '../src/generation/pinned-source.js';
import type { GenerationInput } from '../src/generation/generation-input.js';

test('freshness covers the whole output set and removes only stale generated files', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'atlas-generation-output-'));
  const input: GenerationInput = {
    source: {system_version: 'fixture', source_digest: 'fixture', input_file_count: 1, git_commit: null, git_clean: null},
    nodes: [{id: 'primitive:string', kind: 'primitive', value: 'string'}],
    selection: [{name: 'FixtureFields', declaration: 'fixture', module: 'fixture', deferred: [],
      fields: [{name: 'label', ref: 'primitive:string', optional: false, nullable: false,
        undefinedAllowed: false, forbidden: false, declaredAt: []}]}],
  };
  try {
    const outDir = path.join(directory, 'output with spaces');
    const run = (check = false) => generateInput(input, outDir, check);
    await run();
    await run(true);
    await writeFile(path.join(outDir, 'obsolete.rs'), '// Generated by dev-tools/source-contracts/src/generation/generate.ts; do not edit.\n');
    await assert.rejects(run(true), /stale/);
    await run();
    assert.equal((await artifactFiles(outDir)).includes('obsolete.rs'), false);
    await writeFile(path.join(outDir, 'notes.txt'), 'human authored');
    const before = await readFile(path.join(outDir, 'fixture.rs'), 'utf8');
    await assert.rejects(run(), /Unmanaged file/);
    assert.equal(await readFile(path.join(outDir, 'fixture.rs'), 'utf8'), before);
    await rm(path.join(outDir, 'notes.txt'));
    await rm(path.join(outDir, 'mod.rs'));
    await assert.rejects(run(true), /missing/);
    await mkdir(path.join(outDir, 'mod.rs'));
    await assert.rejects(run(), /not a regular file/);
    assert.equal(await readFile(path.join(outDir, 'fixture.rs'), 'utf8'), before);
  } finally { await rm(directory, { recursive: true, force: true }); }
});

test('overlapping generation paths are rejected before source acquisition', async () => {
  await assert.rejects(generate({outDir: defaultCache}), /separate/);
  await assert.rejects(generate({outDir: '/fixture/source', source: '/fixture/source'}), /separate/);
});
