/** Synthetic regression graph, compiled using the real Rust source primitives. */
import type {GraphField,GraphNode} from './contracts.js';
import type {GenerationInput} from './generation-input.js';
import {authoredRuleInputs} from './rule-inputs.js';

export function recursiveFixture():GenerationInput {
  const field=(name:string,ref:string,optional=false,nullable=false):GraphField=>({name,ref,optional,nullable,undefinedAllowed:false,forbidden:false,declaredAt:[]});
  const object=(id:string,fields:GraphField[]):GraphNode=>({id,name:id,kind:'object',fields,indexSignatures:[]});
  const nodes:GraphNode[]=[{id:'primitive:string',kind:'primitive',value:'string'},
    {id:'primitive:number',kind:'primitive',value:'number'},{id:'primitive:null',kind:'primitive',value:'null'},
    {id:'primitive:never',kind:'primitive',value:'never'},
    {id:'Yes',name:'Yes',kind:'literal',value:true},{id:'One',name:'One',kind:'literal',value:1},
    {id:'A',name:'A',kind:'literal',value:'a'},{id:'B',name:'B',kind:'literal',value:'b'},
    {id:'NullableA',kind:'union',members:['A','primitive:null']},
    object('Node',[field('next','Node',true),field('expression','Expr',true)]),
    {id:'Expr',name:'Expr',kind:'union',members:['primitive:string','Node']},
    {id:'Empty',kind:'tuple',elements:[],readonly:false},
    {id:'Single',kind:'tuple',elements:[{ref:'primitive:string',optional:false,rest:false}],readonly:false},
    object('Left',[field('type','NullableA',false,true),field('if','Yes',true)]),object('Right',[field('type','B')]),
    {id:'Discriminated',name:'Discriminated',kind:'union',members:['Left','Right']},
    object('Optional',[field('value','primitive:string',true)]),object('Required',[field('value','primitive:string')]),object('Other',[field('other','primitive:string')]),
    {id:'Strict',name:'Strict',kind:'union',members:['Required','Other']},
    {id:'Loose',name:'Loose',kind:'union',members:['Optional','Other']},
    object('BoolConsumer',[field('enabled','Yes')]),
    {id:'Harm',name:'Harm',kind:'literal',value:'harm'},{id:'Heal',name:'Heal',kind:'literal',value:'heal'},
    {id:'NoFonts',kind:'array',element:'primitive:never',readonly:false},
    {id:'HarmFont',kind:'tuple',elements:[{ref:'Harm',optional:false,rest:false}],readonly:false},
    {id:'HealFont',kind:'tuple',elements:[{ref:'Heal',optional:false,rest:false}],readonly:false},
    {id:'BothFonts',kind:'tuple',elements:[{ref:'Harm',optional:false,rest:false},{ref:'Heal',optional:false,rest:false}],readonly:false},
    {id:'DivineFonts',name:'DivineFonts',kind:'union',members:['NoFonts','HarmFont','HealFont','BothFonts']},
    {id:'TupleExpr',name:'TupleExpr',kind:'union',members:['primitive:string','NestedTuple']},
    {id:'NestedTuple',kind:'tuple',elements:[{ref:'TupleExpr',optional:false,rest:false}],readonly:false},
    {id:'No',kind:'literal',value:false},
    {id:'NumericScalar',kind:'union',members:['primitive:number','primitive:string']},
    {id:'LogicalScalar',kind:'union',members:['No','primitive:string','Yes']},
    {id:'NumericBoolean',kind:'union',members:['Yes','primitive:number','No']},
    {id:'AnyScalar',kind:'union',members:['No','primitive:number','primitive:string','Yes']},
    {id:'RestrictedScalar',kind:'union',members:['Yes','primitive:number']},
    {id:'ScalarPair',kind:'tuple',elements:[{ref:'AnyScalar',optional:false,rest:false},{ref:'primitive:number',optional:false,rest:false}],readonly:false},
    object('ScalarEnvelope',[field('numeric','NumericScalar'),field('logical','LogicalScalar'),field('numeric_boolean','NumericBoolean'),field('any_scalar','AnyScalar'),field('restricted','RestrictedScalar')]),
    object('ScalarConsumer',[field('pair','ScalarPair')]),
    ...(['any','unknown','object','non-nullish'] as const).map(domain=>({id:'Open:'+domain,kind:'open' as const,domain})),
    {id:'UnknownMap',kind:'object',fields:[],indexSignatures:[{key:'primitive:string',value:'Open:unknown',readonly:false}]},
    {id:'OpenBag',name:'OpenBag',kind:'object',fields:[field('label','primitive:string'),
      {...field('retired','primitive:never'),forbidden:true}],indexSignatures:[{key:'primitive:string',value:'Open:unknown',readonly:false}]},
    {id:'NumberBag',name:'NumberBag',kind:'object',fields:[field('fixed','primitive:number')],indexSignatures:[{key:'primitive:string',value:'primitive:number',readonly:false}]},
    {id:'ConstrainedBag',name:'ConstrainedBag',kind:'object',fields:[field('fixed','primitive:string')],indexSignatures:[{key:'primitive:string',value:'A',readonly:false}]},
    {id:'RecursiveBag',name:'RecursiveBag',kind:'object',fields:[field('child','RecursiveBag',true)],indexSignatures:[{key:'primitive:string',value:'RecursiveBag',readonly:false}]},
    {id:'primitive:undefined',kind:'primitive',value:'undefined'},
    {id:'MaybeNumber',kind:'union',members:['primitive:number','primitive:undefined']},
    {id:'MaybeNumberMap',kind:'object',fields:[],indexSignatures:[{key:'primitive:string',value:'MaybeNumber',readonly:false}]},
    {id:'ObjectUnion',name:'ObjectUnion',kind:'union',members:['primitive:string','Open:object']},
    {id:'OpenTuple',kind:'tuple',elements:[{ref:'Open:unknown',optional:false,rest:false}],readonly:false},
    {id:'OpenTupleUnion',name:'OpenTupleUnion',kind:'union',members:['primitive:string','OpenTuple']},
    object('KnownObject',[field('label','primitive:string')]),
    {id:'OverlappingOpen',name:'OverlappingOpen',kind:'union',members:['Open:object','KnownObject']},
    object('OpenConsumer',[field('bag','OpenBag'),field('payload','Open:object')]),
    {id:'Color',name:'Color',kind:'template',text:['#',''],parameters:['primitive:string']},
    {id:'Png',kind:'template',text:['','.png'],parameters:['primitive:string']},
    {id:'Svg',kind:'template',text:['','.svg'],parameters:['primitive:string']},
    {id:'ImagePath',name:'ImagePath',kind:'union',members:['Png','Svg']},
    {id:'Uuid',name:'Uuid',kind:'template',text:['Actor.','.Item.',''],parameters:['primitive:string','primitive:string']},
    {id:'TemplatePair',kind:'tuple',elements:[{ref:'Color',optional:false,rest:false}],readonly:false},
    {id:'TemplateTupleUnion',name:'TemplateTupleUnion',kind:'union',members:['TemplatePair','primitive:number']},
    {id:'MixedTemplate',name:'MixedTemplate',kind:'union',members:['Color','KnownObject']},
    object('ColorTag',[field('tag','Color')]),object('UuidTag',[field('tag','Uuid')]),
    {id:'TemplateTagged',name:'TemplateTagged',kind:'union',members:['ColorTag','UuidTag']},
    {id:'OverlappingTemplates',name:'OverlappingTemplates',kind:'union',members:['Uuid',
      'ActorPrefix']},
    {id:'ActorPrefix',kind:'template',text:['Actor.',''],parameters:['primitive:string']},
    {id:'Generic:first',name:'SourceFromSchema',kind:'object',fields:[field('first','primitive:string')],indexSignatures:[],typeArguments:[{expression:'FirstSchema',declaredAt:[]}]},
    {id:'Generic:second',name:'SourceFromSchema',kind:'object',fields:[field('second','primitive:number')],indexSignatures:[],typeArguments:[{expression:'SecondSchema',declaredAt:[]}]},
    {id:'Generic:equal',name:'SourceFromSchema',kind:'object',fields:[field('first','primitive:string')],indexSignatures:[],typeArguments:[{expression:'EquivalentSchema',declaredAt:[]}]},
    {id:'Generic:anonymous',name:'SourceFromSchema',kind:'object',fields:[field('anonymous','primitive:number')],indexSignatures:[],typeArguments:[{expression:'{ anonymous: NumberField }',declaredAt:[]}]},
    {id:'GenericUnion',name:'GenericUnion',kind:'union',members:['Generic:first','Generic:second']},
    object('GenericConsumer',[field('repeated','Generic:equal'),field('anonymous','Generic:anonymous')]),
    object('TemplateConsumer',[field('color','Color'),field('image','ImagePath')]),
    object('MappedFields',[field('_id','primitive:string'),field('greater-darkvision','primitive:number'),field('self','primitive:string'),field('1st','primitive:string')]),
    {id:'StringMap',kind:'object',fields:[],indexSignatures:[{key:'primitive:string',value:'primitive:string',readonly:false}]},
    {id:'IntersectionBag',name:'IntersectionBag',kind:'intersection',members:['ConstrainedBag','StringMap'],
      fields:[field('fixed','primitive:string')],indexSignatures:[{key:'primitive:string',value:'A',readonly:false}]},
    {id:'IntersectionMap',name:'IntersectionMap',kind:'intersection',members:['UnknownMap','MaybeNumberMap'],
      fields:[],indexSignatures:[{key:'primitive:string',value:'primitive:number',readonly:false}]},
    object('RecursiveIntersectionFields',[field('next','RecursiveIntersection',true)]),
    {id:'RecursiveIntersectionIndex',kind:'object',fields:[],indexSignatures:[{key:'primitive:string',value:'RecursiveIntersection',readonly:false}]},
    {id:'RecursiveIntersection',name:'RecursiveIntersection',kind:'intersection',members:['RecursiveIntersectionFields','RecursiveIntersectionIndex'],
      fields:[field('next','RecursiveIntersection',true)],indexSignatures:[{key:'primitive:string',value:'RecursiveIntersection',readonly:false}]}];
  nodes.push({id:'Strings',kind:'array',element:'primitive:string',readonly:false},
    object('AuthoredArraySchema',[field('selector','Strings'),field('selectors','Strings')]));
  const authored=authoredRuleInputs({format:'atlas-source-type-graph/v1',typescript:'fixture',complete:true,status:'complete',
    nodes,diagnostics:[],projectDiagnostics:{selected:[],unrelated:[]},roots:[{file:'fixture',name:'AuthoredArraySchema',ruleKey:'FlatModifier',ref:'AuthoredArraySchema',arrayInputs:[
      {field:'selector',arrayRef:'Strings',elementRef:'primitive:string',fieldClass:'ArrayField',declaredAt:[]},
      {field:'selectors',arrayRef:'Strings',elementRef:'primitive:string',fieldClass:'StrictArrayField',declaredAt:[]}]}]});
  return {source:{system_version:'fixture',source_digest:'fixture',input_file_count:1,git_commit:null,git_clean:null},nodes:authored.graph.nodes,
    selection:[...['Node','Expr','Empty','Single','Discriminated','Strict','Loose','Yes','One','DivineFonts'].map(name=>({name,declaration:name,valueRef:name,module:'common',fields:[],deferred:[]})),
      {name:'TupleEntry',declaration:'NestedTuple',valueRef:'NestedTuple',module:'common',fields:[],deferred:[]},
      ...['TupleExpr','ScalarEnvelope'].map(name=>({name,declaration:name,valueRef:name,module:'common',fields:[],deferred:[]})),
      {name:'ScalarPair',declaration:'ScalarPair',valueRef:'ScalarPair',module:'common',fields:[],deferred:[]},
      ...['OpenBag','NumberBag','ConstrainedBag','RecursiveBag','UnknownMap','MaybeNumberMap','ObjectUnion','OpenTupleUnion','OverlappingOpen'].map(name=>({name,declaration:name,valueRef:name,module:'common',fields:[],deferred:[]})),
      ...[{name:'AnyValue',ref:'Open:any'},{name:'UnknownValue',ref:'Open:unknown'},{name:'ObjectValue',ref:'Open:object'},{name:'NonNullishValue',ref:'Open:non-nullish'}].map(({name,ref})=>({name,declaration:ref,valueRef:ref,module:'common',fields:[],deferred:[]})),
      ...['Color','ImagePath','Uuid','TemplateTupleUnion','MixedTemplate','TemplateTagged','OverlappingTemplates','GenericUnion'].map(name=>({name,declaration:name,valueRef:name,module:'common',fields:[],deferred:[]})),
      ...['MappedFields','IntersectionBag','IntersectionMap','RecursiveIntersection'].map(name=>({name,declaration:name,valueRef:name,module:'common',fields:[],deferred:[]})),
      ...['BoolConsumer','ScalarConsumer','OpenConsumer','GenericConsumer','TemplateConsumer'].map(name=>({name,declaration:name,valueRef:name,module:'consumer',fields:[],deferred:[]})),
      {name:'AuthoredArrays',declaration:'AuthoredArraySchema',valueRef:authored.graph.roots[0].ref!,module:'consumer',fields:[],deferred:[]}]};
}
