import type { GraphNode } from './contracts.js';
import { validateInput, type GenerationInput } from './generation-input.js';

interface Owner { type: string; parser: string; module?: string; allocated?:string; inline?:boolean; typeDependencies?:Owner[] }
interface RustModule {
  declarations: (string | (()=>string))[]; imports: Map<string, Set<string>>; types: Set<string>; typeDependencies:Set<Owner>;
  helpers: Set<string>; object: boolean; number: boolean; serialize: boolean;
}
export const generatedHeader = '// Generated by scripts/source-contracts/generate.ts; do not edit.';

const pascal = (name: string) => name.replace(/[^A-Za-z0-9]+/g, ' ').split(/\s+/)
  .filter(Boolean).map(word => word[0].toUpperCase() + word.slice(1)).join('');
const snake = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
const rustString = (text: string) => JSON.stringify(text).replace(/\\u([0-9a-f]{4})/gi, '\\u{$1}');
const scalarOrder = ['string', 'number', 'boolean'];
const atomicOrder = [...scalarOrder, 'object', 'non-nullish', 'unknown', 'any'];
const atomicDomain = (node: GraphNode): string | undefined => node.kind === 'primitive' && scalarOrder.includes(node.value)
  ? node.value : node.kind === 'open' ? node.domain : undefined;

/** Emit only supported, reachable value shapes. SourcePresence retains pre-default states. */
export function generateRustModules(input: GenerationInput): Record<string, string> {
  validateInput(input);
  const nodes = new Map(input.nodes.map(node => [node.id, node]));
  if (nodes.size !== input.nodes.length) throw new Error('Duplicate generation node identities');
  const modules = new Map<string, RustModule>();
  const moduleFor = (name: string) => {
    if (!modules.has(name)) modules.set(name, { declarations: [], imports: new Map(), types: new Set(), typeDependencies:new Set(),
      helpers: new Set(), object: false, number: false, serialize: false });
    return modules.get(name)!;
  };
  const owners = new Map<string, Owner>();
  const usedNames = new Set<string>();
  const lookup = (id: string): GraphNode => {
    const node = nodes.get(id);
    if (!node) throw new Error(`Missing generation node: ${id}`);
    return node;
  };
  const openTraitArrays = new Set(input.openTraitArrays ?? []);
  const stringVocabulary = (ref: string, seen = new Set<string>()): boolean => {
    if (seen.has(ref)) return false;
    const node = lookup(ref); const next = new Set(seen).add(ref);
    return node.kind === 'primitive' && node.value === 'string' || node.kind === 'literal' && typeof node.value === 'string'
      || node.kind === 'union' && node.members.length > 0 && node.members.every(ref => stringVocabulary(ref, next));
  };
  for (const ref of openTraitArrays) {
    const node = lookup(ref);
    if (node.kind !== 'array' || !stringVocabulary(node.element)) throw new Error(`Open trait policy requires a string vocabulary array: ${ref}`);
  }
  const normalized = (id: string, seen = new Set<string>()): GraphNode => {
    if(seen.has(id)) throw new Error(`Recursive alias has no value anchor: ${id}`);
    const node = lookup(id);
    if (node.kind !== 'union') return node;
    let members = node.members.filter(id => { const member = lookup(id); return !['primitive:null', 'primitive:undefined', 'primitive:never'].includes(id)
      && !(member.kind === 'intersection' && member.impossible); });
    if (members.length === 1) return normalized(members[0], new Set(seen).add(id));
    if ([true,false].every(value=>members.some(id=>{const member=lookup(id);return member.kind==='literal' && member.value===value;}))) {
      const boolean:GraphNode={ id: 'primitive:boolean', kind: 'primitive', value: 'boolean' };
      nodes.set(boolean.id,boolean);
      members=[...new Set([...members.filter(id=>{const member=lookup(id);return member.kind!=='literal' || typeof member.value!=='boolean';}),boolean.id])];
      if(members.length===1)return boolean;
    }
    if(members.every(id=>atomicDomain(lookup(id))!==undefined))
      members.sort((a,b)=>atomicOrder.indexOf(atomicDomain(lookup(a))!)-atomicOrder.indexOf(atomicDomain(lookup(b))!));
    return { ...node, members };
  };
  const valueRefs=(node:GraphNode):string[]=>node.kind==='union'?node.members:node.kind==='array'?[node.element]
    :node.kind==='tuple'?node.elements.map(element=>element.ref)
    :node.kind==='object'?[...node.fields.filter(field=>!field.forbidden).map(field=>field.ref),...node.indexSignatures.map(index=>index.value)]
    :node.kind==='intersection'?[...node.members,...node.fields.filter(field=>!field.forbidden).map(field=>field.ref)]:[];
  const anchors=new Set<string>(),visited=new Set<string>(),active:string[]=[];
  const findCycles=(ref:string)=>{
    const node=normalized(ref);const start=active.indexOf(node.id);
    if(start>=0){for(const id of active.slice(start)){const node=normalized(id);if(node.kind==='object' && (!node.indexSignatures.length || node.fields.length) || node.kind==='intersection' || node.kind==='union')anchors.add(id);}return;}
    if(visited.has(node.id))return;active.push(node.id);valueRefs(node).forEach(findCycles);active.pop();visited.add(node.id);
  };
  input.selection.forEach(root=>{root.fields.filter(field=>!field.forbidden).forEach(field=>findCycles(field.ref));if(root.valueRef)findCycles(root.valueRef);});
  const validatedAnchors=new Set<string>();
  const signature = (node: GraphNode, ancestors = new Set<string>(),canonical=true): string => {
    if(canonical && anchors.has(node.id)) {
      if(!validatedAnchors.has(node.id)){signature(node,new Set(),false);validatedAnchors.add(node.id);}
      return JSON.stringify(['recursive',node.id]);
    }
    if (ancestors.has(node.id)) return JSON.stringify(['recursive',node.id]);
    const next = new Set([...ancestors, node.id]);
    const child = (ref: string) => signature(normalized(ref), next,canonical);
    const collectionChild = (ref: string, indexed = false) => {
      const entry = lookup(ref);
      if (entry.kind === 'union' && entry.members.some(ref => ref === 'primitive:null' || !indexed && ref === 'primitive:undefined'))
        throw new Error(`Nullable collection entries need a separate model: ${ref}`);
      return child(ref);
    };
    if (node.kind === 'object' || node.kind === 'intersection') {
      if (node.kind === 'intersection' && node.impossible) throw new Error(`Impossible selected intersection: ${node.id}`);
      if (node.kind === 'object' && node.indexSignatures.length) {
        if (node.indexSignatures.length !== 1 || node.indexSignatures[0].key !== 'primitive:string')
          throw new Error(`Selected index signature is unsupported: ${node.id}`);
        const indexed = collectionChild(node.indexSignatures[0].value, true);
        if (!node.fields.length) return `map:${indexed}`;
        return JSON.stringify(['indexed-object',
          node.fields.filter(field => !field.forbidden).map(field => [field.name, child(field.ref)]),
          indexed, node.fields.filter(field => field.forbidden).map(field => field.name)]);
      }
      if (node.kind === 'intersection') for (const member of node.members) {
        const constituent = normalized(member);
        if (constituent.kind !== 'object' && constituent.kind !== 'intersection')
          throw new Error(`Unsupported selected intersection member: ${member}`);
        if (constituent.kind === 'object' && constituent.indexSignatures.length)
          throw new Error(`Selected intersection index signature is unsupported: ${member}`);
        child(member); // Resolved fields do not encode index-signature constraints.
      }
      return JSON.stringify(node.fields.filter(field => !field.forbidden).map(field => [field.name, child(field.ref)]));
    }
    if (node.kind === 'union') return JSON.stringify(node.members.map(ref=>{
      const member=normalized(ref);
      return JSON.stringify([child(ref),member.kind==='object' || member.kind==='intersection'
        ? member.fields.map(field=>[field.name,field.optional,field.nullable,field.undefinedAllowed,field.forbidden]) : []]);
    }).sort());
    if (node.kind === 'tuple') {
      if(node.elements.some(element=>element.optional || element.rest)) throw new Error(`Optional/rest tuples are unsupported: ${node.id}`);
      return JSON.stringify(['tuple',...node.elements.map(element=>collectionChild(element.ref))]);
    }
    if (node.kind === 'array') return `array:${openTraitArrays.has(node.id) ? JSON.stringify(['primitive', 'string']) : collectionChild(node.element)}`;
    if (node.kind === 'primitive' || node.kind === 'literal') return JSON.stringify([node.kind, node.value]);
    if (node.kind === 'open') {
      if (node.fields?.length || node.indexSignatures?.length || !['any','unknown','object','non-nullish'].includes(node.domain))
        throw new Error(`Unsupported structured open domain: ${node.id}`);
      return JSON.stringify(['open', node.domain]);
    }
    throw new Error(`Unsupported selected construct: ${node.id} (${node.kind})`);
  };
  // Rust layout follows inline value edges; Vec and SourceMap already break cycles.
  const inlineRefs = (ref:string): string[] => {
    const node=normalized(ref);
    if(node.kind==='union') return node.members;
    if(node.kind==='tuple') return node.elements.map(element=>element.ref);
    if((node.kind==='object' && (!node.indexSignatures.length || node.fields.length)) || node.kind==='intersection')
      return node.fields.filter(field=>!field.forbidden).map(field=>field.ref);
    return [];
  };
  const reaches = (from:string,to:string,seen=new Set<string>()):boolean => {
    from=normalized(from).id;to=normalized(to).id;
    if(from===to)return true;if(seen.has(from))return false;seen.add(from);
    return inlineRefs(from).some(ref=>reaches(ref,to,seen));
  };
  const residualReaches = (from:string,to:string,seen=new Set<string>()):boolean => {
    const node=normalized(from);to=normalized(to).id;
    if(node.id===to)return true;if(seen.has(node.id))return false;seen.add(node.id);
    return inlineRefs(node.id).filter(ref=>node.kind!=='union' || !reaches(ref,node.id))
      .some(ref=>residualReaches(ref,to,seen));
  };
  const boxedEdge = (parent:GraphNode,ref:string):boolean => parent.kind==='union'
    ? reaches(ref,parent.id) : residualReaches(ref,parent.id);
  const rustField = (name:string):string => {
    if(!/^[a-z][a-z0-9_]*$/.test(name) || ['self','super','crate'].includes(name)) throw new Error(`Invalid Rust field name: ${name}`);
    return ['type','mod','use','ref','match','struct','enum','pub','fn','const','static','let','loop','move','where','trait','impl','async','await','dyn','in','as','if','else','return','break','continue','mut','unsafe','extern','for','while','abstract','become','box','do','final','macro','override','priv','try','typeof','unsized','virtual','yield','gen'].includes(name) ? `r#${name}` : name;
  };
  const valueKinds=(ref:string,seen=new Set<string>()):Set<string>=>{
    const node=normalized(ref);if(seen.has(node.id))return new Set();const next=new Set(seen).add(node.id);
    if(node.kind==='union')return new Set(node.members.flatMap(ref=>[...valueKinds(ref,next)]));
    if(node.kind==='array' || node.kind==='tuple')return new Set(['Array']);
    if(node.kind==='object' || node.kind==='intersection')return new Set(['Object']);
    if(node.kind==='literal')return new Set([typeof node.value==='string'?'String':typeof node.value==='number'?'Number':'Boolean']);
    if(node.kind==='primitive')return new Set([{string:'String',number:'Number',boolean:'Boolean'}[node.value]??'Null']);
    if(node.kind==='open')return new Set(node.domain==='object'?['Array','Object']
      :node.domain==='non-nullish'?['Boolean','Number','String','Array','Object']:['Null','Boolean','Number','String','Array','Object']);
    throw new Error(`Unsupported union value kind: ${node.id}`);
  };
  const guard = (ref:string,v:string,seen=new Set<string>()):string => {
    const node=normalized(ref);
    if(seen.has(node.id))throw new Error(`Recursive union identity needs a structural anchor: ${node.id}`);
    const next=new Set(seen).add(node.id);
    if(node.kind==='primitive')return `matches!(${v}, SourceValue::${{string:'String',number:'Number',boolean:'Boolean'}[node.value] ?? 'Null'}(_))`;
    if(node.kind==='open')return node.domain==='object'?`matches!(${v}, SourceValue::Array(_) | SourceValue::Object(_))`
      :node.domain==='non-nullish'?`!matches!(${v}, SourceValue::Null)`:'true';
    if(node.kind==='literal') {
      if(typeof node.value==='string')return `matches!(${v}, SourceValue::String(value) if value == ${rustString(node.value)})`;
      if(typeof node.value==='boolean')return `matches!(${v}, SourceValue::Boolean(value) if ${node.value?'*value':'!*value'})`;
      return `matches!(${v}, SourceValue::Number(value) if value.as_f64() == Some(${node.value.toFixed(1)}))`;
    }
    if(node.kind==='union')return '('+node.members.map(ref=>guard(ref,v,next)).join(' || ')+')';
    if(node.kind==='tuple')return `matches!(${v}, SourceValue::Array(values) if values.len() == ${node.elements.length}${node.elements.map((element,index)=>{
      const child=normalized(element.ref),position=`&values[${index}]`;
      const scalar=child.kind==='literal' || child.kind==='primitive' || child.kind==='union' && child.members.every(ref=>['literal','primitive'].includes(normalized(ref).kind));
      return ` && ${scalar?guard(element.ref,position,next):`matches!(${position}, ${[...valueKinds(element.ref)].sort().map(kind=>`SourceValue::${kind}(_)`).join(' | ')})`}`;
    }).join('')})`;
    if(node.kind==='array') {
      const element=normalized(node.element);
      if(element.kind==='primitive' && element.value==='never')return `matches!(${v}, SourceValue::Array(values) if values.is_empty())`;
      const scalar=element.kind==='literal' || element.kind==='primitive' || element.kind==='union' && element.members.every(ref=>['literal','primitive'].includes(normalized(ref).kind));
      return scalar?`matches!(${v}, SourceValue::Array(values) if values.iter().all(|v| ${guard(node.element,'v',next)}))`:`matches!(${v}, SourceValue::Array(_))`;
    }
    if(node.kind==='object' || node.kind==='intersection') {
      const required=node.fields.filter(field=>!field.forbidden && !field.optional && !field.undefinedAllowed);
      const literal=required.filter(field=>{const child=normalized(field.ref);return child.kind==='literal'
        || child.kind==='union' && child.members.every(ref=>normalized(ref).kind==='literal');});
      return `union_object(${v}, &[${required.map(field=>rustString(field.name)).join(', ')}])`
        +literal.map(field=>` && union_member(${v}, ${rustString(field.name)}, |v| ${field.nullable?'matches!(v, SourceValue::Null) || ':''}${guard(field.ref,'v')})`).join('');
    }
    throw new Error(`Unsupported union alternative: ${node.id}`);
  };
  const anchored = new Set<string>();
  const checkAliases=(ref:string,seen=new Set<string>()):void=>{
    const node=normalized(ref);
    if(anchored.has(node.id))return;
    const children=node.kind==='array'?[node.element]:node.kind==='tuple'?node.elements.map(element=>element.ref)
      :node.kind==='object' && node.indexSignatures.length && !node.fields.length?node.indexSignatures.map(index=>index.value):[];
    if(!children.length)return;
    if(seen.has(node.id))throw new Error(`Recursive collection aliases need a nominal anchor: ${node.id}`);
    const next=new Set(seen).add(node.id);children.forEach(ref=>checkAliases(ref,next));anchored.add(node.id);
  };
  const allocate = (hint: string) => {
    const name = pascal(hint);
    if (!/^[A-Z][A-Za-z0-9]*$/.test(name) || name === 'Self' || usedNames.has(name)) throw new Error(`Rust name collision or invalid name: ${name}`);
    usedNames.add(name);
    return name;
  };
  const depend = (module: string, owner: Owner) => {
    const output = moduleFor(module);
    output.typeDependencies.add(owner);
    if (owner.module && owner.module !== module) {
      if (!output.imports.has(owner.module)) output.imports.set(owner.module, new Set());
      output.imports.get(owner.module)!.add(owner.parser);
    } else if (!owner.module) output.helpers.add(owner.parser);
    return owner;
  };
  // Inline tuples import their element types, while sharing only their parser.
  const importType=(module:string,owner:Owner,seen=new Set<Owner>()):void=>{
    if(seen.has(owner))return;seen.add(owner);
    const output=moduleFor(module);
    if(owner.inline) {owner.typeDependencies?.forEach(child=>importType(module,child,seen));return;}
    if(owner.type==='Number')output.number=true;
    else if(owner.module && owner.module!==module && owner.type!=='bool') {
      if(!output.imports.has(owner.module))output.imports.set(owner.module,new Set());
      output.imports.get(owner.module)!.add(owner.type);
    }
  };
  const emit = (ref: string, hint: string, module: string): Owner => {
    const node = normalized(ref);
    checkAliases(ref);
    const key = signature(node);
    const existing = owners.get(key);
    if (existing) return depend(module, existing);
    if (node.kind === 'primitive') {
      const primitives: Record<string, { type: string; parser: string }> = { string: { type: 'String', parser: 'string' }, number: { type: 'Number', parser: 'number' },
        boolean: { type: 'bool', parser: 'boolean' } };
      const value = primitives[node.value];
      if (!value) throw new Error(`Unsupported primitive: ${node.value}`);
      return depend(module, value);
    }
    if (node.kind === 'open') return depend(module, {type:'SourceValue',
      parser:node.domain==='object'?'non_primitive':node.domain==='non-nullish'?'non_nullish':'unknown'});
    const scalarName=node.kind==='union' && node.members.every(ref=>atomicDomain(lookup(ref))!==undefined)
      ? node.members.map(ref=>pascal(atomicDomain(lookup(ref))!)).join('Or'):undefined;
    const name = allocate(node.kind === 'array' || node.kind === 'object' && node.indexSignatures.length && !node.fields.length ? hint : node.name ?? scalarName ?? hint);
    const value: Owner = { type: name, parser: `read_${snake(name)}`, module, allocated:name,
      ...(node.kind==='tuple' && !node.name?{inline:true}:{}) };
    owners.set(key, value);
    const output = moduleFor(module);
    if(node.kind==='tuple') {
      const children=node.elements.map((element,index)=>{
        const child=emit(element.ref,name+'Entry'+(index+1),module);
        const boxed=boxedEdge(node,element.ref);
        return {child,parse:`${child.parser}(&values[${index}], c, &format!("{p}[${index}]"))?`,boxed};
      });
      const tupleType=()=>children.length?`(${children.map(({child,boxed})=>boxed?`Box<${child.type}>`:child.type).join(', ')}${children.length===1?',':''})`:'[(); 0]';
      value.typeDependencies=children.map(({child})=>child);
      // Render types after emission: recursive union arms can reach this owner
      // before its tuple elements have finished allocating their nominal owners.
      if(value.inline)Object.defineProperty(value,'type',{get:tupleType});else output.types.add(name);
      value.typeDependencies.forEach(child=>output.typeDependencies.add(child));output.helpers.add('tuple');
      output.declarations.push(()=>`// Source declaration: ${node.id}
${value.inline?'':`pub type ${name} = ${tupleType()};\n`}pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${value.type}> {
    ${children.length?'let values = ':''}tuple(v, c, p, ${children.length})?;
    Ok(${children.length?`(${children.map(child=>child.boxed?`Box::new(${child.parse})`:child.parse).join(', ')}${children.length===1?',':''})`:'[]'})
}`);
      return value;
    }
    if (node.kind === 'array' || node.kind === 'object' && node.indexSignatures.length && !node.fields.length) {
      const array = node.kind === 'array';
      const childRef = array ? node.element : node.indexSignatures[0].value;
      const empty = array && lookup(childRef).kind === 'primitive' && (lookup(childRef) as GraphNode & { value: string }).value === 'never';
      const child = empty ? { type: 'String', parser: '|v, c, p| Err(c.error(p, "no array elements", v))' }
        : array && openTraitArrays.has(node.id) ? depend(module, { type: 'String', parser: 'string' }) : emit(childRef, name + 'Entry', module);
      output.types.add(name);
      output.helpers.add(array ? 'array' : 'keyed');
      output.declarations.push(()=>`// Source declaration: ${node.id}${array && openTraitArrays.has(node.id) ? '; trait identifiers intentionally remain open strings.' : ''}
pub type ${name} = ${array ? 'Vec' : 'crate::source_model::SourceMap'}<${child.type}>;
pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${name}> {
    ${array ? 'array' : 'keyed'}(v, c, p, ${child.parser})
}`);
      return value;
    }
    if (node.kind === 'object' || node.kind === 'intersection') {
      output.object = output.serialize = true;
      output.types.add(name);
      const fields = node.fields.filter(field => !field.forbidden).map(field => {
        const child = emit(field.ref, name + pascal(field.name), module);
        const boxed=boxedEdge(node,field.ref);
        return { field, child, rust: rustField(snake(field.name)),boxed };
      });
      const indexed = node.kind==='object' && node.indexSignatures.length
        ? emit(node.indexSignatures[0].value, name+'IndexedEntry', module) : undefined;
      const forbidden = node.fields.filter(field=>field.forbidden).map(field=>rustString(field.name)).join(', ');
      const names = fields.map(field => field.rust);
      if (new Set(names).size !== names.length || names.includes('additional_fields')
        || indexed && names.includes('indexed_fields')
        )
        throw new Error(`Invalid or unsupported Rust field names: ${node.id}`);
      output.declarations.push(()=>`// Source declaration: ${node.id}
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ${name} {
${fields.map(({ field, child, rust, boxed }) => `    // Declared optional=${field.optional}, nullable=${field.nullable}; retained before defaults.
    pub ${rust}: SourcePresence<${boxed?`Box<${child.type}>`:child.type}>,`).join('\n')}
${indexed?`    pub indexed_fields: crate::source_model::SourceMap<${indexed.type}>,\n`:''}    pub additional_fields: SourceObject,
}
pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${name}> {
    let f = Fields::new(v, c, p)?;
    Ok(${name} {
${fields.map(({ field, child, rust, boxed }) => `        ${rust}: f.presence(${rustString(field.name)}, ${boxed?`|v, c, p| ${child.parser}(v, c, p).map(Box::new)`:child.parser})?,`).join('\n')}
${indexed?`        indexed_fields: f.indexed(&[${fields.map(({field})=>rustString(field.name)).join(', ')}], &[${forbidden}], ${indexed.parser})?,\n        additional_fields: f.retained(&[${forbidden}]),`
        :`        additional_fields: f.remaining(&[${fields.map(({field})=>rustString(field.name)).join(', ')}]),`}
    })
}`);
      return value;
    }
    const members = node.kind === 'union' ? node.members.map(lookup) : [node];
    if (!members.length) throw new Error(`Selected union has no supported value alternatives: ${node.id}`);
    if (members.every(member => member.kind === 'literal' && typeof member.value === 'string')) {
      output.serialize = true;
      output.helpers.add('string');
      output.types.add(name);
      const tokens = members.map(member => (member as GraphNode & { value: string }).value).sort();
      const variants = tokens.map(token => pascal(/^[A-Z]+$/.test(token) ? token.toLowerCase() : token));
      if (new Set(variants).size !== variants.length || variants.some(variant => !/^[A-Z][A-Za-z0-9]*$/.test(variant)))
        throw new Error(`Unrepresentable literal variants: ${node.id}`);
      output.declarations.push(`#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum ${name} {
${tokens.map((token, index) => `    #[serde(rename = ${rustString(token)})]
    ${variants[index]},`).join('\n')}
}
pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${name}> {
    match string(v, c, p)?.as_str() {
${tokens.map((token, index) => `        ${rustString(token)} => Ok(${name}::${variants[index]}),`).join('\n')}
        _ => Err(c.error(p, ${rustString(tokens.join(' | '))}, v)),
    }
}`);
      return value;
    }
    if (members.every(member => member.kind === 'literal' && typeof member.value === 'number')) {
      const numbers = members.map(member => (member as GraphNode & { value: number }).value);
      if (numbers.some(value => !Number.isSafeInteger(value))) throw new Error(`Unsafe numeric literal: ${node.id}`);
      value.type = 'Number';
      output.number = true;
      output.helpers.add('number');
      output.declarations.push(`pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<Number> {
    let value = number(v, c, p)?;
    if value.as_f64().is_some_and(|n| [${numbers.map(n => n.toFixed(1)).join(', ')}].contains(&n)) {
        Ok(value)
    } else {
        Err(c.error(p, ${rustString(numbers.join(' | '))}, v))
    }
}`);
      return value;
    }
    if(node.kind==='literal' && typeof node.value==='boolean') {
      value.type='bool';output.helpers.add('boolean');
      output.declarations.push(`pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<bool> {
    let value = boolean(v, c, p)?;
    if ${node.value?'value':'!value'} { Ok(value) } else { Err(c.error(p, "${node.value}", v)) }
}`);return value;
    }
    if(node.kind!=='union')throw new Error(`Unsupported selected union: ${node.id}`);
    output.serialize=true;output.types.add(name);output.helpers.add('UnionCandidates');
    const alternatives=members.map((member,index)=>{
      const child=emit(member.id,name+'Alternative'+(index+1),module);
      const variant=pascal(member.name ?? (member.kind==='primitive'?member.value:member.kind==='open'?member.domain:'Alternative'+(index+1)));
      const boxed=boxedEdge(node,member.id);
      if(member.kind==='object' || member.kind==='intersection') output.helpers.add('union_required');
      if(member.kind==='object' || member.kind==='intersection') output.helpers.add('union_object');
      const condition=guard(member.id,'v');
      if(condition.includes('union_member(')) output.helpers.add('union_member');
      if(condition.includes('union_object(')) output.helpers.add('union_object');
      const required=member.kind==='object' || member.kind==='intersection' ? member.fields.filter(field=>!field.forbidden && !field.optional && !field.undefinedAllowed) : [];
      const validate=member.kind==='object' || member.kind==='intersection'
        ? `union_required(v, c, p, &[${required.map(field=>`(${rustString(field.name)}, ${field.nullable})`).join(', ')}]).and_then(|()| ${child.parser}(v, c, p))` : `${child.parser}(v, c, p)`;
      return {variant,child,boxed,condition,
        parse:validate+(boxed?`.map(Box::new)`:'' )+`.map(${name}::${variant})`};
    });
    if(new Set(alternatives.map(a=>a.variant)).size!==alternatives.length)throw new Error(`Union variant collision: ${node.id}`);
    output.declarations.push(()=>`// Source declaration: ${node.id}
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(untagged)]
pub enum ${name} {
${alternatives.map(a=>`    ${a.variant}(${a.boxed?`Box<${a.child.type}>`:a.child.type}),`).join('\n')}
}
pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${name}> {
    let mut candidates = UnionCandidates::new();
${alternatives.map(a=>`    if ${a.condition} {
        candidates.push("${a.variant}", || ${a.parse});
    }`).join('\n')}
    candidates.finish(v, c, p)
}`);
    return value;
  };
  const rootExports: string[] = [];
  for (const selection of input.selection) {
    if(selection.valueRef) {
      const root=lookup(selection.valueRef);
      if(root.kind==='union' && root.members.some(ref=>['primitive:null','primitive:undefined'].includes(ref)))
        throw new Error(`Nullable value roots need an explicit model: ${selection.valueRef}`);
    }
    const id = `selection:${selection.name}`;
    nodes.set(id, { id, name: selection.name, kind: 'object', fields: selection.fields, indexSignatures: [] });
    const value = emit(selection.valueRef ?? id, selection.name, selection.module);
    const alias = value.type === selection.name ? '' : `pub type ${selection.name} = ${value.type};\n`;
    const output = moduleFor(selection.module);
    if (alias) {
      if (usedNames.has(selection.name) && value.allocated!==selection.name) throw new Error(`Rust name collision: ${selection.name}`);
      usedNames.add(selection.name);
      output.types.add(selection.name);
    }
    output.declarations.push(`// ${selection.declaration}; deferred fields: ${selection.deferred.join(', ')}
${alias}pub(in crate::source_model) fn parse_${snake(selection.name)}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${selection.name}> {
    ${value.parser}(v, c, p)
}`);
    if (!selection.family) rootExports.push(`pub(super) use ${selection.module.replaceAll('/', '::')}::parse_${snake(selection.name)};`);
  }
  const children = new Map<string, Set<string>>();
  const familyRoots = input.selection.filter(root => root.family);
  if (familyRoots.length) {
    if (new Set(familyRoots.map(root => root.family)).size !== familyRoots.length) throw new Error('Duplicate Item trait family');
    const output = moduleFor('items/traits');
    output.serialize = true;
    output.types.add('ItemTraits');
    for (const root of familyRoots) {
      if (root.module === 'items/traits') continue;
      if (!output.imports.has(root.module)) output.imports.set(root.module, new Set());
      output.imports.get(root.module)!.add(root.name);
      output.imports.get(root.module)!.add(`parse_${snake(root.name)}`);
    }
    output.declarations.push(`#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(untagged)]
pub enum ItemTraits {
${familyRoots.map(root => `    ${pascal(root.family!)}(${root.name}),`).join('\n')}
}
pub(in crate::source_model) fn parse_item_traits(family: &str, v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<ItemTraits> {
    match family {
${familyRoots.map(root => `        ${rustString(root.family!)} => parse_${snake(root.name)}(v, c, p).map(ItemTraits::${pascal(root.family!)}),`).join('\n')}
        _ => Err(c.message(p, "registered Item family", family)),
    }
}`);
    rootExports.push('pub(super) use items::traits::parse_item_traits;');
    output.declarations.push(`pub(in crate::source_model) const ITEM_FAMILIES: &[&str] = &[${familyRoots.map(root => rustString(root.family!)).join(', ')}];`);
    rootExports.push('pub(super) use items::traits::ITEM_FAMILIES;');
  }
  for (const name of modules.keys()) {
    const parts = name.split('/');
    for (let index = 0; index < parts.length; index++) {
      const parent = parts.slice(0, index).join('/');
      if (!children.has(parent)) children.set(parent, new Set());
      children.get(parent)!.add(parts[index]);
    }
  }
  const header = `${generatedHeader}
// Partial source model for PF2e ${input.source.system_version}; source digest ${input.source.source_digest}.
// SourcePresence intentionally preserves missing/null before Foundry defaults.
${openTraitArrays.size ? '// Explicit trait-array policies keep identifiers as strings; declaration vocabularies remain in snapshots.\n' : ''}
`;
  const files: Record<string, string> = {};
  for (const name of new Set([...modules.keys(), ...children.keys()])) {
    const output = modules.get(name);
    const lines = [...(children.get(name) ?? [])].sort().map(child => `pub(in crate::source_model::generated) mod ${child};`);
    if (output) {
      output.typeDependencies.forEach(owner=>importType(name,owner));
      if (output.serialize) lines.push('use serde::Serialize;');
      if (output.number) lines.push('use serde_json::Number;');
      if (output.object) lines.push('use crate::source_model::presence::SourcePresence;');
      lines.push(`use crate::source_model::value::{${output.object ? 'SourceObject, ' : ''}SourceValue};`);
      const unionHelpers=[...output.helpers].filter(helper=>helper.startsWith('union_') || helper==='UnionCandidates').sort();
      const parseHelpers=[...output.helpers].filter(helper=>!unionHelpers.includes(helper)).sort();
      lines.push(`use crate::source_model::parse::{ParseResult, SourceContext${output.object ? ', Fields' : ''}${parseHelpers.map(helper => ', ' + helper).join('')}};`);
      if(unionHelpers.length)lines.push(`use crate::source_model::union::{${unionHelpers.join(', ')}};`);
      for (const [dependency, names] of [...output.imports].sort(([a], [b]) => a.localeCompare(b)))
        lines.push(`use crate::source_model::generated::${dependency.replaceAll('/', '::')}::{${[...names].sort().join(', ')}};`);
      lines.push('', output.declarations.map(declaration=>typeof declaration==='function'?declaration():declaration).join('\n\n'));
    }
    if (!name) {
      for (const [module, data] of modules) if (data.types.size)
        lines.push(`pub use ${module.replaceAll('/', '::')}::{${[...data.types].sort().join(', ')}};`);
      lines.push(...rootExports);
    }
    files[name ? `${name}.rs` : 'mod.rs'] = header + lines.join('\n') + '\n';
  }
  return files;
}
