import type { GraphNode } from './contracts.js';
import { validateInput, type GenerationInput } from './generation-input.js';

interface Owner { type: string; parser: string; module?: string }
interface RustModule {
  declarations: string[]; imports: Map<string, Set<string>>; types: Set<string>;
  helpers: Set<string>; object: boolean; number: boolean; serialize: boolean;
}
export const generatedHeader = '// Generated by scripts/source-contracts/generate.ts; do not edit.';

const pascal = (name: string) => name.replace(/[^A-Za-z0-9]+/g, ' ').split(/\s+/)
  .filter(Boolean).map(word => word[0].toUpperCase() + word.slice(1)).join('');
const snake = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
const rustString = (text: string) => JSON.stringify(text).replace(/\\u([0-9a-f]{4})/gi, '\\u{$1}');

/** Emit only supported, reachable value shapes. SourcePresence retains pre-default states. */
export function generateRustModules(input: GenerationInput): Record<string, string> {
  validateInput(input);
  const nodes = new Map(input.nodes.map(node => [node.id, node]));
  if (nodes.size !== input.nodes.length) throw new Error('Duplicate generation node identities');
  const modules = new Map<string, RustModule>();
  const moduleFor = (name: string) => {
    if (!modules.has(name)) modules.set(name, { declarations: [], imports: new Map(), types: new Set(),
      helpers: new Set(), object: false, number: false, serialize: false });
    return modules.get(name)!;
  };
  const owners = new Map<string, Owner>();
  const usedNames = new Set<string>();
  const lookup = (id: string): GraphNode => {
    const node = nodes.get(id);
    if (!node) throw new Error(`Missing generation node: ${id}`);
    return node;
  };
  const normalized = (id: string): GraphNode => {
    const node = lookup(id);
    if (node.kind !== 'union') return node;
    const members = node.members.filter(id => !['primitive:null', 'primitive:undefined'].includes(id));
    if (members.length === 1) return normalized(members[0]);
    if (members.length === 2 && members.every(id => lookup(id).kind === 'literal'
      && typeof (lookup(id) as GraphNode & { value: unknown }).value === 'boolean')) {
      return { id: 'primitive:boolean', kind: 'primitive', value: 'boolean' };
    }
    return { ...node, members };
  };
  const signature = (node: GraphNode, ancestors = new Set<string>()): string => {
    if (ancestors.has(node.id)) throw new Error(`Recursive selected shape is outside this trial: ${node.id}`);
    const next = new Set([...ancestors, node.id]);
    const child = (ref: string) => signature(normalized(ref), next);
    if (node.kind === 'object' || node.kind === 'intersection') {
      if (node.kind === 'object' && node.indexSignatures.length) throw new Error(`Selected index signature is unsupported: ${node.id}`);
      if (node.kind === 'intersection') for (const member of node.members) {
        const constituent = normalized(member);
        if (constituent.kind !== 'object' && constituent.kind !== 'intersection')
          throw new Error(`Unsupported selected intersection member: ${member}`);
        child(member); // Resolved fields do not encode index-signature constraints.
      }
      return JSON.stringify(node.fields.map(field => [field.name, field.forbidden, child(field.ref)]));
    }
    if (node.kind === 'union') return JSON.stringify(node.members.map(child).sort());
    if (node.kind === 'array') return `array:${child(node.element)}`;
    if (node.kind === 'primitive' || node.kind === 'literal') return JSON.stringify([node.kind, node.value]);
    throw new Error(`Unsupported selected construct: ${node.id} (${node.kind})`);
  };
  const allocate = (hint: string) => {
    const name = pascal(hint);
    if (!/^[A-Z][A-Za-z0-9]*$/.test(name) || name === 'Self' || usedNames.has(name)) throw new Error(`Rust name collision or invalid name: ${name}`);
    usedNames.add(name);
    return name;
  };
  const depend = (module: string, owner: Owner) => {
    const output = moduleFor(module);
    if (owner.module && owner.module !== module) {
      if (!output.imports.has(owner.module)) output.imports.set(owner.module, new Set());
      if (owner.type !== 'Number') output.imports.get(owner.module)!.add(owner.type);
      output.imports.get(owner.module)!.add(owner.parser);
    } else if (!owner.module) output.helpers.add(owner.parser);
    if (owner.type === 'Number') output.number = true;
    return owner;
  };
  const emit = (ref: string, hint: string, module: string): Owner => {
    const node = normalized(ref);
    const key = signature(node);
    const existing = owners.get(key);
    if (existing) return depend(module, existing);
    if (node.kind === 'primitive') {
      const primitives: Record<string, { type: string; parser: string }> = { string: { type: 'String', parser: 'string' }, number: { type: 'Number', parser: 'number' },
        boolean: { type: 'bool', parser: 'boolean' } };
      const value = primitives[node.value];
      if (!value) throw new Error(`Unsupported primitive: ${node.value}`);
      return depend(module, value);
    }
    if (node.kind === 'array') throw new Error(`Selected arrays are outside this trial: ${node.id}`);
    const name = allocate(node.name ?? hint);
    const value: Owner = { type: name, parser: `read_${snake(name)}`, module };
    owners.set(key, value);
    const output = moduleFor(module);
    if (node.kind === 'object' || node.kind === 'intersection') {
      output.object = output.serialize = true;
      output.types.add(name);
      const fields = node.fields.map(field => {
        if (field.forbidden) throw new Error(`Forbidden selected field is outside this trial: ${node.id}.${field.name}`);
        const child = emit(field.ref, name + pascal(field.name), module);
        return { field, child, rust: snake(field.name) };
      });
      const names = fields.map(field => field.rust);
      if (new Set(names).size !== names.length || names.includes('additional_fields')
        || names.some(name => !/^[a-z][a-z0-9_]*$/.test(name)
          || ['type', 'self', 'mod', 'use', 'ref', 'match', 'struct', 'enum', 'pub', 'fn', 'const', 'static', 'let', 'loop', 'move', 'crate', 'super', 'where', 'trait', 'impl', 'async', 'await', 'dyn', 'in', 'as', 'if', 'else', 'return', 'break', 'continue', 'mut', 'unsafe', 'extern', 'for', 'while'].includes(name)))
        throw new Error(`Invalid or unsupported Rust field names: ${node.id}`);
      output.declarations.push(`// Source declaration: ${node.id}
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ${name} {
${fields.map(({ field, child, rust }) => `    // Declared optional=${field.optional}, nullable=${field.nullable}; retained before defaults.
    pub ${rust}: SourcePresence<${child.type}>,`).join('\n')}
    pub additional_fields: SourceObject,
}
pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${name}> {
    let f = Fields::new(v, c, p)?;
    Ok(${name} {
${fields.map(({ field, child, rust }) => `        ${rust}: f.presence(${rustString(field.name)}, ${child.parser})?,`).join('\n')}
        additional_fields: f.remaining(&[${fields.map(({ field }) => rustString(field.name)).join(', ')}]),
    })
}`);
      return value;
    }
    const members = node.kind === 'union' ? node.members.map(lookup) : [node];
    if (!members.length) throw new Error(`Selected union has no supported value alternatives: ${node.id}`);
    if (members.every(member => member.kind === 'literal' && typeof member.value === 'string')) {
      output.serialize = true;
      output.helpers.add('string');
      output.types.add(name);
      const tokens = members.map(member => (member as GraphNode & { value: string }).value).sort();
      const variants = tokens.map(pascal);
      if (new Set(variants).size !== variants.length || variants.some(variant => !/^[A-Z][A-Za-z0-9]*$/.test(variant)))
        throw new Error(`Unrepresentable literal variants: ${node.id}`);
      output.declarations.push(`#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum ${name} {
${tokens.map((token, index) => `    #[serde(rename = ${rustString(token)})]
    ${variants[index]},`).join('\n')}
}
pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${name}> {
    match string(v, c, p)?.as_str() {
${tokens.map((token, index) => `        ${rustString(token)} => Ok(${name}::${variants[index]}),`).join('\n')}
        _ => Err(c.error(p, ${rustString(tokens.join(' | '))}, v)),
    }
}`);
      return value;
    }
    if (members.every(member => member.kind === 'literal' && typeof member.value === 'number')) {
      const numbers = members.map(member => (member as GraphNode & { value: number }).value);
      if (numbers.some(value => !Number.isSafeInteger(value))) throw new Error(`Unsafe numeric literal: ${node.id}`);
      value.type = 'Number';
      output.number = true;
      output.helpers.add('number');
      output.declarations.push(`pub(in crate::source_model::generated) fn ${value.parser}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<Number> {
    let value = number(v, c, p)?;
    if value.as_f64().is_some_and(|n| [${numbers.map(n => n.toFixed(1)).join(', ')}].contains(&n)) {
        Ok(value)
    } else {
        Err(c.error(p, ${rustString(numbers.join(' | '))}, v))
    }
}`);
      return value;
    }
    throw new Error(`Unsupported selected union: ${node.id}`);
  };
  const rootExports: string[] = [];
  for (const selection of input.selection) {
    const id = `selection:${selection.name}`;
    nodes.set(id, { id, name: selection.name, kind: 'object', fields: selection.fields, indexSignatures: [] });
    const value = emit(id, selection.name, selection.module);
    const alias = value.type === selection.name ? '' : `pub type ${selection.name} = ${value.type};\n`;
    const output = moduleFor(selection.module);
    if (alias) {
      if (usedNames.has(selection.name)) throw new Error(`Rust name collision: ${selection.name}`);
      usedNames.add(selection.name);
      output.types.add(selection.name);
    }
    output.declarations.push(`// ${selection.declaration}; deferred fields: ${selection.deferred.join(', ')}
${alias}pub(in crate::source_model) fn parse_${snake(selection.name)}(v: &SourceValue, c: &SourceContext, p: &str) -> ParseResult<${selection.name}> {
    ${value.parser}(v, c, p)
}`);
    rootExports.push(`pub(super) use ${selection.module.replaceAll('/', '::')}::parse_${snake(selection.name)};`);
  }
  const children = new Map<string, Set<string>>();
  for (const name of modules.keys()) {
    const parts = name.split('/');
    for (let index = 0; index < parts.length; index++) {
      const parent = parts.slice(0, index).join('/');
      if (!children.has(parent)) children.set(parent, new Set());
      children.get(parent)!.add(parts[index]);
    }
  }
  const header = `${generatedHeader}
// Partial source model for PF2e ${input.source.system_version}; source digest ${input.source.source_digest}.
// SourcePresence intentionally preserves missing/null before Foundry defaults.
`;
  const files: Record<string, string> = {};
  for (const name of new Set([...modules.keys(), ...children.keys()])) {
    const output = modules.get(name);
    const lines = [...(children.get(name) ?? [])].sort().map(child => `pub(in crate::source_model::generated) mod ${child};`);
    if (output) {
      if (output.serialize) lines.push('use serde::Serialize;');
      if (output.number) lines.push('use serde_json::Number;');
      if (output.object) lines.push('use crate::source_model::presence::SourcePresence;');
      lines.push(`use crate::source_model::value::{${output.object ? 'SourceObject, ' : ''}SourceValue};`);
      lines.push(`use crate::source_model::parse::{ParseResult, SourceContext${output.object ? ', Fields' : ''}${[...output.helpers].sort().map(helper => ', ' + helper).join('')}};`);
      for (const [dependency, names] of [...output.imports].sort(([a], [b]) => a.localeCompare(b)))
        lines.push(`use crate::source_model::generated::${dependency.replaceAll('/', '::')}::{${[...names].sort().join(', ')}};`);
      lines.push('', output.declarations.join('\n\n'));
    }
    if (!name) {
      for (const [module, data] of modules) if (data.types.size)
        lines.push(`pub use ${module.replaceAll('/', '::')}::{${[...data.types].sort().join(', ')}};`);
      lines.push(...rootExports);
    }
    files[name ? `${name}.rs` : 'mod.rs'] = header + lines.join('\n') + '\n';
  }
  return files;
}
