-- Roll back this schema only. Existing artifacts are rebuilt, never migrated between authorities.
PRAGMA foreign_keys=OFF;
DROP TABLE IF EXISTS semantic_vectors;
DROP TABLE IF EXISTS lexical_fts;
DROP TABLE IF EXISTS semantic_units;
DROP TABLE IF EXISTS semantic_models;
DROP TABLE IF EXISTS lexical_units;
DROP TABLE IF EXISTS query_field_catalog;
DROP TABLE IF EXISTS remaster_pairs;
DROP TABLE IF EXISTS verified_aliases;
DROP TABLE IF EXISTS relationship_occurrences;
DROP TABLE IF EXISTS developer_diagnostics;
DROP TABLE IF EXISTS prepared_content;
DROP TABLE IF EXISTS record_bodies;
DROP TABLE IF EXISTS artifact_context;
DROP TABLE IF EXISTS deity_fonts;
DROP TABLE IF EXISTS deity_domains;
DROP TABLE IF EXISTS deity_projection;
DROP TABLE IF EXISTS condition_projection;
DROP TABLE IF EXISTS effect_projection;
DROP TABLE IF EXISTS heritage_projection;
DROP TABLE IF EXISTS ability_projection;
DROP TABLE IF EXISTS shield_projection;
DROP TABLE IF EXISTS armor_projection;
DROP TABLE IF EXISTS weapon_projection;
DROP TABLE IF EXISTS physical_projection;
DROP TABLE IF EXISTS spell_damage_kinds;
DROP TABLE IF EXISTS spell_damage_entries;
DROP TABLE IF EXISTS spell_traditions;
DROP TABLE IF EXISTS spell_projection;
DROP TABLE IF EXISTS actor_senses;
DROP TABLE IF EXISTS actor_speeds;
DROP TABLE IF EXISTS actor_languages;
DROP TABLE IF EXISTS actor_iwr_entries;
DROP TABLE IF EXISTS actor_item_traits;
DROP TABLE IF EXISTS actor_items;
DROP TABLE IF EXISTS actor_projection;
DROP TABLE IF EXISTS record_traits;
DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS packs;
PRAGMA foreign_keys=ON;
PRAGMA user_version=0;
